/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Echo a greeting */
        get: operations["getPing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cli/auth/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve a pending CLI login (browser-initiated)
         * @description Called by the browser after the signed-in user confirms the CLI
         *     approval screen. Records a PKCE challenge and a human-friendly
         *     token name, returning a single-use exchange code that the browser
         *     redirects back to the CLI's localhost callback.
         */
        post: operations["approveCliAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cli/auth/exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange an approval code for a CLI token (public)
         * @description Called server-to-server by the CLI. Trades a one-time code plus the
         *     PKCE verifier for a long-lived bearer token. This endpoint is public
         *     because the CLI has no session yet when it calls it.
         */
        post: operations["exchangeCliAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cli/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the caller's CLI tokens */
        get: operations["listCliTokens"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cli/tokens/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke a CLI token */
        delete: operations["revokeCliToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orgs/{slug}/github/installations/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Begin a GitHub App install handshake
         * @description Issues a one-time CSRF state and returns the URL the browser should
         *     send the user to. After install, GitHub redirects back to the App's
         *     configured setup URL with `installation_id` and `state`; the SPA
         *     finishes the handshake via `/api/github/installations/complete`.
         */
        post: operations["startGithubInstall"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/github/installations/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finalize a GitHub App install handshake (Clerk session only)
         * @description Called by the SPA setup-callback page with the `state` and
         *     `installation_id` returned from GitHub. Verifies the state, fetches
         *     the installation from GitHub via App-level auth, and persists it
         *     scoped to the org that started the handshake. Not org-prefixed
         *     because the org is recovered from the state itself.
         */
        post: operations["completeGithubInstall"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orgs/{slug}/github/installations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List GitHub App installations connected to this org */
        get: operations["listGithubInstallations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orgs/{slug}/github/installations/{installationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Disconnect a GitHub App installation from this org
         * @description Drops Spacefleet's record of the installation. Does not uninstall
         *     the GitHub App on github.com — that's the user's choice.
         */
        delete: operations["deleteGithubInstallation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orgs/{slug}/github/installations/{installationId}/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List repositories accessible to a GitHub App installation
         * @description Mints a fresh installation access token and enumerates the repos
         *     the App has been granted on. This is what the build pipeline will
         *     clone from.
         */
        get: operations["listGithubInstallationRepositories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cli/whoami": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Return the user associated with the CLI token
         * @description Smoke-test endpoint for the CLI — confirms a token is valid and
         *     reports whose identity it carries. Clerk-authenticated calls also
         *     work; they simply echo the Clerk session's user id.
         */
        get: operations["cliWhoami"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @enum {string} */
            status: "ok";
        };
        Greeting: {
            message: string;
        };
        Error: {
            code: string;
            message: string;
        };
        CliApproveRequest: {
            /** @description User-chosen label for the token (e.g. hostname). */
            name: string;
            /** @description Base64url(sha256(verifier)) — the CLI's PKCE challenge. */
            challenge: string;
        };
        CliApproveResponse: {
            /** @description Single-use exchange code, valid for ~5 minutes. */
            code: string;
        };
        CliExchangeRequest: {
            code: string;
            verifier: string;
        };
        CliExchangeResponse: {
            /** @description The bearer token. Returned exactly once — not recoverable later. */
            token: string;
            name: string;
            /** Format: date-time */
            expires_at: string;
        };
        CliToken: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            expires_at: string;
            /** Format: date-time */
            last_used_at?: string | null;
            /** Format: date-time */
            revoked_at?: string | null;
        };
        CliTokenList: {
            tokens: components["schemas"]["CliToken"][];
        };
        CliWhoami: {
            user_id: string;
            /** @enum {string} */
            source: "clerk" | "cli";
        };
        GithubInstallStart: {
            /**
             * Format: uri
             * @description Send the user here to install the App. State is embedded in the
             *     URL; the caller does not need to track it.
             */
            url: string;
        };
        GithubInstallCompleteRequest: {
            state: string;
            /** Format: int64 */
            installation_id: number;
        };
        GithubInstallCompleteResponse: {
            installation: components["schemas"]["GithubInstallation"];
            /** @description The org the installation was bound to. Use it to redirect. */
            org_slug: string;
        };
        GithubInstallation: {
            /** Format: uuid */
            id: string;
            /** Format: int64 */
            installation_id: number;
            account_login: string;
            /** @description "User" or "Organization" (mirrors GitHub). */
            account_type: string;
            /** Format: int64 */
            account_id: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            suspended_at?: string | null;
        };
        GithubInstallationList: {
            installations: components["schemas"]["GithubInstallation"][];
        };
        GithubRepository: {
            /** Format: int64 */
            id: number;
            name: string;
            full_name: string;
            private: boolean;
            default_branch: string;
            /** Format: uri */
            html_url: string;
        };
        GithubRepositoryList: {
            repositories: components["schemas"]["GithubRepository"][];
        };
    };
    responses: {
        /** @description Error response */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        OrgSlug: string;
        InstallationID: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getPing: {
        parameters: {
            query?: {
                name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Greeting */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Greeting"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    approveCliAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CliApproveRequest"];
            };
        };
        responses: {
            /** @description Approval recorded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CliApproveResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    exchangeCliAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CliExchangeRequest"];
            };
        };
        responses: {
            /** @description Token issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CliExchangeResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listCliTokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token metadata (no plaintext) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CliTokenList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    revokeCliToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked (idempotent) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    startGithubInstall: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["OrgSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Install URL ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GithubInstallStart"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    completeGithubInstall: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GithubInstallCompleteRequest"];
            };
        };
        responses: {
            /** @description Installation persisted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GithubInstallCompleteResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listGithubInstallations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["OrgSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Installations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GithubInstallationList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteGithubInstallation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["OrgSlug"];
                installationId: components["parameters"]["InstallationID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Disconnected (idempotent) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    listGithubInstallationRepositories: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["OrgSlug"];
                installationId: components["parameters"]["InstallationID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Repositories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GithubRepositoryList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    cliWhoami: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Identity echo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CliWhoami"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
