//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CliWhoamiSource.
const (
	Clerk CliWhoamiSource = "clerk"
	Cli   CliWhoamiSource = "cli"
)

// Valid indicates whether the value is a known member of the CliWhoamiSource enum.
func (e CliWhoamiSource) Valid() bool {
	switch e {
	case Clerk:
		return true
	case Cli:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// CliApproveRequest defines model for CliApproveRequest.
type CliApproveRequest struct {
	// Challenge Base64url(sha256(verifier)) — the CLI's PKCE challenge.
	Challenge string `json:"challenge"`

	// Name User-chosen label for the token (e.g. hostname).
	Name string `json:"name"`
}

// CliApproveResponse defines model for CliApproveResponse.
type CliApproveResponse struct {
	// Code Single-use exchange code, valid for ~5 minutes.
	Code string `json:"code"`
}

// CliExchangeRequest defines model for CliExchangeRequest.
type CliExchangeRequest struct {
	Code     string `json:"code"`
	Verifier string `json:"verifier"`
}

// CliExchangeResponse defines model for CliExchangeResponse.
type CliExchangeResponse struct {
	ExpiresAt time.Time `json:"expires_at"`
	Name      string    `json:"name"`

	// Token The bearer token. Returned exactly once — not recoverable later.
	Token string `json:"token"`
}

// CliToken defines model for CliToken.
type CliToken struct {
	CreatedAt  time.Time          `json:"created_at"`
	ExpiresAt  time.Time          `json:"expires_at"`
	Id         openapi_types.UUID `json:"id"`
	LastUsedAt *time.Time         `json:"last_used_at,omitempty"`
	Name       string             `json:"name"`
	RevokedAt  *time.Time         `json:"revoked_at,omitempty"`
}

// CliTokenList defines model for CliTokenList.
type CliTokenList struct {
	Tokens []CliToken `json:"tokens"`
}

// CliWhoami defines model for CliWhoami.
type CliWhoami struct {
	Source CliWhoamiSource `json:"source"`
	UserId string          `json:"user_id"`
}

// CliWhoamiSource defines model for CliWhoami.Source.
type CliWhoamiSource string

// CloudAccount defines model for CloudAccount.
type CloudAccount struct {
	// AccountId 12-digit AWS account ID (empty until onboarding completes).
	AccountId             *string            `json:"account_id,omitempty"`
	CreatedAt             time.Time          `json:"created_at"`
	Id                    openapi_types.UUID `json:"id"`
	Label                 string             `json:"label"`
	LastVerificationError *string            `json:"last_verification_error,omitempty"`
	LastVerifiedAt        *time.Time         `json:"last_verified_at,omitempty"`

	// Provider Cloud provider — only "aws" today.
	Provider string  `json:"provider"`
	Region   *string `json:"region,omitempty"`
	RoleArn  *string `json:"role_arn,omitempty"`

	// Status pending | connected | error | disabled.
	Status    string    `json:"status"`
	UpdatedAt time.Time `json:"updated_at"`
}

// CloudAccountCompleteRequest defines model for CloudAccountCompleteRequest.
type CloudAccountCompleteRequest struct {
	// RoleArn From the stack's Outputs.RoleArn.
	RoleArn string `json:"role_arn"`
}

// CloudAccountList defines model for CloudAccountList.
type CloudAccountList struct {
	Accounts []CloudAccount `json:"accounts"`
}

// CloudAccountStartRequest defines model for CloudAccountStartRequest.
type CloudAccountStartRequest struct {
	// Label Human-friendly name like "acme-prod". Unique per org.
	Label string `json:"label"`

	// Region Optional default region for the Quick Create link.
	Region *string `json:"region,omitempty"`
}

// CloudAccountStartResponse defines model for CloudAccountStartResponse.
type CloudAccountStartResponse struct {
	Account CloudAccount `json:"account"`

	// ExternalId Returned exactly once. Treat as a secret. Embedded in the
	// CloudFormation trust policy and presented on every AssumeRole.
	ExternalId string `json:"external_id"`

	// PlatformAccountId The AWS account ID Spacefleet is running in — what the
	// customer's IAM trust policy will allow AssumeRole from.
	PlatformAccountId string `json:"platform_account_id"`

	// QuickCreateUrl CloudFormation Quick Create URL with the platform account ID
	// and external ID pre-filled. Send the customer here.
	QuickCreateUrl string `json:"quick_create_url"`
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// GithubInstallCompleteRequest defines model for GithubInstallCompleteRequest.
type GithubInstallCompleteRequest struct {
	InstallationId int64  `json:"installation_id"`
	State          string `json:"state"`
}

// GithubInstallCompleteResponse defines model for GithubInstallCompleteResponse.
type GithubInstallCompleteResponse struct {
	Installation GithubInstallation `json:"installation"`

	// OrgSlug The org the installation was bound to. Use it to redirect.
	OrgSlug string `json:"org_slug"`
}

// GithubInstallStart defines model for GithubInstallStart.
type GithubInstallStart struct {
	// Url Send the user here to install the App. State is embedded in the
	// URL; the caller does not need to track it.
	Url string `json:"url"`
}

// GithubInstallation defines model for GithubInstallation.
type GithubInstallation struct {
	AccountId    int64  `json:"account_id"`
	AccountLogin string `json:"account_login"`

	// AccountType "User" or "Organization" (mirrors GitHub).
	AccountType    string             `json:"account_type"`
	CreatedAt      time.Time          `json:"created_at"`
	Id             openapi_types.UUID `json:"id"`
	InstallationId int64              `json:"installation_id"`
	SuspendedAt    *time.Time         `json:"suspended_at,omitempty"`
	UpdatedAt      time.Time          `json:"updated_at"`
}

// GithubInstallationList defines model for GithubInstallationList.
type GithubInstallationList struct {
	Installations []GithubInstallation `json:"installations"`
}

// GithubRepository defines model for GithubRepository.
type GithubRepository struct {
	DefaultBranch string `json:"default_branch"`
	FullName      string `json:"full_name"`
	HtmlUrl       string `json:"html_url"`
	Id            int64  `json:"id"`
	Name          string `json:"name"`
	Private       bool   `json:"private"`
}

// GithubRepositoryList defines model for GithubRepositoryList.
type GithubRepositoryList struct {
	Repositories []GithubRepository `json:"repositories"`
}

// Greeting defines model for Greeting.
type Greeting struct {
	Message string `json:"message"`
}

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// CloudAccountID defines model for CloudAccountID.
type CloudAccountID = openapi_types.UUID

// InstallationID defines model for InstallationID.
type InstallationID = int64

// OrgSlug defines model for OrgSlug.
type OrgSlug = string

// GetPingParams defines parameters for GetPing.
type GetPingParams struct {
	Name *string `form:"name,omitempty" json:"name,omitempty"`
}

// ApproveCliAuthJSONRequestBody defines body for ApproveCliAuth for application/json ContentType.
type ApproveCliAuthJSONRequestBody = CliApproveRequest

// ExchangeCliAuthJSONRequestBody defines body for ExchangeCliAuth for application/json ContentType.
type ExchangeCliAuthJSONRequestBody = CliExchangeRequest

// CompleteGithubInstallJSONRequestBody defines body for CompleteGithubInstall for application/json ContentType.
type CompleteGithubInstallJSONRequestBody = GithubInstallCompleteRequest

// StartAwsAccountJSONRequestBody defines body for StartAwsAccount for application/json ContentType.
type StartAwsAccountJSONRequestBody = CloudAccountStartRequest

// CompleteAwsAccountJSONRequestBody defines body for CompleteAwsAccount for application/json ContentType.
type CompleteAwsAccountJSONRequestBody = CloudAccountCompleteRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Approve a pending CLI login (browser-initiated)
	// (POST /api/cli/auth/approve)
	ApproveCliAuth(w http.ResponseWriter, r *http.Request)
	// Exchange an approval code for a CLI token (public)
	// (POST /api/cli/auth/exchange)
	ExchangeCliAuth(w http.ResponseWriter, r *http.Request)
	// List the caller's CLI tokens
	// (GET /api/cli/tokens)
	ListCliTokens(w http.ResponseWriter, r *http.Request)
	// Revoke a CLI token
	// (DELETE /api/cli/tokens/{id})
	RevokeCliToken(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Return the user associated with the CLI token
	// (GET /api/cli/whoami)
	CliWhoami(w http.ResponseWriter, r *http.Request)
	// Finalize a GitHub App install handshake (Clerk session only)
	// (POST /api/github/installations/complete)
	CompleteGithubInstall(w http.ResponseWriter, r *http.Request)
	// Liveness probe
	// (GET /api/health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// List AWS cloud accounts connected to this org
	// (GET /api/orgs/{slug}/aws/accounts)
	ListAwsAccounts(w http.ResponseWriter, r *http.Request, slug OrgSlug)
	// Begin AWS cloud-account onboarding
	// (POST /api/orgs/{slug}/aws/accounts)
	StartAwsAccount(w http.ResponseWriter, r *http.Request, slug OrgSlug)
	// Disconnect an AWS cloud account
	// (DELETE /api/orgs/{slug}/aws/accounts/{id})
	DeleteAwsAccount(w http.ResponseWriter, r *http.Request, slug OrgSlug, id CloudAccountID)
	// Get a single AWS cloud account
	// (GET /api/orgs/{slug}/aws/accounts/{id})
	GetAwsAccount(w http.ResponseWriter, r *http.Request, slug OrgSlug, id CloudAccountID)
	// Finalize AWS onboarding by submitting the role ARN
	// (POST /api/orgs/{slug}/aws/accounts/{id}/complete)
	CompleteAwsAccount(w http.ResponseWriter, r *http.Request, slug OrgSlug, id CloudAccountID)
	// Re-run the verification probe against a cloud account
	// (POST /api/orgs/{slug}/aws/accounts/{id}/verify)
	VerifyAwsAccount(w http.ResponseWriter, r *http.Request, slug OrgSlug, id CloudAccountID)
	// List GitHub App installations connected to this org
	// (GET /api/orgs/{slug}/github/installations)
	ListGithubInstallations(w http.ResponseWriter, r *http.Request, slug OrgSlug)
	// Begin a GitHub App install handshake
	// (POST /api/orgs/{slug}/github/installations/start)
	StartGithubInstall(w http.ResponseWriter, r *http.Request, slug OrgSlug)
	// Disconnect a GitHub App installation from this org
	// (DELETE /api/orgs/{slug}/github/installations/{installationId})
	DeleteGithubInstallation(w http.ResponseWriter, r *http.Request, slug OrgSlug, installationId InstallationID)
	// List repositories accessible to a GitHub App installation
	// (GET /api/orgs/{slug}/github/installations/{installationId}/repositories)
	ListGithubInstallationRepositories(w http.ResponseWriter, r *http.Request, slug OrgSlug, installationId InstallationID)
	// Echo a greeting
	// (GET /api/ping)
	GetPing(w http.ResponseWriter, r *http.Request, params GetPingParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ApproveCliAuth operation middleware
func (siw *ServerInterfaceWrapper) ApproveCliAuth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ApproveCliAuth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExchangeCliAuth operation middleware
func (siw *ServerInterfaceWrapper) ExchangeCliAuth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExchangeCliAuth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCliTokens operation middleware
func (siw *ServerInterfaceWrapper) ListCliTokens(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCliTokens(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeCliToken operation middleware
func (siw *ServerInterfaceWrapper) RevokeCliToken(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeCliToken(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CliWhoami operation middleware
func (siw *ServerInterfaceWrapper) CliWhoami(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CliWhoami(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CompleteGithubInstall operation middleware
func (siw *ServerInterfaceWrapper) CompleteGithubInstall(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CompleteGithubInstall(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAwsAccounts operation middleware
func (siw *ServerInterfaceWrapper) ListAwsAccounts(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug OrgSlug

	err = runtime.BindStyledParameterWithOptions("simple", "slug", r.PathValue("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAwsAccounts(w, r, slug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartAwsAccount operation middleware
func (siw *ServerInterfaceWrapper) StartAwsAccount(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug OrgSlug

	err = runtime.BindStyledParameterWithOptions("simple", "slug", r.PathValue("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartAwsAccount(w, r, slug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAwsAccount operation middleware
func (siw *ServerInterfaceWrapper) DeleteAwsAccount(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug OrgSlug

	err = runtime.BindStyledParameterWithOptions("simple", "slug", r.PathValue("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	// ------------- Path parameter "id" -------------
	var id CloudAccountID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAwsAccount(w, r, slug, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAwsAccount operation middleware
func (siw *ServerInterfaceWrapper) GetAwsAccount(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug OrgSlug

	err = runtime.BindStyledParameterWithOptions("simple", "slug", r.PathValue("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	// ------------- Path parameter "id" -------------
	var id CloudAccountID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAwsAccount(w, r, slug, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CompleteAwsAccount operation middleware
func (siw *ServerInterfaceWrapper) CompleteAwsAccount(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug OrgSlug

	err = runtime.BindStyledParameterWithOptions("simple", "slug", r.PathValue("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	// ------------- Path parameter "id" -------------
	var id CloudAccountID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CompleteAwsAccount(w, r, slug, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// VerifyAwsAccount operation middleware
func (siw *ServerInterfaceWrapper) VerifyAwsAccount(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug OrgSlug

	err = runtime.BindStyledParameterWithOptions("simple", "slug", r.PathValue("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	// ------------- Path parameter "id" -------------
	var id CloudAccountID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VerifyAwsAccount(w, r, slug, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListGithubInstallations operation middleware
func (siw *ServerInterfaceWrapper) ListGithubInstallations(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug OrgSlug

	err = runtime.BindStyledParameterWithOptions("simple", "slug", r.PathValue("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListGithubInstallations(w, r, slug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartGithubInstall operation middleware
func (siw *ServerInterfaceWrapper) StartGithubInstall(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug OrgSlug

	err = runtime.BindStyledParameterWithOptions("simple", "slug", r.PathValue("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartGithubInstall(w, r, slug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteGithubInstallation operation middleware
func (siw *ServerInterfaceWrapper) DeleteGithubInstallation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug OrgSlug

	err = runtime.BindStyledParameterWithOptions("simple", "slug", r.PathValue("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	// ------------- Path parameter "installationId" -------------
	var installationId InstallationID

	err = runtime.BindStyledParameterWithOptions("simple", "installationId", r.PathValue("installationId"), &installationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "installationId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteGithubInstallation(w, r, slug, installationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListGithubInstallationRepositories operation middleware
func (siw *ServerInterfaceWrapper) ListGithubInstallationRepositories(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug OrgSlug

	err = runtime.BindStyledParameterWithOptions("simple", "slug", r.PathValue("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	// ------------- Path parameter "installationId" -------------
	var installationId InstallationID

	err = runtime.BindStyledParameterWithOptions("simple", "installationId", r.PathValue("installationId"), &installationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "installationId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListGithubInstallationRepositories(w, r, slug, installationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPing operation middleware
func (siw *ServerInterfaceWrapper) GetPing(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPingParams

	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "name", r.URL.Query(), &params.Name, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPing(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/api/cli/auth/approve", wrapper.ApproveCliAuth)
	m.HandleFunc("POST "+options.BaseURL+"/api/cli/auth/exchange", wrapper.ExchangeCliAuth)
	m.HandleFunc("GET "+options.BaseURL+"/api/cli/tokens", wrapper.ListCliTokens)
	m.HandleFunc("DELETE "+options.BaseURL+"/api/cli/tokens/{id}", wrapper.RevokeCliToken)
	m.HandleFunc("GET "+options.BaseURL+"/api/cli/whoami", wrapper.CliWhoami)
	m.HandleFunc("POST "+options.BaseURL+"/api/github/installations/complete", wrapper.CompleteGithubInstall)
	m.HandleFunc("GET "+options.BaseURL+"/api/health", wrapper.GetHealth)
	m.HandleFunc("GET "+options.BaseURL+"/api/orgs/{slug}/aws/accounts", wrapper.ListAwsAccounts)
	m.HandleFunc("POST "+options.BaseURL+"/api/orgs/{slug}/aws/accounts", wrapper.StartAwsAccount)
	m.HandleFunc("DELETE "+options.BaseURL+"/api/orgs/{slug}/aws/accounts/{id}", wrapper.DeleteAwsAccount)
	m.HandleFunc("GET "+options.BaseURL+"/api/orgs/{slug}/aws/accounts/{id}", wrapper.GetAwsAccount)
	m.HandleFunc("POST "+options.BaseURL+"/api/orgs/{slug}/aws/accounts/{id}/complete", wrapper.CompleteAwsAccount)
	m.HandleFunc("POST "+options.BaseURL+"/api/orgs/{slug}/aws/accounts/{id}/verify", wrapper.VerifyAwsAccount)
	m.HandleFunc("GET "+options.BaseURL+"/api/orgs/{slug}/github/installations", wrapper.ListGithubInstallations)
	m.HandleFunc("POST "+options.BaseURL+"/api/orgs/{slug}/github/installations/start", wrapper.StartGithubInstall)
	m.HandleFunc("DELETE "+options.BaseURL+"/api/orgs/{slug}/github/installations/{installationId}", wrapper.DeleteGithubInstallation)
	m.HandleFunc("GET "+options.BaseURL+"/api/orgs/{slug}/github/installations/{installationId}/repositories", wrapper.ListGithubInstallationRepositories)
	m.HandleFunc("GET "+options.BaseURL+"/api/ping", wrapper.GetPing)

	return m
}

type ErrorJSONResponse Error

type ApproveCliAuthRequestObject struct {
	Body *ApproveCliAuthJSONRequestBody
}

type ApproveCliAuthResponseObject interface {
	VisitApproveCliAuthResponse(w http.ResponseWriter) error
}

type ApproveCliAuth200JSONResponse CliApproveResponse

func (response ApproveCliAuth200JSONResponse) VisitApproveCliAuthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ApproveCliAuthdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ApproveCliAuthdefaultJSONResponse) VisitApproveCliAuthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type ExchangeCliAuthRequestObject struct {
	Body *ExchangeCliAuthJSONRequestBody
}

type ExchangeCliAuthResponseObject interface {
	VisitExchangeCliAuthResponse(w http.ResponseWriter) error
}

type ExchangeCliAuth200JSONResponse CliExchangeResponse

func (response ExchangeCliAuth200JSONResponse) VisitExchangeCliAuthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ExchangeCliAuthdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ExchangeCliAuthdefaultJSONResponse) VisitExchangeCliAuthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type ListCliTokensRequestObject struct {
}

type ListCliTokensResponseObject interface {
	VisitListCliTokensResponse(w http.ResponseWriter) error
}

type ListCliTokens200JSONResponse CliTokenList

func (response ListCliTokens200JSONResponse) VisitListCliTokensResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListCliTokensdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ListCliTokensdefaultJSONResponse) VisitListCliTokensResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type RevokeCliTokenRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type RevokeCliTokenResponseObject interface {
	VisitRevokeCliTokenResponse(w http.ResponseWriter) error
}

type RevokeCliToken204Response struct {
}

func (response RevokeCliToken204Response) VisitRevokeCliTokenResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RevokeCliTokendefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response RevokeCliTokendefaultJSONResponse) VisitRevokeCliTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type CliWhoamiRequestObject struct {
}

type CliWhoamiResponseObject interface {
	VisitCliWhoamiResponse(w http.ResponseWriter) error
}

type CliWhoami200JSONResponse CliWhoami

func (response CliWhoami200JSONResponse) VisitCliWhoamiResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CliWhoamidefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CliWhoamidefaultJSONResponse) VisitCliWhoamiResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type CompleteGithubInstallRequestObject struct {
	Body *CompleteGithubInstallJSONRequestBody
}

type CompleteGithubInstallResponseObject interface {
	VisitCompleteGithubInstallResponse(w http.ResponseWriter) error
}

type CompleteGithubInstall200JSONResponse GithubInstallCompleteResponse

func (response CompleteGithubInstall200JSONResponse) VisitCompleteGithubInstallResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CompleteGithubInstalldefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CompleteGithubInstalldefaultJSONResponse) VisitCompleteGithubInstallResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListAwsAccountsRequestObject struct {
	Slug OrgSlug `json:"slug"`
}

type ListAwsAccountsResponseObject interface {
	VisitListAwsAccountsResponse(w http.ResponseWriter) error
}

type ListAwsAccounts200JSONResponse CloudAccountList

func (response ListAwsAccounts200JSONResponse) VisitListAwsAccountsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListAwsAccountsdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ListAwsAccountsdefaultJSONResponse) VisitListAwsAccountsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type StartAwsAccountRequestObject struct {
	Slug OrgSlug `json:"slug"`
	Body *StartAwsAccountJSONRequestBody
}

type StartAwsAccountResponseObject interface {
	VisitStartAwsAccountResponse(w http.ResponseWriter) error
}

type StartAwsAccount200JSONResponse CloudAccountStartResponse

func (response StartAwsAccount200JSONResponse) VisitStartAwsAccountResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type StartAwsAccountdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response StartAwsAccountdefaultJSONResponse) VisitStartAwsAccountResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type DeleteAwsAccountRequestObject struct {
	Slug OrgSlug        `json:"slug"`
	Id   CloudAccountID `json:"id"`
}

type DeleteAwsAccountResponseObject interface {
	VisitDeleteAwsAccountResponse(w http.ResponseWriter) error
}

type DeleteAwsAccount204Response struct {
}

func (response DeleteAwsAccount204Response) VisitDeleteAwsAccountResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteAwsAccountdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response DeleteAwsAccountdefaultJSONResponse) VisitDeleteAwsAccountResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetAwsAccountRequestObject struct {
	Slug OrgSlug        `json:"slug"`
	Id   CloudAccountID `json:"id"`
}

type GetAwsAccountResponseObject interface {
	VisitGetAwsAccountResponse(w http.ResponseWriter) error
}

type GetAwsAccount200JSONResponse CloudAccount

func (response GetAwsAccount200JSONResponse) VisitGetAwsAccountResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAwsAccountdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetAwsAccountdefaultJSONResponse) VisitGetAwsAccountResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type CompleteAwsAccountRequestObject struct {
	Slug OrgSlug        `json:"slug"`
	Id   CloudAccountID `json:"id"`
	Body *CompleteAwsAccountJSONRequestBody
}

type CompleteAwsAccountResponseObject interface {
	VisitCompleteAwsAccountResponse(w http.ResponseWriter) error
}

type CompleteAwsAccount200JSONResponse CloudAccount

func (response CompleteAwsAccount200JSONResponse) VisitCompleteAwsAccountResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CompleteAwsAccountdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CompleteAwsAccountdefaultJSONResponse) VisitCompleteAwsAccountResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type VerifyAwsAccountRequestObject struct {
	Slug OrgSlug        `json:"slug"`
	Id   CloudAccountID `json:"id"`
}

type VerifyAwsAccountResponseObject interface {
	VisitVerifyAwsAccountResponse(w http.ResponseWriter) error
}

type VerifyAwsAccount200JSONResponse CloudAccount

func (response VerifyAwsAccount200JSONResponse) VisitVerifyAwsAccountResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type VerifyAwsAccountdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response VerifyAwsAccountdefaultJSONResponse) VisitVerifyAwsAccountResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type ListGithubInstallationsRequestObject struct {
	Slug OrgSlug `json:"slug"`
}

type ListGithubInstallationsResponseObject interface {
	VisitListGithubInstallationsResponse(w http.ResponseWriter) error
}

type ListGithubInstallations200JSONResponse GithubInstallationList

func (response ListGithubInstallations200JSONResponse) VisitListGithubInstallationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListGithubInstallationsdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ListGithubInstallationsdefaultJSONResponse) VisitListGithubInstallationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type StartGithubInstallRequestObject struct {
	Slug OrgSlug `json:"slug"`
}

type StartGithubInstallResponseObject interface {
	VisitStartGithubInstallResponse(w http.ResponseWriter) error
}

type StartGithubInstall200JSONResponse GithubInstallStart

func (response StartGithubInstall200JSONResponse) VisitStartGithubInstallResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type StartGithubInstalldefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response StartGithubInstalldefaultJSONResponse) VisitStartGithubInstallResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type DeleteGithubInstallationRequestObject struct {
	Slug           OrgSlug        `json:"slug"`
	InstallationId InstallationID `json:"installationId"`
}

type DeleteGithubInstallationResponseObject interface {
	VisitDeleteGithubInstallationResponse(w http.ResponseWriter) error
}

type DeleteGithubInstallation204Response struct {
}

func (response DeleteGithubInstallation204Response) VisitDeleteGithubInstallationResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteGithubInstallationdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response DeleteGithubInstallationdefaultJSONResponse) VisitDeleteGithubInstallationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type ListGithubInstallationRepositoriesRequestObject struct {
	Slug           OrgSlug        `json:"slug"`
	InstallationId InstallationID `json:"installationId"`
}

type ListGithubInstallationRepositoriesResponseObject interface {
	VisitListGithubInstallationRepositoriesResponse(w http.ResponseWriter) error
}

type ListGithubInstallationRepositories200JSONResponse GithubRepositoryList

func (response ListGithubInstallationRepositories200JSONResponse) VisitListGithubInstallationRepositoriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListGithubInstallationRepositoriesdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ListGithubInstallationRepositoriesdefaultJSONResponse) VisitListGithubInstallationRepositoriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetPingRequestObject struct {
	Params GetPingParams
}

type GetPingResponseObject interface {
	VisitGetPingResponse(w http.ResponseWriter) error
}

type GetPing200JSONResponse Greeting

func (response GetPing200JSONResponse) VisitGetPingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetPingdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetPingdefaultJSONResponse) VisitGetPingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Approve a pending CLI login (browser-initiated)
	// (POST /api/cli/auth/approve)
	ApproveCliAuth(ctx context.Context, request ApproveCliAuthRequestObject) (ApproveCliAuthResponseObject, error)
	// Exchange an approval code for a CLI token (public)
	// (POST /api/cli/auth/exchange)
	ExchangeCliAuth(ctx context.Context, request ExchangeCliAuthRequestObject) (ExchangeCliAuthResponseObject, error)
	// List the caller's CLI tokens
	// (GET /api/cli/tokens)
	ListCliTokens(ctx context.Context, request ListCliTokensRequestObject) (ListCliTokensResponseObject, error)
	// Revoke a CLI token
	// (DELETE /api/cli/tokens/{id})
	RevokeCliToken(ctx context.Context, request RevokeCliTokenRequestObject) (RevokeCliTokenResponseObject, error)
	// Return the user associated with the CLI token
	// (GET /api/cli/whoami)
	CliWhoami(ctx context.Context, request CliWhoamiRequestObject) (CliWhoamiResponseObject, error)
	// Finalize a GitHub App install handshake (Clerk session only)
	// (POST /api/github/installations/complete)
	CompleteGithubInstall(ctx context.Context, request CompleteGithubInstallRequestObject) (CompleteGithubInstallResponseObject, error)
	// Liveness probe
	// (GET /api/health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// List AWS cloud accounts connected to this org
	// (GET /api/orgs/{slug}/aws/accounts)
	ListAwsAccounts(ctx context.Context, request ListAwsAccountsRequestObject) (ListAwsAccountsResponseObject, error)
	// Begin AWS cloud-account onboarding
	// (POST /api/orgs/{slug}/aws/accounts)
	StartAwsAccount(ctx context.Context, request StartAwsAccountRequestObject) (StartAwsAccountResponseObject, error)
	// Disconnect an AWS cloud account
	// (DELETE /api/orgs/{slug}/aws/accounts/{id})
	DeleteAwsAccount(ctx context.Context, request DeleteAwsAccountRequestObject) (DeleteAwsAccountResponseObject, error)
	// Get a single AWS cloud account
	// (GET /api/orgs/{slug}/aws/accounts/{id})
	GetAwsAccount(ctx context.Context, request GetAwsAccountRequestObject) (GetAwsAccountResponseObject, error)
	// Finalize AWS onboarding by submitting the role ARN
	// (POST /api/orgs/{slug}/aws/accounts/{id}/complete)
	CompleteAwsAccount(ctx context.Context, request CompleteAwsAccountRequestObject) (CompleteAwsAccountResponseObject, error)
	// Re-run the verification probe against a cloud account
	// (POST /api/orgs/{slug}/aws/accounts/{id}/verify)
	VerifyAwsAccount(ctx context.Context, request VerifyAwsAccountRequestObject) (VerifyAwsAccountResponseObject, error)
	// List GitHub App installations connected to this org
	// (GET /api/orgs/{slug}/github/installations)
	ListGithubInstallations(ctx context.Context, request ListGithubInstallationsRequestObject) (ListGithubInstallationsResponseObject, error)
	// Begin a GitHub App install handshake
	// (POST /api/orgs/{slug}/github/installations/start)
	StartGithubInstall(ctx context.Context, request StartGithubInstallRequestObject) (StartGithubInstallResponseObject, error)
	// Disconnect a GitHub App installation from this org
	// (DELETE /api/orgs/{slug}/github/installations/{installationId})
	DeleteGithubInstallation(ctx context.Context, request DeleteGithubInstallationRequestObject) (DeleteGithubInstallationResponseObject, error)
	// List repositories accessible to a GitHub App installation
	// (GET /api/orgs/{slug}/github/installations/{installationId}/repositories)
	ListGithubInstallationRepositories(ctx context.Context, request ListGithubInstallationRepositoriesRequestObject) (ListGithubInstallationRepositoriesResponseObject, error)
	// Echo a greeting
	// (GET /api/ping)
	GetPing(ctx context.Context, request GetPingRequestObject) (GetPingResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ApproveCliAuth operation middleware
func (sh *strictHandler) ApproveCliAuth(w http.ResponseWriter, r *http.Request) {
	var request ApproveCliAuthRequestObject

	var body ApproveCliAuthJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ApproveCliAuth(ctx, request.(ApproveCliAuthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ApproveCliAuth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ApproveCliAuthResponseObject); ok {
		if err := validResponse.VisitApproveCliAuthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ExchangeCliAuth operation middleware
func (sh *strictHandler) ExchangeCliAuth(w http.ResponseWriter, r *http.Request) {
	var request ExchangeCliAuthRequestObject

	var body ExchangeCliAuthJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ExchangeCliAuth(ctx, request.(ExchangeCliAuthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ExchangeCliAuth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ExchangeCliAuthResponseObject); ok {
		if err := validResponse.VisitExchangeCliAuthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListCliTokens operation middleware
func (sh *strictHandler) ListCliTokens(w http.ResponseWriter, r *http.Request) {
	var request ListCliTokensRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListCliTokens(ctx, request.(ListCliTokensRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListCliTokens")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListCliTokensResponseObject); ok {
		if err := validResponse.VisitListCliTokensResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RevokeCliToken operation middleware
func (sh *strictHandler) RevokeCliToken(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request RevokeCliTokenRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RevokeCliToken(ctx, request.(RevokeCliTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RevokeCliToken")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RevokeCliTokenResponseObject); ok {
		if err := validResponse.VisitRevokeCliTokenResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CliWhoami operation middleware
func (sh *strictHandler) CliWhoami(w http.ResponseWriter, r *http.Request) {
	var request CliWhoamiRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CliWhoami(ctx, request.(CliWhoamiRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CliWhoami")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CliWhoamiResponseObject); ok {
		if err := validResponse.VisitCliWhoamiResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CompleteGithubInstall operation middleware
func (sh *strictHandler) CompleteGithubInstall(w http.ResponseWriter, r *http.Request) {
	var request CompleteGithubInstallRequestObject

	var body CompleteGithubInstallJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CompleteGithubInstall(ctx, request.(CompleteGithubInstallRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CompleteGithubInstall")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CompleteGithubInstallResponseObject); ok {
		if err := validResponse.VisitCompleteGithubInstallResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListAwsAccounts operation middleware
func (sh *strictHandler) ListAwsAccounts(w http.ResponseWriter, r *http.Request, slug OrgSlug) {
	var request ListAwsAccountsRequestObject

	request.Slug = slug

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListAwsAccounts(ctx, request.(ListAwsAccountsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAwsAccounts")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAwsAccountsResponseObject); ok {
		if err := validResponse.VisitListAwsAccountsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StartAwsAccount operation middleware
func (sh *strictHandler) StartAwsAccount(w http.ResponseWriter, r *http.Request, slug OrgSlug) {
	var request StartAwsAccountRequestObject

	request.Slug = slug

	var body StartAwsAccountJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.StartAwsAccount(ctx, request.(StartAwsAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StartAwsAccount")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(StartAwsAccountResponseObject); ok {
		if err := validResponse.VisitStartAwsAccountResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteAwsAccount operation middleware
func (sh *strictHandler) DeleteAwsAccount(w http.ResponseWriter, r *http.Request, slug OrgSlug, id CloudAccountID) {
	var request DeleteAwsAccountRequestObject

	request.Slug = slug
	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteAwsAccount(ctx, request.(DeleteAwsAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteAwsAccount")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteAwsAccountResponseObject); ok {
		if err := validResponse.VisitDeleteAwsAccountResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAwsAccount operation middleware
func (sh *strictHandler) GetAwsAccount(w http.ResponseWriter, r *http.Request, slug OrgSlug, id CloudAccountID) {
	var request GetAwsAccountRequestObject

	request.Slug = slug
	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAwsAccount(ctx, request.(GetAwsAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAwsAccount")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAwsAccountResponseObject); ok {
		if err := validResponse.VisitGetAwsAccountResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CompleteAwsAccount operation middleware
func (sh *strictHandler) CompleteAwsAccount(w http.ResponseWriter, r *http.Request, slug OrgSlug, id CloudAccountID) {
	var request CompleteAwsAccountRequestObject

	request.Slug = slug
	request.Id = id

	var body CompleteAwsAccountJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CompleteAwsAccount(ctx, request.(CompleteAwsAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CompleteAwsAccount")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CompleteAwsAccountResponseObject); ok {
		if err := validResponse.VisitCompleteAwsAccountResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// VerifyAwsAccount operation middleware
func (sh *strictHandler) VerifyAwsAccount(w http.ResponseWriter, r *http.Request, slug OrgSlug, id CloudAccountID) {
	var request VerifyAwsAccountRequestObject

	request.Slug = slug
	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.VerifyAwsAccount(ctx, request.(VerifyAwsAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "VerifyAwsAccount")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(VerifyAwsAccountResponseObject); ok {
		if err := validResponse.VisitVerifyAwsAccountResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListGithubInstallations operation middleware
func (sh *strictHandler) ListGithubInstallations(w http.ResponseWriter, r *http.Request, slug OrgSlug) {
	var request ListGithubInstallationsRequestObject

	request.Slug = slug

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListGithubInstallations(ctx, request.(ListGithubInstallationsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListGithubInstallations")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListGithubInstallationsResponseObject); ok {
		if err := validResponse.VisitListGithubInstallationsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StartGithubInstall operation middleware
func (sh *strictHandler) StartGithubInstall(w http.ResponseWriter, r *http.Request, slug OrgSlug) {
	var request StartGithubInstallRequestObject

	request.Slug = slug

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.StartGithubInstall(ctx, request.(StartGithubInstallRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StartGithubInstall")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(StartGithubInstallResponseObject); ok {
		if err := validResponse.VisitStartGithubInstallResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteGithubInstallation operation middleware
func (sh *strictHandler) DeleteGithubInstallation(w http.ResponseWriter, r *http.Request, slug OrgSlug, installationId InstallationID) {
	var request DeleteGithubInstallationRequestObject

	request.Slug = slug
	request.InstallationId = installationId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteGithubInstallation(ctx, request.(DeleteGithubInstallationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteGithubInstallation")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteGithubInstallationResponseObject); ok {
		if err := validResponse.VisitDeleteGithubInstallationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListGithubInstallationRepositories operation middleware
func (sh *strictHandler) ListGithubInstallationRepositories(w http.ResponseWriter, r *http.Request, slug OrgSlug, installationId InstallationID) {
	var request ListGithubInstallationRepositoriesRequestObject

	request.Slug = slug
	request.InstallationId = installationId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListGithubInstallationRepositories(ctx, request.(ListGithubInstallationRepositoriesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListGithubInstallationRepositories")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListGithubInstallationRepositoriesResponseObject); ok {
		if err := validResponse.VisitListGithubInstallationRepositoriesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPing operation middleware
func (sh *strictHandler) GetPing(w http.ResponseWriter, r *http.Request, params GetPingParams) {
	var request GetPingRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPing(ctx, request.(GetPingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPing")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPingResponseObject); ok {
		if err := validResponse.VisitGetPingResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+Rb23IbN5N+la7ZrZJUy4P//EkulCtGPkS1TuyV7OQiTMngTJODCATGAEY042grD5En",
	"zJNsNTCYA4kRKYtKXLV3kmYG3ej++tz6mKRqWSiJ0prk9GNSMM2WaFG7386EKrNJmqpS2vOn9Bcuk9Ok",
	"YDZPBolkS0xOE54lg0Tj+5JrzJJTq0scJCbNccnoi7nSS2aT06Qs3Zt2XdBXxmouF8nt7SA5l8YyIZjl",
	"SvZTab+0J0Uu7ddfNiS5tLhA7Wi+0otLUS56iBl6dBeJzUvc0sumUNKgE9wzrZWmH1IlLUpLP7KiEDx1",
	"Fxj/apSkvzUn/qfGeXKa/Me40cfYPzVjf5qjkqFJNS/okOTUk4FA2V2s+sZrj0+KQqsbvMD3JRrHRaFV",
	"gdpyz2eaMyFQLpB+6Z79LTP49ZelFscmZ1989fXxDWo+56hPTuCvP/4EmyOcvTw/MvD6v8+eQX3SaFvH",
	"Qa6bJN4a1MM0VwYlCDZDAXOl3cFWXaOEYxwtRpArY+n7k1EUPY2SfvZkBq1b/VJ/oWa/YmqJl7ZYKsFt",
	"y0VlEX4vuVwIHJYGAT+kOZMLBHpzADdM8Mxx/79fwZLL0qLZza6j0sPis4pAv+oqFrdkHfQUw2mEfuuD",
	"naz0iQs/FFyjuWK2Y38Zszi03OmkFxJbD5zut4X/JkeYIdOoPTpGcIG21BIzwA8stWINSqbosCmVBY2p",
	"ukHNZgJBMIt6tz485UGAUetWPZJ5E1jdUI1GZjG7lzg+RYQ828PBDhLBjL0qzd0MyVIIklXwdfvrS+ON",
	"un7Q4RtqcLcIptyIcm+FvOQxe3HKdT9xi0uzy+fW2r2tKTGt2ToOGtPH0E+5Yku+zY1RpU6dPFGWS2eM",
	"AvU13Vjw1mGNmEuD+spr/G7xhRcHgUictSayb3PH/IOKXNcO//XFMOMLbmHy0yVUL8L5UzjGZWHXUErL",
	"BSg5U0xnXC6AZCvQonH+eyfMPsV29raDGYoohJ2FeDfoA/QVhgC+k+HWtw+0MIpJPPOOuytzpy0Iz52L",
	"U1KsYZqwlZkmYFXG1tHAq3HBfaqxk7xWAq+Y3u9lY5ktzTanBUqn9d8hVVJiajGD38FJE36HjBs6NYuy",
	"WhbZPTUf8xu1EIO+a143nEmL3C4DOasg3BuL26LryuO5VkuX0RjL0usjA69KW5TWjC6UwImWu4NSffYu",
	"LuNur7LQ+zi+lmfY5fzq03cxd2mZtr3yqy2zK7zvyiWTw7nmKDOxBgoJIPg1Eu7TJQ4LrbJpMoK3kr8v",
	"EQrUoPRihx10SbxyPzABGc5ZKShtoBfrRPR/Sp5ew5kDDggur3crzF9mT4H0ZVSscc33URZ+sKglE1HP",
	"Hc2XRvCGLgfMAAODqUY7gmfLGWYZZsAlSWEqHZ3nziRJOlaXxkKhBE/XwCS5JjQoydiVBLxBvYaJMeUS",
	"CeajqYyppBDMkpVf3RVtKOvbCDSXBUtxLhAtcAO6lJIcDpfOLa5yZj3LaWmsWqI+MnA++b7L8ooLAUwI",
	"tWqxCXOtlj28vicYXHn/cVVq0eOiGwl1cPP24iWsuM0dosK1W1eaSpJh0B3dsdA4nHNBrhIuUWbuy3Aj",
	"yFFXQm1inuY7gRkw1YVJ5HJx3cQQXde5e9YmSzSGLXDv0iS8H6P9gtu8nFXNg50uut0/uNpIGPr6BD50",
	"7MGtf22wReQebPc5gvaRu7xB52j/xe0gUXpxZapex7ZxKb1w4GrTgRUzMFMl4U6N4K1B4BasAo0Z15ja",
	"3U6ww3aLh50ScX5xWwxRm6stg1JeZxXEZEXaPZgUxQguSTvkK3DTrb29ePmNNy0mBGrIFBpXPEpEujtY",
	"zdJr4PYTrI043nnbWq135d974DR8INSCy6jlhTf8g01JTl0vZpqA0jBNXukFk/w3x9w0geMlJzM38ILb",
	"78rZSTTAPmLe/ommWxpKRh+Ykx8mKd28wabCNtQzaAPgfmnrNrriaWGbo/1zw7iDuTND7BLqZ/kCC2W4",
	"VXq9zWyVm13NNJNpHoX3vBTiqrdFkdulCGH7biPeAmU/wHqpFZrfdMPGTCmBTN7Z6Whu0Jww2Lx66yr7",
	"iDKuex2eByzsr/qWlnYpvkMlyqxGtCSyLQb3zhLuSg++QyZsHum81JVr6Lyo60jDJRLhy9g9bp2DmqtI",
	"9fLmzWuYvD6va4lW4sooLl3gAiVqCk6pkpSGagOrHCUl0GBzbmDOBYLvvpoqNeWW3FXSOmzy+tx3cY0n",
	"/GT0r9ETF/kLlKzgyWny79GT0b8JWMzm7u5jVvBxKviYlTYfM98Pd8JSHjIb2S3Fxwxma3eRmVYrirhs",
	"btFfzfCFxGzIpQ/FqZJzrpcmDAmm0lNgAkyq0TdvU6UzKjq64wNXTjDIO6XfVPqBAJnHALSrYyjpZ2B6",
	"WvJgq0IgMDuVIXkxMKOgTtG9HmEIlTKRK2NdJkDPvbQJOGHkdJpUY4MzwSelGxdpn21+q7L1wYY921Ob",
	"2y4YKVJtzpu+ePLkURioB0tbo6dJUKh2isQsua29VR+FmuV6okVherlk5PSDdIFBaCKdvTwHFyDhuNLi",
	"kEtuOQXAE/d1F8YBATtxbFDfoB5aNfQ/BWCfvTynephlSMBU0sd4D6hClMZnjQ6wYWjirJuBUHIxFPyG",
	"jKQzpHhDZowyKxSXrmAtypng6VTOMGUE24ou5IxSTzBoyIxhjdb5Asq8CZOmzkK7mAzDmUcH5eZA6u9H",
	"5dYcKgJL17MHbkx5AEQGgsAk1A7MgcErndRWTSq9VjdA2YwcFuhY6KqOonMYM5jkcWXXDEZ6hbZEyzJm",
	"GRxLBYVglOp8sCcPliJRbRVZR6aRm4nJa/yRZ7fedKk03pbbhRs41QOaQWdp4efH2FH4ZUs5X8baa24O",
	"Bsc8w2WhSG0PF54/tI21rshW9XypgthGhbxU1zi0aGzjg0I6Qif+9cefTbBmFZi5qebZTGYUNgulLSUm",
	"yiDwDKXldu3dkqbkbgRnAvX1kFwwPUzJPVc+iwmjpnKl9LWrs9dg+LIQa8A0r8IvfRqc3pHx6QPPYp6u",
	"maY9rqlURCJ2ch4uT+wfQLWUxjT9C2aMSl1sa5qFEa0vXCI+7tRV4zBk2zeDu3w9AYO2LIYh34GCLbAh",
	"/M61tN55CLzbqF/fVSkYZq5nWvUFRvCjj4kmDDwsDmCONs3RTOVWk6n1KdxwBpOiGAq8QQGEpIHvK1NS",
	"aywFv6k0qSqqtkzduGKWCGkSGv0xZzIzObvGEfygLL0zLDTO+QfMuhGXvuYmLAmEi9R8A7cGxTwKw0rU",
	"nVr4kcLunS3OvzkA3923jFlLW9mVIg8QlJ9zyQT/jXxiBZ5JUdRNvxoAcNxxLW5e2grPeV0dRkPzC7RV",
	"/fiIEq0oRER3ifqGp65n6Rldb8XUG5RoDBRazbC5ltILM/5oRLm4HbOVGbenf705yGRlJuG9rWAau0Dz",
	"yjjs0UVC5CGd8saUMyIyPyIP94VjiSuKenOuzaFymMlPl5B2yTRDbueVuCHH4npAUSf8PaePmGzPegaN",
	"k2sqH0fmqiaj1WoQojE53qqw3jFy6syMTK5KkU2lKlASs4KVMs2r1r/FhccEaCWQihbsjKO4oe9Xciq3",
	"Vq2MVdqNB1LBUdqh4RlWSyBVUKJj+bw7lPN26qg7ThUlHznXGRRM23XM77rBQAPVByL1MUqknmn3314o",
	"9Q2ZI1bzuo23eiL5X+39nbcXLx9sPt8iFfG1/QwDoYbMbhcWKQu6d3mqVWFaTbYjU/UmPJ43rMXtY9SD",
	"oNawOPDGDQicW3qlEKxCu8th1UqCRaYztZIxpD51DB4CqoOdr25saO9XqTzlpnFcBy1XmpPJy205TDq/",
	"L95+LvJ6HEvcGbIeLPoXaOt+aEzye9nXPoVEcOHHSlNR6JrVPppUSbgzrZOwrua9PMUVmFz8MJXzXRtR",
	"zlqrvpwupYuXl28ufaozlWzBKNmD47AYNYDWOsOJKxvmghcGfM+egkuDdiWn0pRpSrmT0tViGhUjjIsy",
	"bFXEE/5/EKCPG63+4cJil5m82t4lzeC4va0JmsmTwxUWZDytADhbgylnS24t/dYG875G5Xhdt02qizBX",
	"N6///znAHzd0CMeVyWqK4KmtXAeaUhyklTbUpe+3dMDj/AoEt8L28ZuxHsydJdb24PwzLbV69gd2lPfm",
	"MAXWdj3vT+8rs/ZVzdjUS0XRkHZuTNmd+JxdXjyvOkEUT9pVV6iswhA0FFams4xk1QgmbjxacTIIt4uP",
	"ISdFcWSm0vViF6V2MypbFs3q4HYPjhir2nTfhKbeVM655Cavom7TDbnhDN7t7h++6628Nttdnzt2/R5Z",
	"P26dZDWybH2g6ubudtQ9wPqx+6+On1bzgJpvrfWN4GnYbytl9cD3ZVucKwmeq1GqllXNw+jcAO0jA2mu",
	"eIr9pU9kTegRI9rGv49+TiVQn0cL3eZ7O7JNbIw3d3miU6Cq7QRzjSbvMsJ8KuwHP24LWZZLt5MSgm+h",
	"quY9XSJnBmaIEhaaVeve1Yibm3r3GmYlFxkUvEDBJbpt66lMhZLtHet9guRF+3b/KIQO7aU2drQifqpz",
	"94OE1zZWKsXzmUDffetBaoPNolrV6qvfX9Pz+Cz2fYl63QxjqyW3/v+mflTxh62ziMibZw9dHEhzkumi",
	"Q8uXtF4sbhcxGSe3v9z+XwAAAP//Ba+72II/AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
