//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CliWhoamiSource.
const (
	Clerk CliWhoamiSource = "clerk"
	Cli   CliWhoamiSource = "cli"
)

// Valid indicates whether the value is a known member of the CliWhoamiSource enum.
func (e CliWhoamiSource) Valid() bool {
	switch e {
	case Clerk:
		return true
	case Cli:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// CliApproveRequest defines model for CliApproveRequest.
type CliApproveRequest struct {
	// Challenge Base64url(sha256(verifier)) — the CLI's PKCE challenge.
	Challenge string `json:"challenge"`

	// Name User-chosen label for the token (e.g. hostname).
	Name string `json:"name"`
}

// CliApproveResponse defines model for CliApproveResponse.
type CliApproveResponse struct {
	// Code Single-use exchange code, valid for ~5 minutes.
	Code string `json:"code"`
}

// CliExchangeRequest defines model for CliExchangeRequest.
type CliExchangeRequest struct {
	Code     string `json:"code"`
	Verifier string `json:"verifier"`
}

// CliExchangeResponse defines model for CliExchangeResponse.
type CliExchangeResponse struct {
	ExpiresAt time.Time `json:"expires_at"`
	Name      string    `json:"name"`

	// Token The bearer token. Returned exactly once — not recoverable later.
	Token string `json:"token"`
}

// CliToken defines model for CliToken.
type CliToken struct {
	CreatedAt  time.Time          `json:"created_at"`
	ExpiresAt  time.Time          `json:"expires_at"`
	Id         openapi_types.UUID `json:"id"`
	LastUsedAt *time.Time         `json:"last_used_at,omitempty"`
	Name       string             `json:"name"`
	RevokedAt  *time.Time         `json:"revoked_at,omitempty"`
}

// CliTokenList defines model for CliTokenList.
type CliTokenList struct {
	Tokens []CliToken `json:"tokens"`
}

// CliWhoami defines model for CliWhoami.
type CliWhoami struct {
	Source CliWhoamiSource `json:"source"`
	UserId string          `json:"user_id"`
}

// CliWhoamiSource defines model for CliWhoami.Source.
type CliWhoamiSource string

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// Greeting defines model for Greeting.
type Greeting struct {
	Message string `json:"message"`
}

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// GetPingParams defines parameters for GetPing.
type GetPingParams struct {
	Name *string `form:"name,omitempty" json:"name,omitempty"`
}

// ApproveCliAuthJSONRequestBody defines body for ApproveCliAuth for application/json ContentType.
type ApproveCliAuthJSONRequestBody = CliApproveRequest

// ExchangeCliAuthJSONRequestBody defines body for ExchangeCliAuth for application/json ContentType.
type ExchangeCliAuthJSONRequestBody = CliExchangeRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Approve a pending CLI login (browser-initiated)
	// (POST /api/cli/auth/approve)
	ApproveCliAuth(w http.ResponseWriter, r *http.Request)
	// Exchange an approval code for a CLI token (public)
	// (POST /api/cli/auth/exchange)
	ExchangeCliAuth(w http.ResponseWriter, r *http.Request)
	// List the caller's CLI tokens
	// (GET /api/cli/tokens)
	ListCliTokens(w http.ResponseWriter, r *http.Request)
	// Revoke a CLI token
	// (DELETE /api/cli/tokens/{id})
	RevokeCliToken(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Return the user associated with the CLI token
	// (GET /api/cli/whoami)
	CliWhoami(w http.ResponseWriter, r *http.Request)
	// Liveness probe
	// (GET /api/health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Echo a greeting
	// (GET /api/ping)
	GetPing(w http.ResponseWriter, r *http.Request, params GetPingParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ApproveCliAuth operation middleware
func (siw *ServerInterfaceWrapper) ApproveCliAuth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ApproveCliAuth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExchangeCliAuth operation middleware
func (siw *ServerInterfaceWrapper) ExchangeCliAuth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExchangeCliAuth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCliTokens operation middleware
func (siw *ServerInterfaceWrapper) ListCliTokens(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCliTokens(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeCliToken operation middleware
func (siw *ServerInterfaceWrapper) RevokeCliToken(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeCliToken(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CliWhoami operation middleware
func (siw *ServerInterfaceWrapper) CliWhoami(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CliWhoami(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPing operation middleware
func (siw *ServerInterfaceWrapper) GetPing(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPingParams

	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "name", r.URL.Query(), &params.Name, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPing(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/api/cli/auth/approve", wrapper.ApproveCliAuth)
	m.HandleFunc("POST "+options.BaseURL+"/api/cli/auth/exchange", wrapper.ExchangeCliAuth)
	m.HandleFunc("GET "+options.BaseURL+"/api/cli/tokens", wrapper.ListCliTokens)
	m.HandleFunc("DELETE "+options.BaseURL+"/api/cli/tokens/{id}", wrapper.RevokeCliToken)
	m.HandleFunc("GET "+options.BaseURL+"/api/cli/whoami", wrapper.CliWhoami)
	m.HandleFunc("GET "+options.BaseURL+"/api/health", wrapper.GetHealth)
	m.HandleFunc("GET "+options.BaseURL+"/api/ping", wrapper.GetPing)

	return m
}

type ErrorJSONResponse Error

type ApproveCliAuthRequestObject struct {
	Body *ApproveCliAuthJSONRequestBody
}

type ApproveCliAuthResponseObject interface {
	VisitApproveCliAuthResponse(w http.ResponseWriter) error
}

type ApproveCliAuth200JSONResponse CliApproveResponse

func (response ApproveCliAuth200JSONResponse) VisitApproveCliAuthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ApproveCliAuthdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ApproveCliAuthdefaultJSONResponse) VisitApproveCliAuthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type ExchangeCliAuthRequestObject struct {
	Body *ExchangeCliAuthJSONRequestBody
}

type ExchangeCliAuthResponseObject interface {
	VisitExchangeCliAuthResponse(w http.ResponseWriter) error
}

type ExchangeCliAuth200JSONResponse CliExchangeResponse

func (response ExchangeCliAuth200JSONResponse) VisitExchangeCliAuthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ExchangeCliAuthdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ExchangeCliAuthdefaultJSONResponse) VisitExchangeCliAuthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type ListCliTokensRequestObject struct {
}

type ListCliTokensResponseObject interface {
	VisitListCliTokensResponse(w http.ResponseWriter) error
}

type ListCliTokens200JSONResponse CliTokenList

func (response ListCliTokens200JSONResponse) VisitListCliTokensResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListCliTokensdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ListCliTokensdefaultJSONResponse) VisitListCliTokensResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type RevokeCliTokenRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type RevokeCliTokenResponseObject interface {
	VisitRevokeCliTokenResponse(w http.ResponseWriter) error
}

type RevokeCliToken204Response struct {
}

func (response RevokeCliToken204Response) VisitRevokeCliTokenResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RevokeCliTokendefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response RevokeCliTokendefaultJSONResponse) VisitRevokeCliTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type CliWhoamiRequestObject struct {
}

type CliWhoamiResponseObject interface {
	VisitCliWhoamiResponse(w http.ResponseWriter) error
}

type CliWhoami200JSONResponse CliWhoami

func (response CliWhoami200JSONResponse) VisitCliWhoamiResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CliWhoamidefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CliWhoamidefaultJSONResponse) VisitCliWhoamiResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetPingRequestObject struct {
	Params GetPingParams
}

type GetPingResponseObject interface {
	VisitGetPingResponse(w http.ResponseWriter) error
}

type GetPing200JSONResponse Greeting

func (response GetPing200JSONResponse) VisitGetPingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetPingdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetPingdefaultJSONResponse) VisitGetPingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Approve a pending CLI login (browser-initiated)
	// (POST /api/cli/auth/approve)
	ApproveCliAuth(ctx context.Context, request ApproveCliAuthRequestObject) (ApproveCliAuthResponseObject, error)
	// Exchange an approval code for a CLI token (public)
	// (POST /api/cli/auth/exchange)
	ExchangeCliAuth(ctx context.Context, request ExchangeCliAuthRequestObject) (ExchangeCliAuthResponseObject, error)
	// List the caller's CLI tokens
	// (GET /api/cli/tokens)
	ListCliTokens(ctx context.Context, request ListCliTokensRequestObject) (ListCliTokensResponseObject, error)
	// Revoke a CLI token
	// (DELETE /api/cli/tokens/{id})
	RevokeCliToken(ctx context.Context, request RevokeCliTokenRequestObject) (RevokeCliTokenResponseObject, error)
	// Return the user associated with the CLI token
	// (GET /api/cli/whoami)
	CliWhoami(ctx context.Context, request CliWhoamiRequestObject) (CliWhoamiResponseObject, error)
	// Liveness probe
	// (GET /api/health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// Echo a greeting
	// (GET /api/ping)
	GetPing(ctx context.Context, request GetPingRequestObject) (GetPingResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ApproveCliAuth operation middleware
func (sh *strictHandler) ApproveCliAuth(w http.ResponseWriter, r *http.Request) {
	var request ApproveCliAuthRequestObject

	var body ApproveCliAuthJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ApproveCliAuth(ctx, request.(ApproveCliAuthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ApproveCliAuth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ApproveCliAuthResponseObject); ok {
		if err := validResponse.VisitApproveCliAuthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ExchangeCliAuth operation middleware
func (sh *strictHandler) ExchangeCliAuth(w http.ResponseWriter, r *http.Request) {
	var request ExchangeCliAuthRequestObject

	var body ExchangeCliAuthJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ExchangeCliAuth(ctx, request.(ExchangeCliAuthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ExchangeCliAuth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ExchangeCliAuthResponseObject); ok {
		if err := validResponse.VisitExchangeCliAuthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListCliTokens operation middleware
func (sh *strictHandler) ListCliTokens(w http.ResponseWriter, r *http.Request) {
	var request ListCliTokensRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListCliTokens(ctx, request.(ListCliTokensRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListCliTokens")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListCliTokensResponseObject); ok {
		if err := validResponse.VisitListCliTokensResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RevokeCliToken operation middleware
func (sh *strictHandler) RevokeCliToken(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request RevokeCliTokenRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RevokeCliToken(ctx, request.(RevokeCliTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RevokeCliToken")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RevokeCliTokenResponseObject); ok {
		if err := validResponse.VisitRevokeCliTokenResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CliWhoami operation middleware
func (sh *strictHandler) CliWhoami(w http.ResponseWriter, r *http.Request) {
	var request CliWhoamiRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CliWhoami(ctx, request.(CliWhoamiRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CliWhoami")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CliWhoamiResponseObject); ok {
		if err := validResponse.VisitCliWhoamiResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPing operation middleware
func (sh *strictHandler) GetPing(w http.ResponseWriter, r *http.Request, params GetPingParams) {
	var request GetPingRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPing(ctx, request.(GetPingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPing")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPingResponseObject); ok {
		if err := validResponse.VisitGetPingResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xX227bzBF+lcG2QGxAB/fP4UK9cowgMeoLI3HRizgIVuRI3Hi5y8wsZQuGij5En7BP",
	"UswuSZ2o2Knt3lHi7hy++Wbm473KfFl5hy6wmtwrQq68Y4w/PhB5kofMu4AuyKOuKmsyHYx34x/snfzH",
	"WYGllqc/E87URP1pvLY6Tm95nKytVquBypEzMpUYUZPkBlrPSg40d8TkmTWnVUV+gZ/xZ40co6jIV0jB",
	"pDizQluLbo7yY9v2e8347k1N9ogL/cfbd0cLJDMzSMfH8J9//RtCgXB2cf6K4fJvZx+gszRSAxWWFaqJ",
	"4kDGzdVqoJwue1z8nZGGWeEZHVg9RQszT9Fw8Dfo4AhH8xEUnoPcP+6xvBoowp+1IczV5GtyM9jI6lt3",
	"w09/YBYklk1YGuD2cfF5T7xfjJtbHNaMgHdZod0cQU4OYKGtyWP0/3wLpXF1QH443OjlQIgfGgeHS9eE",
	"uId1W6eel33+Ny48GMohuPCuMoT8Xcc4Z55KeVK5DjgMJtbkICX2XsTa74N/VSBMURNSYscIPmOoyWEO",
	"eKezYJfgXYaRm84HIMz8AklPLYLVAenheiTPg5ZGG1kdQOaqDXWnNIQ6YP5bcPwvEJp862xdm7zvmNUc",
	"vtf864Bcba1gpSaBavydehEu/M2TjO+UIWbRtvIaykcX5ML09UssbnwyAUt+aOZ21V11njSRXvaThg8F",
	"9I/C69LsR8O+piziia4uYzNapBvJ2JoNY2uYa0b6nir+a/jag4PWSV9o3YJ65FApkVnP8dEzpT3f5/sj",
	"IQa5u+f+0V5+Zf4TahuKHsiDDjVvQu5vepDe8dTc2nckB42b+f1J9enq6hJOL8+7bfal0hnOLGIAXVUy",
	"uObokHSQ9eG4LpEYbgt0uJDpVhiGmbEIaezy6FqGUjBBGkhtGDu9PE/jm5Pjk9FfRicCga/Q6cqoiXo9",
	"Ohm9VgNV6VDE3Me6MuPMmrGuQzHWaRFGsHzqmu1czmST5jBdxkSm5G8ZCfQsYEqNzdxhPjQOhHaSzsxQ",
	"ya06uHbJg7bAGWGa2pmnnEHv6AbQLgcNRV1qN5yRQZfb5bVLSkCmwQAoDnzj5qCBD+xiCIUOm8FeO8Lc",
	"EGaBYaqzGwh+Q7tYn2krCgMyba28T2gLcaJUO8/VRDV6QZRDHQqVGIIc3vt8+Wwqb1+urbbJKLMz/rEh",
	"NP84OXmRADpFuac5T9uCUiwk5ioemenahkMeupA7KTtQXJelpuUaXdBQoculvGcX52D93Dg4aqo4NM4E",
	"I6vgON7epnHLgAd5zEgLpGHww/TUEvvs4nwEV6RzFGJ6lzZXIlRl68jnaxcJ26ql2N0arHfzoTULaZIt",
	"dXIlbYwur7xxAQxDVU+tya7dFDMttG38QqEZnAdGljaGJYY4C8AkTjKY0MfJVpW9OCl3lej/n5V7ArSH",
	"lnFZg2Gun4GRrUPQDroBFsmQii5laz5RUlV3SLnWGnOMIWyXTgRKqy9YvSx2a0V0ELQSg8510HDkPFRW",
	"GxfwLhw/GUXxGlkuNEZ6xWvcuA+v8b3JV6l1LQbcx+1zVJqdMpOtRrrEgMRq8vVeGclJNl2rHydJS26T",
	"dbAB3gPaefVtrzhv9mdLCiuHI5NjWXkp29PBS0Y3ubYN2W0nLBuK7Xyqlv4GhwE5rGdQK0fEonwldcta",
	"N2Q23HzIapfL2qw8BREmnhFMji6YsExjicggj+BMNOtQRrC8zGQ8NzNLW/bX7tbTzV/F5xLYlJVdAmZF",
	"s37lajv0XnGSDybvm3RrGf2yrdI46emT8zZ5Cf8ZSisyJqIQs9bMPou7DW5NKLoa7VS96HRt71D5iKFR",
	"vi+IUuOhB6IvSAuToXAoBbrcmwYLdMgMFfkprtOqmi+BQ0ldyvv+Vv9ZIy3Xvd58Mq4zebibnw+Z7qOm",
	"B5v1u6fuJekeDfMtX0nJJFhqsmqixmr1bfXfAAAA//+p4Z2ZoBQAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
