// Code generated by ent, DO NOT EDIT.

package githubinstallstate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the githubinstallstate type in the database.
	Label = "github_install_state"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStateHash holds the string denoting the state_hash field in the database.
	FieldStateHash = "state_hash"
	// FieldOrgSlug holds the string denoting the org_slug field in the database.
	FieldOrgSlug = "org_slug"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldConsumedAt holds the string denoting the consumed_at field in the database.
	FieldConsumedAt = "consumed_at"
	// Table holds the table name of the githubinstallstate in the database.
	Table = "github_install_states"
)

// Columns holds all SQL columns for githubinstallstate fields.
var Columns = []string{
	FieldID,
	FieldStateHash,
	FieldOrgSlug,
	FieldUserID,
	FieldCreatedAt,
	FieldExpiresAt,
	FieldConsumedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// StateHashValidator is a validator for the "state_hash" field. It is called by the builders before save.
	StateHashValidator func([]byte) error
	// OrgSlugValidator is a validator for the "org_slug" field. It is called by the builders before save.
	OrgSlugValidator func(string) error
	// UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	UserIDValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the GithubInstallState queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOrgSlug orders the results by the org_slug field.
func ByOrgSlug(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrgSlug, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByConsumedAt orders the results by the consumed_at field.
func ByConsumedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConsumedAt, opts...).ToFunc()
}
