// Code generated by ent, DO NOT EDIT.

package githubinstallstate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/spacefleet/app/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldLTE(FieldID, id))
}

// StateHash applies equality check predicate on the "state_hash" field. It's identical to StateHashEQ.
func StateHash(v []byte) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldEQ(FieldStateHash, v))
}

// OrgSlug applies equality check predicate on the "org_slug" field. It's identical to OrgSlugEQ.
func OrgSlug(v string) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldEQ(FieldOrgSlug, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldEQ(FieldUserID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldEQ(FieldCreatedAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldEQ(FieldExpiresAt, v))
}

// ConsumedAt applies equality check predicate on the "consumed_at" field. It's identical to ConsumedAtEQ.
func ConsumedAt(v time.Time) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldEQ(FieldConsumedAt, v))
}

// StateHashEQ applies the EQ predicate on the "state_hash" field.
func StateHashEQ(v []byte) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldEQ(FieldStateHash, v))
}

// StateHashNEQ applies the NEQ predicate on the "state_hash" field.
func StateHashNEQ(v []byte) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldNEQ(FieldStateHash, v))
}

// StateHashIn applies the In predicate on the "state_hash" field.
func StateHashIn(vs ...[]byte) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldIn(FieldStateHash, vs...))
}

// StateHashNotIn applies the NotIn predicate on the "state_hash" field.
func StateHashNotIn(vs ...[]byte) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldNotIn(FieldStateHash, vs...))
}

// StateHashGT applies the GT predicate on the "state_hash" field.
func StateHashGT(v []byte) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldGT(FieldStateHash, v))
}

// StateHashGTE applies the GTE predicate on the "state_hash" field.
func StateHashGTE(v []byte) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldGTE(FieldStateHash, v))
}

// StateHashLT applies the LT predicate on the "state_hash" field.
func StateHashLT(v []byte) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldLT(FieldStateHash, v))
}

// StateHashLTE applies the LTE predicate on the "state_hash" field.
func StateHashLTE(v []byte) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldLTE(FieldStateHash, v))
}

// OrgSlugEQ applies the EQ predicate on the "org_slug" field.
func OrgSlugEQ(v string) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldEQ(FieldOrgSlug, v))
}

// OrgSlugNEQ applies the NEQ predicate on the "org_slug" field.
func OrgSlugNEQ(v string) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldNEQ(FieldOrgSlug, v))
}

// OrgSlugIn applies the In predicate on the "org_slug" field.
func OrgSlugIn(vs ...string) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldIn(FieldOrgSlug, vs...))
}

// OrgSlugNotIn applies the NotIn predicate on the "org_slug" field.
func OrgSlugNotIn(vs ...string) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldNotIn(FieldOrgSlug, vs...))
}

// OrgSlugGT applies the GT predicate on the "org_slug" field.
func OrgSlugGT(v string) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldGT(FieldOrgSlug, v))
}

// OrgSlugGTE applies the GTE predicate on the "org_slug" field.
func OrgSlugGTE(v string) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldGTE(FieldOrgSlug, v))
}

// OrgSlugLT applies the LT predicate on the "org_slug" field.
func OrgSlugLT(v string) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldLT(FieldOrgSlug, v))
}

// OrgSlugLTE applies the LTE predicate on the "org_slug" field.
func OrgSlugLTE(v string) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldLTE(FieldOrgSlug, v))
}

// OrgSlugContains applies the Contains predicate on the "org_slug" field.
func OrgSlugContains(v string) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldContains(FieldOrgSlug, v))
}

// OrgSlugHasPrefix applies the HasPrefix predicate on the "org_slug" field.
func OrgSlugHasPrefix(v string) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldHasPrefix(FieldOrgSlug, v))
}

// OrgSlugHasSuffix applies the HasSuffix predicate on the "org_slug" field.
func OrgSlugHasSuffix(v string) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldHasSuffix(FieldOrgSlug, v))
}

// OrgSlugEqualFold applies the EqualFold predicate on the "org_slug" field.
func OrgSlugEqualFold(v string) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldEqualFold(FieldOrgSlug, v))
}

// OrgSlugContainsFold applies the ContainsFold predicate on the "org_slug" field.
func OrgSlugContainsFold(v string) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldContainsFold(FieldOrgSlug, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldContainsFold(FieldUserID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldLTE(FieldCreatedAt, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldLTE(FieldExpiresAt, v))
}

// ConsumedAtEQ applies the EQ predicate on the "consumed_at" field.
func ConsumedAtEQ(v time.Time) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldEQ(FieldConsumedAt, v))
}

// ConsumedAtNEQ applies the NEQ predicate on the "consumed_at" field.
func ConsumedAtNEQ(v time.Time) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldNEQ(FieldConsumedAt, v))
}

// ConsumedAtIn applies the In predicate on the "consumed_at" field.
func ConsumedAtIn(vs ...time.Time) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldIn(FieldConsumedAt, vs...))
}

// ConsumedAtNotIn applies the NotIn predicate on the "consumed_at" field.
func ConsumedAtNotIn(vs ...time.Time) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldNotIn(FieldConsumedAt, vs...))
}

// ConsumedAtGT applies the GT predicate on the "consumed_at" field.
func ConsumedAtGT(v time.Time) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldGT(FieldConsumedAt, v))
}

// ConsumedAtGTE applies the GTE predicate on the "consumed_at" field.
func ConsumedAtGTE(v time.Time) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldGTE(FieldConsumedAt, v))
}

// ConsumedAtLT applies the LT predicate on the "consumed_at" field.
func ConsumedAtLT(v time.Time) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldLT(FieldConsumedAt, v))
}

// ConsumedAtLTE applies the LTE predicate on the "consumed_at" field.
func ConsumedAtLTE(v time.Time) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldLTE(FieldConsumedAt, v))
}

// ConsumedAtIsNil applies the IsNil predicate on the "consumed_at" field.
func ConsumedAtIsNil() predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldIsNull(FieldConsumedAt))
}

// ConsumedAtNotNil applies the NotNil predicate on the "consumed_at" field.
func ConsumedAtNotNil() predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.FieldNotNull(FieldConsumedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GithubInstallState) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GithubInstallState) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GithubInstallState) predicate.GithubInstallState {
	return predicate.GithubInstallState(sql.NotPredicates(p))
}
