// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AppsColumns holds the columns for the "apps" table.
	AppsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "org_slug", Type: field.TypeString},
		{Name: "name", Type: field.TypeString, Size: 200},
		{Name: "slug", Type: field.TypeString, Size: 50},
		{Name: "cloud_account_id", Type: field.TypeUUID},
		{Name: "github_installation_id", Type: field.TypeUUID},
		{Name: "github_repo_full_name", Type: field.TypeString},
		{Name: "default_branch", Type: field.TypeString},
		{Name: "created_by", Type: field.TypeString},
		{Name: "deleting_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// AppsTable holds the schema information for the "apps" table.
	AppsTable = &schema.Table{
		Name:       "apps",
		Columns:    AppsColumns,
		PrimaryKey: []*schema.Column{AppsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "app_org_slug",
				Unique:  false,
				Columns: []*schema.Column{AppsColumns[1]},
			},
			{
				Name:    "app_org_slug_slug",
				Unique:  true,
				Columns: []*schema.Column{AppsColumns[1], AppsColumns[3]},
			},
		},
	}
	// BuildsColumns holds the columns for the "builds" table.
	BuildsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "app_id", Type: field.TypeUUID},
		{Name: "source_ref", Type: field.TypeString},
		{Name: "source_sha", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeString, Default: "queued"},
		{Name: "stages", Type: field.TypeJSON},
		{Name: "image_uri", Type: field.TypeString, Nullable: true},
		{Name: "image_digest", Type: field.TypeString, Nullable: true},
		{Name: "fargate_task_arn", Type: field.TypeString, Nullable: true},
		{Name: "log_group", Type: field.TypeString, Nullable: true},
		{Name: "log_stream", Type: field.TypeString, Nullable: true},
		{Name: "webhook_secret", Type: field.TypeString},
		{Name: "error_message", Type: field.TypeString, Nullable: true},
		{Name: "created_by", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "started_at", Type: field.TypeTime, Nullable: true},
		{Name: "ended_at", Type: field.TypeTime, Nullable: true},
	}
	// BuildsTable holds the schema information for the "builds" table.
	BuildsTable = &schema.Table{
		Name:       "builds",
		Columns:    BuildsColumns,
		PrimaryKey: []*schema.Column{BuildsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "build_app_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{BuildsColumns[1], BuildsColumns[14]},
			},
			{
				Name:    "build_status",
				Unique:  false,
				Columns: []*schema.Column{BuildsColumns[4]},
			},
		},
	}
	// CliAuthCodesColumns holds the columns for the "cli_auth_codes" table.
	CliAuthCodesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "user_id", Type: field.TypeString},
		{Name: "code_hash", Type: field.TypeBytes, Unique: true, Size: 32},
		{Name: "challenge", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "consumed_at", Type: field.TypeTime, Nullable: true},
	}
	// CliAuthCodesTable holds the schema information for the "cli_auth_codes" table.
	CliAuthCodesTable = &schema.Table{
		Name:       "cli_auth_codes",
		Columns:    CliAuthCodesColumns,
		PrimaryKey: []*schema.Column{CliAuthCodesColumns[0]},
	}
	// CliTokensColumns holds the columns for the "cli_tokens" table.
	CliTokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "user_id", Type: field.TypeString},
		{Name: "token_hash", Type: field.TypeBytes, Unique: true, Size: 32},
		{Name: "name", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "last_used_at", Type: field.TypeTime, Nullable: true},
		{Name: "revoked_at", Type: field.TypeTime, Nullable: true},
	}
	// CliTokensTable holds the schema information for the "cli_tokens" table.
	CliTokensTable = &schema.Table{
		Name:       "cli_tokens",
		Columns:    CliTokensColumns,
		PrimaryKey: []*schema.Column{CliTokensColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "clitoken_user_id",
				Unique:  false,
				Columns: []*schema.Column{CliTokensColumns[1]},
			},
		},
	}
	// CloudAccountsColumns holds the columns for the "cloud_accounts" table.
	CloudAccountsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "org_slug", Type: field.TypeString},
		{Name: "provider", Type: field.TypeString, Default: "aws"},
		{Name: "label", Type: field.TypeString},
		{Name: "account_id", Type: field.TypeString, Nullable: true},
		{Name: "role_arn", Type: field.TypeString, Nullable: true},
		{Name: "external_id", Type: field.TypeString},
		{Name: "region", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeString, Default: "pending"},
		{Name: "last_verified_at", Type: field.TypeTime, Nullable: true},
		{Name: "last_verification_error", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// CloudAccountsTable holds the schema information for the "cloud_accounts" table.
	CloudAccountsTable = &schema.Table{
		Name:       "cloud_accounts",
		Columns:    CloudAccountsColumns,
		PrimaryKey: []*schema.Column{CloudAccountsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "cloudaccount_org_slug",
				Unique:  false,
				Columns: []*schema.Column{CloudAccountsColumns[1]},
			},
			{
				Name:    "cloudaccount_org_slug_provider_label",
				Unique:  true,
				Columns: []*schema.Column{CloudAccountsColumns[1], CloudAccountsColumns[2], CloudAccountsColumns[3]},
			},
		},
	}
	// GithubInstallStatesColumns holds the columns for the "github_install_states" table.
	GithubInstallStatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "state_hash", Type: field.TypeBytes, Unique: true, Size: 32},
		{Name: "org_slug", Type: field.TypeString},
		{Name: "user_id", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "consumed_at", Type: field.TypeTime, Nullable: true},
	}
	// GithubInstallStatesTable holds the schema information for the "github_install_states" table.
	GithubInstallStatesTable = &schema.Table{
		Name:       "github_install_states",
		Columns:    GithubInstallStatesColumns,
		PrimaryKey: []*schema.Column{GithubInstallStatesColumns[0]},
	}
	// GithubInstallationsColumns holds the columns for the "github_installations" table.
	GithubInstallationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "org_slug", Type: field.TypeString},
		{Name: "installation_id", Type: field.TypeInt64, Unique: true},
		{Name: "account_login", Type: field.TypeString},
		{Name: "account_type", Type: field.TypeString},
		{Name: "account_id", Type: field.TypeInt64},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "suspended_at", Type: field.TypeTime, Nullable: true},
	}
	// GithubInstallationsTable holds the schema information for the "github_installations" table.
	GithubInstallationsTable = &schema.Table{
		Name:       "github_installations",
		Columns:    GithubInstallationsColumns,
		PrimaryKey: []*schema.Column{GithubInstallationsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "githubinstallation_org_slug",
				Unique:  false,
				Columns: []*schema.Column{GithubInstallationsColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AppsTable,
		BuildsTable,
		CliAuthCodesTable,
		CliTokensTable,
		CloudAccountsTable,
		GithubInstallStatesTable,
		GithubInstallationsTable,
	}
)

func init() {
}
