// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/spacefleet/app/ent/app"
)

// AppCreate is the builder for creating a App entity.
type AppCreate struct {
	config
	mutation *AppMutation
	hooks    []Hook
}

// SetOrgSlug sets the "org_slug" field.
func (_c *AppCreate) SetOrgSlug(v string) *AppCreate {
	_c.mutation.SetOrgSlug(v)
	return _c
}

// SetName sets the "name" field.
func (_c *AppCreate) SetName(v string) *AppCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetSlug sets the "slug" field.
func (_c *AppCreate) SetSlug(v string) *AppCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetCloudAccountID sets the "cloud_account_id" field.
func (_c *AppCreate) SetCloudAccountID(v uuid.UUID) *AppCreate {
	_c.mutation.SetCloudAccountID(v)
	return _c
}

// SetGithubInstallationID sets the "github_installation_id" field.
func (_c *AppCreate) SetGithubInstallationID(v uuid.UUID) *AppCreate {
	_c.mutation.SetGithubInstallationID(v)
	return _c
}

// SetGithubRepoFullName sets the "github_repo_full_name" field.
func (_c *AppCreate) SetGithubRepoFullName(v string) *AppCreate {
	_c.mutation.SetGithubRepoFullName(v)
	return _c
}

// SetDefaultBranch sets the "default_branch" field.
func (_c *AppCreate) SetDefaultBranch(v string) *AppCreate {
	_c.mutation.SetDefaultBranch(v)
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *AppCreate) SetCreatedBy(v string) *AppCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetDeletingAt sets the "deleting_at" field.
func (_c *AppCreate) SetDeletingAt(v time.Time) *AppCreate {
	_c.mutation.SetDeletingAt(v)
	return _c
}

// SetNillableDeletingAt sets the "deleting_at" field if the given value is not nil.
func (_c *AppCreate) SetNillableDeletingAt(v *time.Time) *AppCreate {
	if v != nil {
		_c.SetDeletingAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AppCreate) SetCreatedAt(v time.Time) *AppCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AppCreate) SetNillableCreatedAt(v *time.Time) *AppCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AppCreate) SetUpdatedAt(v time.Time) *AppCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AppCreate) SetNillableUpdatedAt(v *time.Time) *AppCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AppCreate) SetID(v uuid.UUID) *AppCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AppCreate) SetNillableID(v *uuid.UUID) *AppCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the AppMutation object of the builder.
func (_c *AppCreate) Mutation() *AppMutation {
	return _c.mutation
}

// Save creates the App in the database.
func (_c *AppCreate) Save(ctx context.Context) (*App, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AppCreate) SaveX(ctx context.Context) *App {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AppCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AppCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AppCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := app.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := app.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := app.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AppCreate) check() error {
	if _, ok := _c.mutation.OrgSlug(); !ok {
		return &ValidationError{Name: "org_slug", err: errors.New(`ent: missing required field "App.org_slug"`)}
	}
	if v, ok := _c.mutation.OrgSlug(); ok {
		if err := app.OrgSlugValidator(v); err != nil {
			return &ValidationError{Name: "org_slug", err: fmt.Errorf(`ent: validator failed for field "App.org_slug": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "App.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := app.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "App.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "App.slug"`)}
	}
	if v, ok := _c.mutation.Slug(); ok {
		if err := app.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "App.slug": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CloudAccountID(); !ok {
		return &ValidationError{Name: "cloud_account_id", err: errors.New(`ent: missing required field "App.cloud_account_id"`)}
	}
	if _, ok := _c.mutation.GithubInstallationID(); !ok {
		return &ValidationError{Name: "github_installation_id", err: errors.New(`ent: missing required field "App.github_installation_id"`)}
	}
	if _, ok := _c.mutation.GithubRepoFullName(); !ok {
		return &ValidationError{Name: "github_repo_full_name", err: errors.New(`ent: missing required field "App.github_repo_full_name"`)}
	}
	if v, ok := _c.mutation.GithubRepoFullName(); ok {
		if err := app.GithubRepoFullNameValidator(v); err != nil {
			return &ValidationError{Name: "github_repo_full_name", err: fmt.Errorf(`ent: validator failed for field "App.github_repo_full_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DefaultBranch(); !ok {
		return &ValidationError{Name: "default_branch", err: errors.New(`ent: missing required field "App.default_branch"`)}
	}
	if v, ok := _c.mutation.DefaultBranch(); ok {
		if err := app.DefaultBranchValidator(v); err != nil {
			return &ValidationError{Name: "default_branch", err: fmt.Errorf(`ent: validator failed for field "App.default_branch": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "App.created_by"`)}
	}
	if v, ok := _c.mutation.CreatedBy(); ok {
		if err := app.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "App.created_by": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "App.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "App.updated_at"`)}
	}
	return nil
}

func (_c *AppCreate) sqlSave(ctx context.Context) (*App, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AppCreate) createSpec() (*App, *sqlgraph.CreateSpec) {
	var (
		_node = &App{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(app.Table, sqlgraph.NewFieldSpec(app.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.OrgSlug(); ok {
		_spec.SetField(app.FieldOrgSlug, field.TypeString, value)
		_node.OrgSlug = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(app.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(app.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.CloudAccountID(); ok {
		_spec.SetField(app.FieldCloudAccountID, field.TypeUUID, value)
		_node.CloudAccountID = value
	}
	if value, ok := _c.mutation.GithubInstallationID(); ok {
		_spec.SetField(app.FieldGithubInstallationID, field.TypeUUID, value)
		_node.GithubInstallationID = value
	}
	if value, ok := _c.mutation.GithubRepoFullName(); ok {
		_spec.SetField(app.FieldGithubRepoFullName, field.TypeString, value)
		_node.GithubRepoFullName = value
	}
	if value, ok := _c.mutation.DefaultBranch(); ok {
		_spec.SetField(app.FieldDefaultBranch, field.TypeString, value)
		_node.DefaultBranch = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(app.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.DeletingAt(); ok {
		_spec.SetField(app.FieldDeletingAt, field.TypeTime, value)
		_node.DeletingAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(app.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(app.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// AppCreateBulk is the builder for creating many App entities in bulk.
type AppCreateBulk struct {
	config
	err      error
	builders []*AppCreate
}

// Save creates the App entities in the database.
func (_c *AppCreateBulk) Save(ctx context.Context) ([]*App, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*App, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AppMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AppCreateBulk) SaveX(ctx context.Context) []*App {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AppCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AppCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
