// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/spacefleet/app/ent/cliauthcode"
	"github.com/spacefleet/app/ent/predicate"
)

// CLIAuthCodeUpdate is the builder for updating CLIAuthCode entities.
type CLIAuthCodeUpdate struct {
	config
	hooks    []Hook
	mutation *CLIAuthCodeMutation
}

// Where appends a list predicates to the CLIAuthCodeUpdate builder.
func (_u *CLIAuthCodeUpdate) Where(ps ...predicate.CLIAuthCode) *CLIAuthCodeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CLIAuthCodeUpdate) SetUserID(v string) *CLIAuthCodeUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CLIAuthCodeUpdate) SetNillableUserID(v *string) *CLIAuthCodeUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCodeHash sets the "code_hash" field.
func (_u *CLIAuthCodeUpdate) SetCodeHash(v []byte) *CLIAuthCodeUpdate {
	_u.mutation.SetCodeHash(v)
	return _u
}

// SetChallenge sets the "challenge" field.
func (_u *CLIAuthCodeUpdate) SetChallenge(v string) *CLIAuthCodeUpdate {
	_u.mutation.SetChallenge(v)
	return _u
}

// SetNillableChallenge sets the "challenge" field if the given value is not nil.
func (_u *CLIAuthCodeUpdate) SetNillableChallenge(v *string) *CLIAuthCodeUpdate {
	if v != nil {
		_u.SetChallenge(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *CLIAuthCodeUpdate) SetName(v string) *CLIAuthCodeUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CLIAuthCodeUpdate) SetNillableName(v *string) *CLIAuthCodeUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *CLIAuthCodeUpdate) SetExpiresAt(v time.Time) *CLIAuthCodeUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *CLIAuthCodeUpdate) SetNillableExpiresAt(v *time.Time) *CLIAuthCodeUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetConsumedAt sets the "consumed_at" field.
func (_u *CLIAuthCodeUpdate) SetConsumedAt(v time.Time) *CLIAuthCodeUpdate {
	_u.mutation.SetConsumedAt(v)
	return _u
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_u *CLIAuthCodeUpdate) SetNillableConsumedAt(v *time.Time) *CLIAuthCodeUpdate {
	if v != nil {
		_u.SetConsumedAt(*v)
	}
	return _u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (_u *CLIAuthCodeUpdate) ClearConsumedAt() *CLIAuthCodeUpdate {
	_u.mutation.ClearConsumedAt()
	return _u
}

// Mutation returns the CLIAuthCodeMutation object of the builder.
func (_u *CLIAuthCodeUpdate) Mutation() *CLIAuthCodeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CLIAuthCodeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CLIAuthCodeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CLIAuthCodeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CLIAuthCodeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CLIAuthCodeUpdate) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := cliauthcode.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "CLIAuthCode.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CodeHash(); ok {
		if err := cliauthcode.CodeHashValidator(v); err != nil {
			return &ValidationError{Name: "code_hash", err: fmt.Errorf(`ent: validator failed for field "CLIAuthCode.code_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Challenge(); ok {
		if err := cliauthcode.ChallengeValidator(v); err != nil {
			return &ValidationError{Name: "challenge", err: fmt.Errorf(`ent: validator failed for field "CLIAuthCode.challenge": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := cliauthcode.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CLIAuthCode.name": %w`, err)}
		}
	}
	return nil
}

func (_u *CLIAuthCodeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(cliauthcode.Table, cliauthcode.Columns, sqlgraph.NewFieldSpec(cliauthcode.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(cliauthcode.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.CodeHash(); ok {
		_spec.SetField(cliauthcode.FieldCodeHash, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.Challenge(); ok {
		_spec.SetField(cliauthcode.FieldChallenge, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(cliauthcode.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(cliauthcode.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ConsumedAt(); ok {
		_spec.SetField(cliauthcode.FieldConsumedAt, field.TypeTime, value)
	}
	if _u.mutation.ConsumedAtCleared() {
		_spec.ClearField(cliauthcode.FieldConsumedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cliauthcode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CLIAuthCodeUpdateOne is the builder for updating a single CLIAuthCode entity.
type CLIAuthCodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CLIAuthCodeMutation
}

// SetUserID sets the "user_id" field.
func (_u *CLIAuthCodeUpdateOne) SetUserID(v string) *CLIAuthCodeUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CLIAuthCodeUpdateOne) SetNillableUserID(v *string) *CLIAuthCodeUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCodeHash sets the "code_hash" field.
func (_u *CLIAuthCodeUpdateOne) SetCodeHash(v []byte) *CLIAuthCodeUpdateOne {
	_u.mutation.SetCodeHash(v)
	return _u
}

// SetChallenge sets the "challenge" field.
func (_u *CLIAuthCodeUpdateOne) SetChallenge(v string) *CLIAuthCodeUpdateOne {
	_u.mutation.SetChallenge(v)
	return _u
}

// SetNillableChallenge sets the "challenge" field if the given value is not nil.
func (_u *CLIAuthCodeUpdateOne) SetNillableChallenge(v *string) *CLIAuthCodeUpdateOne {
	if v != nil {
		_u.SetChallenge(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *CLIAuthCodeUpdateOne) SetName(v string) *CLIAuthCodeUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CLIAuthCodeUpdateOne) SetNillableName(v *string) *CLIAuthCodeUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *CLIAuthCodeUpdateOne) SetExpiresAt(v time.Time) *CLIAuthCodeUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *CLIAuthCodeUpdateOne) SetNillableExpiresAt(v *time.Time) *CLIAuthCodeUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetConsumedAt sets the "consumed_at" field.
func (_u *CLIAuthCodeUpdateOne) SetConsumedAt(v time.Time) *CLIAuthCodeUpdateOne {
	_u.mutation.SetConsumedAt(v)
	return _u
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_u *CLIAuthCodeUpdateOne) SetNillableConsumedAt(v *time.Time) *CLIAuthCodeUpdateOne {
	if v != nil {
		_u.SetConsumedAt(*v)
	}
	return _u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (_u *CLIAuthCodeUpdateOne) ClearConsumedAt() *CLIAuthCodeUpdateOne {
	_u.mutation.ClearConsumedAt()
	return _u
}

// Mutation returns the CLIAuthCodeMutation object of the builder.
func (_u *CLIAuthCodeUpdateOne) Mutation() *CLIAuthCodeMutation {
	return _u.mutation
}

// Where appends a list predicates to the CLIAuthCodeUpdate builder.
func (_u *CLIAuthCodeUpdateOne) Where(ps ...predicate.CLIAuthCode) *CLIAuthCodeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CLIAuthCodeUpdateOne) Select(field string, fields ...string) *CLIAuthCodeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CLIAuthCode entity.
func (_u *CLIAuthCodeUpdateOne) Save(ctx context.Context) (*CLIAuthCode, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CLIAuthCodeUpdateOne) SaveX(ctx context.Context) *CLIAuthCode {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CLIAuthCodeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CLIAuthCodeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CLIAuthCodeUpdateOne) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := cliauthcode.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "CLIAuthCode.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CodeHash(); ok {
		if err := cliauthcode.CodeHashValidator(v); err != nil {
			return &ValidationError{Name: "code_hash", err: fmt.Errorf(`ent: validator failed for field "CLIAuthCode.code_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Challenge(); ok {
		if err := cliauthcode.ChallengeValidator(v); err != nil {
			return &ValidationError{Name: "challenge", err: fmt.Errorf(`ent: validator failed for field "CLIAuthCode.challenge": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := cliauthcode.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CLIAuthCode.name": %w`, err)}
		}
	}
	return nil
}

func (_u *CLIAuthCodeUpdateOne) sqlSave(ctx context.Context) (_node *CLIAuthCode, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(cliauthcode.Table, cliauthcode.Columns, sqlgraph.NewFieldSpec(cliauthcode.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CLIAuthCode.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cliauthcode.FieldID)
		for _, f := range fields {
			if !cliauthcode.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != cliauthcode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(cliauthcode.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.CodeHash(); ok {
		_spec.SetField(cliauthcode.FieldCodeHash, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.Challenge(); ok {
		_spec.SetField(cliauthcode.FieldChallenge, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(cliauthcode.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(cliauthcode.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ConsumedAt(); ok {
		_spec.SetField(cliauthcode.FieldConsumedAt, field.TypeTime, value)
	}
	if _u.mutation.ConsumedAtCleared() {
		_spec.ClearField(cliauthcode.FieldConsumedAt, field.TypeTime)
	}
	_node = &CLIAuthCode{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cliauthcode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
