// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/spacefleet/app/ent/cliauthcode"
	"github.com/spacefleet/app/ent/predicate"
)

// CLIAuthCodeDelete is the builder for deleting a CLIAuthCode entity.
type CLIAuthCodeDelete struct {
	config
	hooks    []Hook
	mutation *CLIAuthCodeMutation
}

// Where appends a list predicates to the CLIAuthCodeDelete builder.
func (_d *CLIAuthCodeDelete) Where(ps ...predicate.CLIAuthCode) *CLIAuthCodeDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CLIAuthCodeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CLIAuthCodeDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CLIAuthCodeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(cliauthcode.Table, sqlgraph.NewFieldSpec(cliauthcode.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CLIAuthCodeDeleteOne is the builder for deleting a single CLIAuthCode entity.
type CLIAuthCodeDeleteOne struct {
	_d *CLIAuthCodeDelete
}

// Where appends a list predicates to the CLIAuthCodeDelete builder.
func (_d *CLIAuthCodeDeleteOne) Where(ps ...predicate.CLIAuthCode) *CLIAuthCodeDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CLIAuthCodeDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{cliauthcode.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CLIAuthCodeDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
