// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/google/uuid"
	"github.com/spacefleet/app/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/spacefleet/app/ent/app"
	"github.com/spacefleet/app/ent/build"
	"github.com/spacefleet/app/ent/cliauthcode"
	"github.com/spacefleet/app/ent/clitoken"
	"github.com/spacefleet/app/ent/cloudaccount"
	"github.com/spacefleet/app/ent/githubinstallation"
	"github.com/spacefleet/app/ent/githubinstallstate"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// App is the client for interacting with the App builders.
	App *AppClient
	// Build is the client for interacting with the Build builders.
	Build *BuildClient
	// CLIAuthCode is the client for interacting with the CLIAuthCode builders.
	CLIAuthCode *CLIAuthCodeClient
	// CLIToken is the client for interacting with the CLIToken builders.
	CLIToken *CLITokenClient
	// CloudAccount is the client for interacting with the CloudAccount builders.
	CloudAccount *CloudAccountClient
	// GithubInstallState is the client for interacting with the GithubInstallState builders.
	GithubInstallState *GithubInstallStateClient
	// GithubInstallation is the client for interacting with the GithubInstallation builders.
	GithubInstallation *GithubInstallationClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.App = NewAppClient(c.config)
	c.Build = NewBuildClient(c.config)
	c.CLIAuthCode = NewCLIAuthCodeClient(c.config)
	c.CLIToken = NewCLITokenClient(c.config)
	c.CloudAccount = NewCloudAccountClient(c.config)
	c.GithubInstallState = NewGithubInstallStateClient(c.config)
	c.GithubInstallation = NewGithubInstallationClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                ctx,
		config:             cfg,
		App:                NewAppClient(cfg),
		Build:              NewBuildClient(cfg),
		CLIAuthCode:        NewCLIAuthCodeClient(cfg),
		CLIToken:           NewCLITokenClient(cfg),
		CloudAccount:       NewCloudAccountClient(cfg),
		GithubInstallState: NewGithubInstallStateClient(cfg),
		GithubInstallation: NewGithubInstallationClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                ctx,
		config:             cfg,
		App:                NewAppClient(cfg),
		Build:              NewBuildClient(cfg),
		CLIAuthCode:        NewCLIAuthCodeClient(cfg),
		CLIToken:           NewCLITokenClient(cfg),
		CloudAccount:       NewCloudAccountClient(cfg),
		GithubInstallState: NewGithubInstallStateClient(cfg),
		GithubInstallation: NewGithubInstallationClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		App.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.App, c.Build, c.CLIAuthCode, c.CLIToken, c.CloudAccount, c.GithubInstallState,
		c.GithubInstallation,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.App, c.Build, c.CLIAuthCode, c.CLIToken, c.CloudAccount, c.GithubInstallState,
		c.GithubInstallation,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *AppMutation:
		return c.App.mutate(ctx, m)
	case *BuildMutation:
		return c.Build.mutate(ctx, m)
	case *CLIAuthCodeMutation:
		return c.CLIAuthCode.mutate(ctx, m)
	case *CLITokenMutation:
		return c.CLIToken.mutate(ctx, m)
	case *CloudAccountMutation:
		return c.CloudAccount.mutate(ctx, m)
	case *GithubInstallStateMutation:
		return c.GithubInstallState.mutate(ctx, m)
	case *GithubInstallationMutation:
		return c.GithubInstallation.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// AppClient is a client for the App schema.
type AppClient struct {
	config
}

// NewAppClient returns a client for the App from the given config.
func NewAppClient(c config) *AppClient {
	return &AppClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `app.Hooks(f(g(h())))`.
func (c *AppClient) Use(hooks ...Hook) {
	c.hooks.App = append(c.hooks.App, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `app.Intercept(f(g(h())))`.
func (c *AppClient) Intercept(interceptors ...Interceptor) {
	c.inters.App = append(c.inters.App, interceptors...)
}

// Create returns a builder for creating a App entity.
func (c *AppClient) Create() *AppCreate {
	mutation := newAppMutation(c.config, OpCreate)
	return &AppCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of App entities.
func (c *AppClient) CreateBulk(builders ...*AppCreate) *AppCreateBulk {
	return &AppCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AppClient) MapCreateBulk(slice any, setFunc func(*AppCreate, int)) *AppCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AppCreateBulk{err: fmt.Errorf("calling to AppClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AppCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AppCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for App.
func (c *AppClient) Update() *AppUpdate {
	mutation := newAppMutation(c.config, OpUpdate)
	return &AppUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AppClient) UpdateOne(_m *App) *AppUpdateOne {
	mutation := newAppMutation(c.config, OpUpdateOne, withApp(_m))
	return &AppUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AppClient) UpdateOneID(id uuid.UUID) *AppUpdateOne {
	mutation := newAppMutation(c.config, OpUpdateOne, withAppID(id))
	return &AppUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for App.
func (c *AppClient) Delete() *AppDelete {
	mutation := newAppMutation(c.config, OpDelete)
	return &AppDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AppClient) DeleteOne(_m *App) *AppDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AppClient) DeleteOneID(id uuid.UUID) *AppDeleteOne {
	builder := c.Delete().Where(app.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AppDeleteOne{builder}
}

// Query returns a query builder for App.
func (c *AppClient) Query() *AppQuery {
	return &AppQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeApp},
		inters: c.Interceptors(),
	}
}

// Get returns a App entity by its id.
func (c *AppClient) Get(ctx context.Context, id uuid.UUID) (*App, error) {
	return c.Query().Where(app.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AppClient) GetX(ctx context.Context, id uuid.UUID) *App {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AppClient) Hooks() []Hook {
	return c.hooks.App
}

// Interceptors returns the client interceptors.
func (c *AppClient) Interceptors() []Interceptor {
	return c.inters.App
}

func (c *AppClient) mutate(ctx context.Context, m *AppMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AppCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AppUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AppUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AppDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown App mutation op: %q", m.Op())
	}
}

// BuildClient is a client for the Build schema.
type BuildClient struct {
	config
}

// NewBuildClient returns a client for the Build from the given config.
func NewBuildClient(c config) *BuildClient {
	return &BuildClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `build.Hooks(f(g(h())))`.
func (c *BuildClient) Use(hooks ...Hook) {
	c.hooks.Build = append(c.hooks.Build, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `build.Intercept(f(g(h())))`.
func (c *BuildClient) Intercept(interceptors ...Interceptor) {
	c.inters.Build = append(c.inters.Build, interceptors...)
}

// Create returns a builder for creating a Build entity.
func (c *BuildClient) Create() *BuildCreate {
	mutation := newBuildMutation(c.config, OpCreate)
	return &BuildCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Build entities.
func (c *BuildClient) CreateBulk(builders ...*BuildCreate) *BuildCreateBulk {
	return &BuildCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *BuildClient) MapCreateBulk(slice any, setFunc func(*BuildCreate, int)) *BuildCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &BuildCreateBulk{err: fmt.Errorf("calling to BuildClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*BuildCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &BuildCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Build.
func (c *BuildClient) Update() *BuildUpdate {
	mutation := newBuildMutation(c.config, OpUpdate)
	return &BuildUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BuildClient) UpdateOne(_m *Build) *BuildUpdateOne {
	mutation := newBuildMutation(c.config, OpUpdateOne, withBuild(_m))
	return &BuildUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *BuildClient) UpdateOneID(id uuid.UUID) *BuildUpdateOne {
	mutation := newBuildMutation(c.config, OpUpdateOne, withBuildID(id))
	return &BuildUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Build.
func (c *BuildClient) Delete() *BuildDelete {
	mutation := newBuildMutation(c.config, OpDelete)
	return &BuildDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *BuildClient) DeleteOne(_m *Build) *BuildDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *BuildClient) DeleteOneID(id uuid.UUID) *BuildDeleteOne {
	builder := c.Delete().Where(build.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BuildDeleteOne{builder}
}

// Query returns a query builder for Build.
func (c *BuildClient) Query() *BuildQuery {
	return &BuildQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeBuild},
		inters: c.Interceptors(),
	}
}

// Get returns a Build entity by its id.
func (c *BuildClient) Get(ctx context.Context, id uuid.UUID) (*Build, error) {
	return c.Query().Where(build.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BuildClient) GetX(ctx context.Context, id uuid.UUID) *Build {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *BuildClient) Hooks() []Hook {
	return c.hooks.Build
}

// Interceptors returns the client interceptors.
func (c *BuildClient) Interceptors() []Interceptor {
	return c.inters.Build
}

func (c *BuildClient) mutate(ctx context.Context, m *BuildMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&BuildCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&BuildUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&BuildUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&BuildDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Build mutation op: %q", m.Op())
	}
}

// CLIAuthCodeClient is a client for the CLIAuthCode schema.
type CLIAuthCodeClient struct {
	config
}

// NewCLIAuthCodeClient returns a client for the CLIAuthCode from the given config.
func NewCLIAuthCodeClient(c config) *CLIAuthCodeClient {
	return &CLIAuthCodeClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `cliauthcode.Hooks(f(g(h())))`.
func (c *CLIAuthCodeClient) Use(hooks ...Hook) {
	c.hooks.CLIAuthCode = append(c.hooks.CLIAuthCode, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `cliauthcode.Intercept(f(g(h())))`.
func (c *CLIAuthCodeClient) Intercept(interceptors ...Interceptor) {
	c.inters.CLIAuthCode = append(c.inters.CLIAuthCode, interceptors...)
}

// Create returns a builder for creating a CLIAuthCode entity.
func (c *CLIAuthCodeClient) Create() *CLIAuthCodeCreate {
	mutation := newCLIAuthCodeMutation(c.config, OpCreate)
	return &CLIAuthCodeCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of CLIAuthCode entities.
func (c *CLIAuthCodeClient) CreateBulk(builders ...*CLIAuthCodeCreate) *CLIAuthCodeCreateBulk {
	return &CLIAuthCodeCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CLIAuthCodeClient) MapCreateBulk(slice any, setFunc func(*CLIAuthCodeCreate, int)) *CLIAuthCodeCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CLIAuthCodeCreateBulk{err: fmt.Errorf("calling to CLIAuthCodeClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CLIAuthCodeCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CLIAuthCodeCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for CLIAuthCode.
func (c *CLIAuthCodeClient) Update() *CLIAuthCodeUpdate {
	mutation := newCLIAuthCodeMutation(c.config, OpUpdate)
	return &CLIAuthCodeUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CLIAuthCodeClient) UpdateOne(_m *CLIAuthCode) *CLIAuthCodeUpdateOne {
	mutation := newCLIAuthCodeMutation(c.config, OpUpdateOne, withCLIAuthCode(_m))
	return &CLIAuthCodeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CLIAuthCodeClient) UpdateOneID(id uuid.UUID) *CLIAuthCodeUpdateOne {
	mutation := newCLIAuthCodeMutation(c.config, OpUpdateOne, withCLIAuthCodeID(id))
	return &CLIAuthCodeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for CLIAuthCode.
func (c *CLIAuthCodeClient) Delete() *CLIAuthCodeDelete {
	mutation := newCLIAuthCodeMutation(c.config, OpDelete)
	return &CLIAuthCodeDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CLIAuthCodeClient) DeleteOne(_m *CLIAuthCode) *CLIAuthCodeDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CLIAuthCodeClient) DeleteOneID(id uuid.UUID) *CLIAuthCodeDeleteOne {
	builder := c.Delete().Where(cliauthcode.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CLIAuthCodeDeleteOne{builder}
}

// Query returns a query builder for CLIAuthCode.
func (c *CLIAuthCodeClient) Query() *CLIAuthCodeQuery {
	return &CLIAuthCodeQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCLIAuthCode},
		inters: c.Interceptors(),
	}
}

// Get returns a CLIAuthCode entity by its id.
func (c *CLIAuthCodeClient) Get(ctx context.Context, id uuid.UUID) (*CLIAuthCode, error) {
	return c.Query().Where(cliauthcode.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CLIAuthCodeClient) GetX(ctx context.Context, id uuid.UUID) *CLIAuthCode {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *CLIAuthCodeClient) Hooks() []Hook {
	return c.hooks.CLIAuthCode
}

// Interceptors returns the client interceptors.
func (c *CLIAuthCodeClient) Interceptors() []Interceptor {
	return c.inters.CLIAuthCode
}

func (c *CLIAuthCodeClient) mutate(ctx context.Context, m *CLIAuthCodeMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CLIAuthCodeCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CLIAuthCodeUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CLIAuthCodeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CLIAuthCodeDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown CLIAuthCode mutation op: %q", m.Op())
	}
}

// CLITokenClient is a client for the CLIToken schema.
type CLITokenClient struct {
	config
}

// NewCLITokenClient returns a client for the CLIToken from the given config.
func NewCLITokenClient(c config) *CLITokenClient {
	return &CLITokenClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `clitoken.Hooks(f(g(h())))`.
func (c *CLITokenClient) Use(hooks ...Hook) {
	c.hooks.CLIToken = append(c.hooks.CLIToken, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `clitoken.Intercept(f(g(h())))`.
func (c *CLITokenClient) Intercept(interceptors ...Interceptor) {
	c.inters.CLIToken = append(c.inters.CLIToken, interceptors...)
}

// Create returns a builder for creating a CLIToken entity.
func (c *CLITokenClient) Create() *CLITokenCreate {
	mutation := newCLITokenMutation(c.config, OpCreate)
	return &CLITokenCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of CLIToken entities.
func (c *CLITokenClient) CreateBulk(builders ...*CLITokenCreate) *CLITokenCreateBulk {
	return &CLITokenCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CLITokenClient) MapCreateBulk(slice any, setFunc func(*CLITokenCreate, int)) *CLITokenCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CLITokenCreateBulk{err: fmt.Errorf("calling to CLITokenClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CLITokenCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CLITokenCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for CLIToken.
func (c *CLITokenClient) Update() *CLITokenUpdate {
	mutation := newCLITokenMutation(c.config, OpUpdate)
	return &CLITokenUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CLITokenClient) UpdateOne(_m *CLIToken) *CLITokenUpdateOne {
	mutation := newCLITokenMutation(c.config, OpUpdateOne, withCLIToken(_m))
	return &CLITokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CLITokenClient) UpdateOneID(id uuid.UUID) *CLITokenUpdateOne {
	mutation := newCLITokenMutation(c.config, OpUpdateOne, withCLITokenID(id))
	return &CLITokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for CLIToken.
func (c *CLITokenClient) Delete() *CLITokenDelete {
	mutation := newCLITokenMutation(c.config, OpDelete)
	return &CLITokenDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CLITokenClient) DeleteOne(_m *CLIToken) *CLITokenDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CLITokenClient) DeleteOneID(id uuid.UUID) *CLITokenDeleteOne {
	builder := c.Delete().Where(clitoken.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CLITokenDeleteOne{builder}
}

// Query returns a query builder for CLIToken.
func (c *CLITokenClient) Query() *CLITokenQuery {
	return &CLITokenQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCLIToken},
		inters: c.Interceptors(),
	}
}

// Get returns a CLIToken entity by its id.
func (c *CLITokenClient) Get(ctx context.Context, id uuid.UUID) (*CLIToken, error) {
	return c.Query().Where(clitoken.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CLITokenClient) GetX(ctx context.Context, id uuid.UUID) *CLIToken {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *CLITokenClient) Hooks() []Hook {
	return c.hooks.CLIToken
}

// Interceptors returns the client interceptors.
func (c *CLITokenClient) Interceptors() []Interceptor {
	return c.inters.CLIToken
}

func (c *CLITokenClient) mutate(ctx context.Context, m *CLITokenMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CLITokenCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CLITokenUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CLITokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CLITokenDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown CLIToken mutation op: %q", m.Op())
	}
}

// CloudAccountClient is a client for the CloudAccount schema.
type CloudAccountClient struct {
	config
}

// NewCloudAccountClient returns a client for the CloudAccount from the given config.
func NewCloudAccountClient(c config) *CloudAccountClient {
	return &CloudAccountClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `cloudaccount.Hooks(f(g(h())))`.
func (c *CloudAccountClient) Use(hooks ...Hook) {
	c.hooks.CloudAccount = append(c.hooks.CloudAccount, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `cloudaccount.Intercept(f(g(h())))`.
func (c *CloudAccountClient) Intercept(interceptors ...Interceptor) {
	c.inters.CloudAccount = append(c.inters.CloudAccount, interceptors...)
}

// Create returns a builder for creating a CloudAccount entity.
func (c *CloudAccountClient) Create() *CloudAccountCreate {
	mutation := newCloudAccountMutation(c.config, OpCreate)
	return &CloudAccountCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of CloudAccount entities.
func (c *CloudAccountClient) CreateBulk(builders ...*CloudAccountCreate) *CloudAccountCreateBulk {
	return &CloudAccountCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CloudAccountClient) MapCreateBulk(slice any, setFunc func(*CloudAccountCreate, int)) *CloudAccountCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CloudAccountCreateBulk{err: fmt.Errorf("calling to CloudAccountClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CloudAccountCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CloudAccountCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for CloudAccount.
func (c *CloudAccountClient) Update() *CloudAccountUpdate {
	mutation := newCloudAccountMutation(c.config, OpUpdate)
	return &CloudAccountUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CloudAccountClient) UpdateOne(_m *CloudAccount) *CloudAccountUpdateOne {
	mutation := newCloudAccountMutation(c.config, OpUpdateOne, withCloudAccount(_m))
	return &CloudAccountUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CloudAccountClient) UpdateOneID(id uuid.UUID) *CloudAccountUpdateOne {
	mutation := newCloudAccountMutation(c.config, OpUpdateOne, withCloudAccountID(id))
	return &CloudAccountUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for CloudAccount.
func (c *CloudAccountClient) Delete() *CloudAccountDelete {
	mutation := newCloudAccountMutation(c.config, OpDelete)
	return &CloudAccountDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CloudAccountClient) DeleteOne(_m *CloudAccount) *CloudAccountDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CloudAccountClient) DeleteOneID(id uuid.UUID) *CloudAccountDeleteOne {
	builder := c.Delete().Where(cloudaccount.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CloudAccountDeleteOne{builder}
}

// Query returns a query builder for CloudAccount.
func (c *CloudAccountClient) Query() *CloudAccountQuery {
	return &CloudAccountQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCloudAccount},
		inters: c.Interceptors(),
	}
}

// Get returns a CloudAccount entity by its id.
func (c *CloudAccountClient) Get(ctx context.Context, id uuid.UUID) (*CloudAccount, error) {
	return c.Query().Where(cloudaccount.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CloudAccountClient) GetX(ctx context.Context, id uuid.UUID) *CloudAccount {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *CloudAccountClient) Hooks() []Hook {
	return c.hooks.CloudAccount
}

// Interceptors returns the client interceptors.
func (c *CloudAccountClient) Interceptors() []Interceptor {
	return c.inters.CloudAccount
}

func (c *CloudAccountClient) mutate(ctx context.Context, m *CloudAccountMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CloudAccountCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CloudAccountUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CloudAccountUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CloudAccountDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown CloudAccount mutation op: %q", m.Op())
	}
}

// GithubInstallStateClient is a client for the GithubInstallState schema.
type GithubInstallStateClient struct {
	config
}

// NewGithubInstallStateClient returns a client for the GithubInstallState from the given config.
func NewGithubInstallStateClient(c config) *GithubInstallStateClient {
	return &GithubInstallStateClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `githubinstallstate.Hooks(f(g(h())))`.
func (c *GithubInstallStateClient) Use(hooks ...Hook) {
	c.hooks.GithubInstallState = append(c.hooks.GithubInstallState, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `githubinstallstate.Intercept(f(g(h())))`.
func (c *GithubInstallStateClient) Intercept(interceptors ...Interceptor) {
	c.inters.GithubInstallState = append(c.inters.GithubInstallState, interceptors...)
}

// Create returns a builder for creating a GithubInstallState entity.
func (c *GithubInstallStateClient) Create() *GithubInstallStateCreate {
	mutation := newGithubInstallStateMutation(c.config, OpCreate)
	return &GithubInstallStateCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of GithubInstallState entities.
func (c *GithubInstallStateClient) CreateBulk(builders ...*GithubInstallStateCreate) *GithubInstallStateCreateBulk {
	return &GithubInstallStateCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *GithubInstallStateClient) MapCreateBulk(slice any, setFunc func(*GithubInstallStateCreate, int)) *GithubInstallStateCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &GithubInstallStateCreateBulk{err: fmt.Errorf("calling to GithubInstallStateClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*GithubInstallStateCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &GithubInstallStateCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for GithubInstallState.
func (c *GithubInstallStateClient) Update() *GithubInstallStateUpdate {
	mutation := newGithubInstallStateMutation(c.config, OpUpdate)
	return &GithubInstallStateUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *GithubInstallStateClient) UpdateOne(_m *GithubInstallState) *GithubInstallStateUpdateOne {
	mutation := newGithubInstallStateMutation(c.config, OpUpdateOne, withGithubInstallState(_m))
	return &GithubInstallStateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *GithubInstallStateClient) UpdateOneID(id uuid.UUID) *GithubInstallStateUpdateOne {
	mutation := newGithubInstallStateMutation(c.config, OpUpdateOne, withGithubInstallStateID(id))
	return &GithubInstallStateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for GithubInstallState.
func (c *GithubInstallStateClient) Delete() *GithubInstallStateDelete {
	mutation := newGithubInstallStateMutation(c.config, OpDelete)
	return &GithubInstallStateDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *GithubInstallStateClient) DeleteOne(_m *GithubInstallState) *GithubInstallStateDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *GithubInstallStateClient) DeleteOneID(id uuid.UUID) *GithubInstallStateDeleteOne {
	builder := c.Delete().Where(githubinstallstate.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &GithubInstallStateDeleteOne{builder}
}

// Query returns a query builder for GithubInstallState.
func (c *GithubInstallStateClient) Query() *GithubInstallStateQuery {
	return &GithubInstallStateQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeGithubInstallState},
		inters: c.Interceptors(),
	}
}

// Get returns a GithubInstallState entity by its id.
func (c *GithubInstallStateClient) Get(ctx context.Context, id uuid.UUID) (*GithubInstallState, error) {
	return c.Query().Where(githubinstallstate.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *GithubInstallStateClient) GetX(ctx context.Context, id uuid.UUID) *GithubInstallState {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *GithubInstallStateClient) Hooks() []Hook {
	return c.hooks.GithubInstallState
}

// Interceptors returns the client interceptors.
func (c *GithubInstallStateClient) Interceptors() []Interceptor {
	return c.inters.GithubInstallState
}

func (c *GithubInstallStateClient) mutate(ctx context.Context, m *GithubInstallStateMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&GithubInstallStateCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&GithubInstallStateUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&GithubInstallStateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&GithubInstallStateDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown GithubInstallState mutation op: %q", m.Op())
	}
}

// GithubInstallationClient is a client for the GithubInstallation schema.
type GithubInstallationClient struct {
	config
}

// NewGithubInstallationClient returns a client for the GithubInstallation from the given config.
func NewGithubInstallationClient(c config) *GithubInstallationClient {
	return &GithubInstallationClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `githubinstallation.Hooks(f(g(h())))`.
func (c *GithubInstallationClient) Use(hooks ...Hook) {
	c.hooks.GithubInstallation = append(c.hooks.GithubInstallation, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `githubinstallation.Intercept(f(g(h())))`.
func (c *GithubInstallationClient) Intercept(interceptors ...Interceptor) {
	c.inters.GithubInstallation = append(c.inters.GithubInstallation, interceptors...)
}

// Create returns a builder for creating a GithubInstallation entity.
func (c *GithubInstallationClient) Create() *GithubInstallationCreate {
	mutation := newGithubInstallationMutation(c.config, OpCreate)
	return &GithubInstallationCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of GithubInstallation entities.
func (c *GithubInstallationClient) CreateBulk(builders ...*GithubInstallationCreate) *GithubInstallationCreateBulk {
	return &GithubInstallationCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *GithubInstallationClient) MapCreateBulk(slice any, setFunc func(*GithubInstallationCreate, int)) *GithubInstallationCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &GithubInstallationCreateBulk{err: fmt.Errorf("calling to GithubInstallationClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*GithubInstallationCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &GithubInstallationCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for GithubInstallation.
func (c *GithubInstallationClient) Update() *GithubInstallationUpdate {
	mutation := newGithubInstallationMutation(c.config, OpUpdate)
	return &GithubInstallationUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *GithubInstallationClient) UpdateOne(_m *GithubInstallation) *GithubInstallationUpdateOne {
	mutation := newGithubInstallationMutation(c.config, OpUpdateOne, withGithubInstallation(_m))
	return &GithubInstallationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *GithubInstallationClient) UpdateOneID(id uuid.UUID) *GithubInstallationUpdateOne {
	mutation := newGithubInstallationMutation(c.config, OpUpdateOne, withGithubInstallationID(id))
	return &GithubInstallationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for GithubInstallation.
func (c *GithubInstallationClient) Delete() *GithubInstallationDelete {
	mutation := newGithubInstallationMutation(c.config, OpDelete)
	return &GithubInstallationDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *GithubInstallationClient) DeleteOne(_m *GithubInstallation) *GithubInstallationDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *GithubInstallationClient) DeleteOneID(id uuid.UUID) *GithubInstallationDeleteOne {
	builder := c.Delete().Where(githubinstallation.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &GithubInstallationDeleteOne{builder}
}

// Query returns a query builder for GithubInstallation.
func (c *GithubInstallationClient) Query() *GithubInstallationQuery {
	return &GithubInstallationQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeGithubInstallation},
		inters: c.Interceptors(),
	}
}

// Get returns a GithubInstallation entity by its id.
func (c *GithubInstallationClient) Get(ctx context.Context, id uuid.UUID) (*GithubInstallation, error) {
	return c.Query().Where(githubinstallation.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *GithubInstallationClient) GetX(ctx context.Context, id uuid.UUID) *GithubInstallation {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *GithubInstallationClient) Hooks() []Hook {
	return c.hooks.GithubInstallation
}

// Interceptors returns the client interceptors.
func (c *GithubInstallationClient) Interceptors() []Interceptor {
	return c.inters.GithubInstallation
}

func (c *GithubInstallationClient) mutate(ctx context.Context, m *GithubInstallationMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&GithubInstallationCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&GithubInstallationUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&GithubInstallationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&GithubInstallationDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown GithubInstallation mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		App, Build, CLIAuthCode, CLIToken, CloudAccount, GithubInstallState,
		GithubInstallation []ent.Hook
	}
	inters struct {
		App, Build, CLIAuthCode, CLIToken, CloudAccount, GithubInstallState,
		GithubInstallation []ent.Interceptor
	}
)
