// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/spacefleet/app/ent/cloudaccount"
	"github.com/spacefleet/app/ent/predicate"
)

// CloudAccountUpdate is the builder for updating CloudAccount entities.
type CloudAccountUpdate struct {
	config
	hooks    []Hook
	mutation *CloudAccountMutation
}

// Where appends a list predicates to the CloudAccountUpdate builder.
func (_u *CloudAccountUpdate) Where(ps ...predicate.CloudAccount) *CloudAccountUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOrgSlug sets the "org_slug" field.
func (_u *CloudAccountUpdate) SetOrgSlug(v string) *CloudAccountUpdate {
	_u.mutation.SetOrgSlug(v)
	return _u
}

// SetNillableOrgSlug sets the "org_slug" field if the given value is not nil.
func (_u *CloudAccountUpdate) SetNillableOrgSlug(v *string) *CloudAccountUpdate {
	if v != nil {
		_u.SetOrgSlug(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *CloudAccountUpdate) SetProvider(v string) *CloudAccountUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *CloudAccountUpdate) SetNillableProvider(v *string) *CloudAccountUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetLabel sets the "label" field.
func (_u *CloudAccountUpdate) SetLabel(v string) *CloudAccountUpdate {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *CloudAccountUpdate) SetNillableLabel(v *string) *CloudAccountUpdate {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *CloudAccountUpdate) SetAccountID(v string) *CloudAccountUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *CloudAccountUpdate) SetNillableAccountID(v *string) *CloudAccountUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// ClearAccountID clears the value of the "account_id" field.
func (_u *CloudAccountUpdate) ClearAccountID() *CloudAccountUpdate {
	_u.mutation.ClearAccountID()
	return _u
}

// SetRoleArn sets the "role_arn" field.
func (_u *CloudAccountUpdate) SetRoleArn(v string) *CloudAccountUpdate {
	_u.mutation.SetRoleArn(v)
	return _u
}

// SetNillableRoleArn sets the "role_arn" field if the given value is not nil.
func (_u *CloudAccountUpdate) SetNillableRoleArn(v *string) *CloudAccountUpdate {
	if v != nil {
		_u.SetRoleArn(*v)
	}
	return _u
}

// ClearRoleArn clears the value of the "role_arn" field.
func (_u *CloudAccountUpdate) ClearRoleArn() *CloudAccountUpdate {
	_u.mutation.ClearRoleArn()
	return _u
}

// SetExternalID sets the "external_id" field.
func (_u *CloudAccountUpdate) SetExternalID(v string) *CloudAccountUpdate {
	_u.mutation.SetExternalID(v)
	return _u
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_u *CloudAccountUpdate) SetNillableExternalID(v *string) *CloudAccountUpdate {
	if v != nil {
		_u.SetExternalID(*v)
	}
	return _u
}

// SetRegion sets the "region" field.
func (_u *CloudAccountUpdate) SetRegion(v string) *CloudAccountUpdate {
	_u.mutation.SetRegion(v)
	return _u
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_u *CloudAccountUpdate) SetNillableRegion(v *string) *CloudAccountUpdate {
	if v != nil {
		_u.SetRegion(*v)
	}
	return _u
}

// ClearRegion clears the value of the "region" field.
func (_u *CloudAccountUpdate) ClearRegion() *CloudAccountUpdate {
	_u.mutation.ClearRegion()
	return _u
}

// SetStatus sets the "status" field.
func (_u *CloudAccountUpdate) SetStatus(v string) *CloudAccountUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CloudAccountUpdate) SetNillableStatus(v *string) *CloudAccountUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLastVerifiedAt sets the "last_verified_at" field.
func (_u *CloudAccountUpdate) SetLastVerifiedAt(v time.Time) *CloudAccountUpdate {
	_u.mutation.SetLastVerifiedAt(v)
	return _u
}

// SetNillableLastVerifiedAt sets the "last_verified_at" field if the given value is not nil.
func (_u *CloudAccountUpdate) SetNillableLastVerifiedAt(v *time.Time) *CloudAccountUpdate {
	if v != nil {
		_u.SetLastVerifiedAt(*v)
	}
	return _u
}

// ClearLastVerifiedAt clears the value of the "last_verified_at" field.
func (_u *CloudAccountUpdate) ClearLastVerifiedAt() *CloudAccountUpdate {
	_u.mutation.ClearLastVerifiedAt()
	return _u
}

// SetLastVerificationError sets the "last_verification_error" field.
func (_u *CloudAccountUpdate) SetLastVerificationError(v string) *CloudAccountUpdate {
	_u.mutation.SetLastVerificationError(v)
	return _u
}

// SetNillableLastVerificationError sets the "last_verification_error" field if the given value is not nil.
func (_u *CloudAccountUpdate) SetNillableLastVerificationError(v *string) *CloudAccountUpdate {
	if v != nil {
		_u.SetLastVerificationError(*v)
	}
	return _u
}

// ClearLastVerificationError clears the value of the "last_verification_error" field.
func (_u *CloudAccountUpdate) ClearLastVerificationError() *CloudAccountUpdate {
	_u.mutation.ClearLastVerificationError()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CloudAccountUpdate) SetUpdatedAt(v time.Time) *CloudAccountUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the CloudAccountMutation object of the builder.
func (_u *CloudAccountUpdate) Mutation() *CloudAccountMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CloudAccountUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CloudAccountUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CloudAccountUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CloudAccountUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CloudAccountUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := cloudaccount.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CloudAccountUpdate) check() error {
	if v, ok := _u.mutation.OrgSlug(); ok {
		if err := cloudaccount.OrgSlugValidator(v); err != nil {
			return &ValidationError{Name: "org_slug", err: fmt.Errorf(`ent: validator failed for field "CloudAccount.org_slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := cloudaccount.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "CloudAccount.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Label(); ok {
		if err := cloudaccount.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "CloudAccount.label": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExternalID(); ok {
		if err := cloudaccount.ExternalIDValidator(v); err != nil {
			return &ValidationError{Name: "external_id", err: fmt.Errorf(`ent: validator failed for field "CloudAccount.external_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := cloudaccount.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CloudAccount.status": %w`, err)}
		}
	}
	return nil
}

func (_u *CloudAccountUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(cloudaccount.Table, cloudaccount.Columns, sqlgraph.NewFieldSpec(cloudaccount.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrgSlug(); ok {
		_spec.SetField(cloudaccount.FieldOrgSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(cloudaccount.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(cloudaccount.FieldLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(cloudaccount.FieldAccountID, field.TypeString, value)
	}
	if _u.mutation.AccountIDCleared() {
		_spec.ClearField(cloudaccount.FieldAccountID, field.TypeString)
	}
	if value, ok := _u.mutation.RoleArn(); ok {
		_spec.SetField(cloudaccount.FieldRoleArn, field.TypeString, value)
	}
	if _u.mutation.RoleArnCleared() {
		_spec.ClearField(cloudaccount.FieldRoleArn, field.TypeString)
	}
	if value, ok := _u.mutation.ExternalID(); ok {
		_spec.SetField(cloudaccount.FieldExternalID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Region(); ok {
		_spec.SetField(cloudaccount.FieldRegion, field.TypeString, value)
	}
	if _u.mutation.RegionCleared() {
		_spec.ClearField(cloudaccount.FieldRegion, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(cloudaccount.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastVerifiedAt(); ok {
		_spec.SetField(cloudaccount.FieldLastVerifiedAt, field.TypeTime, value)
	}
	if _u.mutation.LastVerifiedAtCleared() {
		_spec.ClearField(cloudaccount.FieldLastVerifiedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastVerificationError(); ok {
		_spec.SetField(cloudaccount.FieldLastVerificationError, field.TypeString, value)
	}
	if _u.mutation.LastVerificationErrorCleared() {
		_spec.ClearField(cloudaccount.FieldLastVerificationError, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(cloudaccount.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cloudaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CloudAccountUpdateOne is the builder for updating a single CloudAccount entity.
type CloudAccountUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CloudAccountMutation
}

// SetOrgSlug sets the "org_slug" field.
func (_u *CloudAccountUpdateOne) SetOrgSlug(v string) *CloudAccountUpdateOne {
	_u.mutation.SetOrgSlug(v)
	return _u
}

// SetNillableOrgSlug sets the "org_slug" field if the given value is not nil.
func (_u *CloudAccountUpdateOne) SetNillableOrgSlug(v *string) *CloudAccountUpdateOne {
	if v != nil {
		_u.SetOrgSlug(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *CloudAccountUpdateOne) SetProvider(v string) *CloudAccountUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *CloudAccountUpdateOne) SetNillableProvider(v *string) *CloudAccountUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetLabel sets the "label" field.
func (_u *CloudAccountUpdateOne) SetLabel(v string) *CloudAccountUpdateOne {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *CloudAccountUpdateOne) SetNillableLabel(v *string) *CloudAccountUpdateOne {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *CloudAccountUpdateOne) SetAccountID(v string) *CloudAccountUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *CloudAccountUpdateOne) SetNillableAccountID(v *string) *CloudAccountUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// ClearAccountID clears the value of the "account_id" field.
func (_u *CloudAccountUpdateOne) ClearAccountID() *CloudAccountUpdateOne {
	_u.mutation.ClearAccountID()
	return _u
}

// SetRoleArn sets the "role_arn" field.
func (_u *CloudAccountUpdateOne) SetRoleArn(v string) *CloudAccountUpdateOne {
	_u.mutation.SetRoleArn(v)
	return _u
}

// SetNillableRoleArn sets the "role_arn" field if the given value is not nil.
func (_u *CloudAccountUpdateOne) SetNillableRoleArn(v *string) *CloudAccountUpdateOne {
	if v != nil {
		_u.SetRoleArn(*v)
	}
	return _u
}

// ClearRoleArn clears the value of the "role_arn" field.
func (_u *CloudAccountUpdateOne) ClearRoleArn() *CloudAccountUpdateOne {
	_u.mutation.ClearRoleArn()
	return _u
}

// SetExternalID sets the "external_id" field.
func (_u *CloudAccountUpdateOne) SetExternalID(v string) *CloudAccountUpdateOne {
	_u.mutation.SetExternalID(v)
	return _u
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_u *CloudAccountUpdateOne) SetNillableExternalID(v *string) *CloudAccountUpdateOne {
	if v != nil {
		_u.SetExternalID(*v)
	}
	return _u
}

// SetRegion sets the "region" field.
func (_u *CloudAccountUpdateOne) SetRegion(v string) *CloudAccountUpdateOne {
	_u.mutation.SetRegion(v)
	return _u
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_u *CloudAccountUpdateOne) SetNillableRegion(v *string) *CloudAccountUpdateOne {
	if v != nil {
		_u.SetRegion(*v)
	}
	return _u
}

// ClearRegion clears the value of the "region" field.
func (_u *CloudAccountUpdateOne) ClearRegion() *CloudAccountUpdateOne {
	_u.mutation.ClearRegion()
	return _u
}

// SetStatus sets the "status" field.
func (_u *CloudAccountUpdateOne) SetStatus(v string) *CloudAccountUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CloudAccountUpdateOne) SetNillableStatus(v *string) *CloudAccountUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLastVerifiedAt sets the "last_verified_at" field.
func (_u *CloudAccountUpdateOne) SetLastVerifiedAt(v time.Time) *CloudAccountUpdateOne {
	_u.mutation.SetLastVerifiedAt(v)
	return _u
}

// SetNillableLastVerifiedAt sets the "last_verified_at" field if the given value is not nil.
func (_u *CloudAccountUpdateOne) SetNillableLastVerifiedAt(v *time.Time) *CloudAccountUpdateOne {
	if v != nil {
		_u.SetLastVerifiedAt(*v)
	}
	return _u
}

// ClearLastVerifiedAt clears the value of the "last_verified_at" field.
func (_u *CloudAccountUpdateOne) ClearLastVerifiedAt() *CloudAccountUpdateOne {
	_u.mutation.ClearLastVerifiedAt()
	return _u
}

// SetLastVerificationError sets the "last_verification_error" field.
func (_u *CloudAccountUpdateOne) SetLastVerificationError(v string) *CloudAccountUpdateOne {
	_u.mutation.SetLastVerificationError(v)
	return _u
}

// SetNillableLastVerificationError sets the "last_verification_error" field if the given value is not nil.
func (_u *CloudAccountUpdateOne) SetNillableLastVerificationError(v *string) *CloudAccountUpdateOne {
	if v != nil {
		_u.SetLastVerificationError(*v)
	}
	return _u
}

// ClearLastVerificationError clears the value of the "last_verification_error" field.
func (_u *CloudAccountUpdateOne) ClearLastVerificationError() *CloudAccountUpdateOne {
	_u.mutation.ClearLastVerificationError()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CloudAccountUpdateOne) SetUpdatedAt(v time.Time) *CloudAccountUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the CloudAccountMutation object of the builder.
func (_u *CloudAccountUpdateOne) Mutation() *CloudAccountMutation {
	return _u.mutation
}

// Where appends a list predicates to the CloudAccountUpdate builder.
func (_u *CloudAccountUpdateOne) Where(ps ...predicate.CloudAccount) *CloudAccountUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CloudAccountUpdateOne) Select(field string, fields ...string) *CloudAccountUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CloudAccount entity.
func (_u *CloudAccountUpdateOne) Save(ctx context.Context) (*CloudAccount, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CloudAccountUpdateOne) SaveX(ctx context.Context) *CloudAccount {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CloudAccountUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CloudAccountUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CloudAccountUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := cloudaccount.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CloudAccountUpdateOne) check() error {
	if v, ok := _u.mutation.OrgSlug(); ok {
		if err := cloudaccount.OrgSlugValidator(v); err != nil {
			return &ValidationError{Name: "org_slug", err: fmt.Errorf(`ent: validator failed for field "CloudAccount.org_slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := cloudaccount.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "CloudAccount.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Label(); ok {
		if err := cloudaccount.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "CloudAccount.label": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExternalID(); ok {
		if err := cloudaccount.ExternalIDValidator(v); err != nil {
			return &ValidationError{Name: "external_id", err: fmt.Errorf(`ent: validator failed for field "CloudAccount.external_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := cloudaccount.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CloudAccount.status": %w`, err)}
		}
	}
	return nil
}

func (_u *CloudAccountUpdateOne) sqlSave(ctx context.Context) (_node *CloudAccount, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(cloudaccount.Table, cloudaccount.Columns, sqlgraph.NewFieldSpec(cloudaccount.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CloudAccount.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cloudaccount.FieldID)
		for _, f := range fields {
			if !cloudaccount.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != cloudaccount.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrgSlug(); ok {
		_spec.SetField(cloudaccount.FieldOrgSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(cloudaccount.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(cloudaccount.FieldLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(cloudaccount.FieldAccountID, field.TypeString, value)
	}
	if _u.mutation.AccountIDCleared() {
		_spec.ClearField(cloudaccount.FieldAccountID, field.TypeString)
	}
	if value, ok := _u.mutation.RoleArn(); ok {
		_spec.SetField(cloudaccount.FieldRoleArn, field.TypeString, value)
	}
	if _u.mutation.RoleArnCleared() {
		_spec.ClearField(cloudaccount.FieldRoleArn, field.TypeString)
	}
	if value, ok := _u.mutation.ExternalID(); ok {
		_spec.SetField(cloudaccount.FieldExternalID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Region(); ok {
		_spec.SetField(cloudaccount.FieldRegion, field.TypeString, value)
	}
	if _u.mutation.RegionCleared() {
		_spec.ClearField(cloudaccount.FieldRegion, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(cloudaccount.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastVerifiedAt(); ok {
		_spec.SetField(cloudaccount.FieldLastVerifiedAt, field.TypeTime, value)
	}
	if _u.mutation.LastVerifiedAtCleared() {
		_spec.ClearField(cloudaccount.FieldLastVerifiedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastVerificationError(); ok {
		_spec.SetField(cloudaccount.FieldLastVerificationError, field.TypeString, value)
	}
	if _u.mutation.LastVerificationErrorCleared() {
		_spec.ClearField(cloudaccount.FieldLastVerificationError, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(cloudaccount.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &CloudAccount{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cloudaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
