// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/spacefleet/app/ent/cloudaccount"
)

// CloudAccountCreate is the builder for creating a CloudAccount entity.
type CloudAccountCreate struct {
	config
	mutation *CloudAccountMutation
	hooks    []Hook
}

// SetOrgSlug sets the "org_slug" field.
func (_c *CloudAccountCreate) SetOrgSlug(v string) *CloudAccountCreate {
	_c.mutation.SetOrgSlug(v)
	return _c
}

// SetProvider sets the "provider" field.
func (_c *CloudAccountCreate) SetProvider(v string) *CloudAccountCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_c *CloudAccountCreate) SetNillableProvider(v *string) *CloudAccountCreate {
	if v != nil {
		_c.SetProvider(*v)
	}
	return _c
}

// SetLabel sets the "label" field.
func (_c *CloudAccountCreate) SetLabel(v string) *CloudAccountCreate {
	_c.mutation.SetLabel(v)
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *CloudAccountCreate) SetAccountID(v string) *CloudAccountCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_c *CloudAccountCreate) SetNillableAccountID(v *string) *CloudAccountCreate {
	if v != nil {
		_c.SetAccountID(*v)
	}
	return _c
}

// SetRoleArn sets the "role_arn" field.
func (_c *CloudAccountCreate) SetRoleArn(v string) *CloudAccountCreate {
	_c.mutation.SetRoleArn(v)
	return _c
}

// SetNillableRoleArn sets the "role_arn" field if the given value is not nil.
func (_c *CloudAccountCreate) SetNillableRoleArn(v *string) *CloudAccountCreate {
	if v != nil {
		_c.SetRoleArn(*v)
	}
	return _c
}

// SetExternalID sets the "external_id" field.
func (_c *CloudAccountCreate) SetExternalID(v string) *CloudAccountCreate {
	_c.mutation.SetExternalID(v)
	return _c
}

// SetRegion sets the "region" field.
func (_c *CloudAccountCreate) SetRegion(v string) *CloudAccountCreate {
	_c.mutation.SetRegion(v)
	return _c
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_c *CloudAccountCreate) SetNillableRegion(v *string) *CloudAccountCreate {
	if v != nil {
		_c.SetRegion(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *CloudAccountCreate) SetStatus(v string) *CloudAccountCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *CloudAccountCreate) SetNillableStatus(v *string) *CloudAccountCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetLastVerifiedAt sets the "last_verified_at" field.
func (_c *CloudAccountCreate) SetLastVerifiedAt(v time.Time) *CloudAccountCreate {
	_c.mutation.SetLastVerifiedAt(v)
	return _c
}

// SetNillableLastVerifiedAt sets the "last_verified_at" field if the given value is not nil.
func (_c *CloudAccountCreate) SetNillableLastVerifiedAt(v *time.Time) *CloudAccountCreate {
	if v != nil {
		_c.SetLastVerifiedAt(*v)
	}
	return _c
}

// SetLastVerificationError sets the "last_verification_error" field.
func (_c *CloudAccountCreate) SetLastVerificationError(v string) *CloudAccountCreate {
	_c.mutation.SetLastVerificationError(v)
	return _c
}

// SetNillableLastVerificationError sets the "last_verification_error" field if the given value is not nil.
func (_c *CloudAccountCreate) SetNillableLastVerificationError(v *string) *CloudAccountCreate {
	if v != nil {
		_c.SetLastVerificationError(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CloudAccountCreate) SetCreatedAt(v time.Time) *CloudAccountCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CloudAccountCreate) SetNillableCreatedAt(v *time.Time) *CloudAccountCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CloudAccountCreate) SetUpdatedAt(v time.Time) *CloudAccountCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CloudAccountCreate) SetNillableUpdatedAt(v *time.Time) *CloudAccountCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CloudAccountCreate) SetID(v uuid.UUID) *CloudAccountCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *CloudAccountCreate) SetNillableID(v *uuid.UUID) *CloudAccountCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the CloudAccountMutation object of the builder.
func (_c *CloudAccountCreate) Mutation() *CloudAccountMutation {
	return _c.mutation
}

// Save creates the CloudAccount in the database.
func (_c *CloudAccountCreate) Save(ctx context.Context) (*CloudAccount, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CloudAccountCreate) SaveX(ctx context.Context) *CloudAccount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CloudAccountCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CloudAccountCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CloudAccountCreate) defaults() {
	if _, ok := _c.mutation.Provider(); !ok {
		v := cloudaccount.DefaultProvider
		_c.mutation.SetProvider(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := cloudaccount.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := cloudaccount.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := cloudaccount.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := cloudaccount.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CloudAccountCreate) check() error {
	if _, ok := _c.mutation.OrgSlug(); !ok {
		return &ValidationError{Name: "org_slug", err: errors.New(`ent: missing required field "CloudAccount.org_slug"`)}
	}
	if v, ok := _c.mutation.OrgSlug(); ok {
		if err := cloudaccount.OrgSlugValidator(v); err != nil {
			return &ValidationError{Name: "org_slug", err: fmt.Errorf(`ent: validator failed for field "CloudAccount.org_slug": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "CloudAccount.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := cloudaccount.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "CloudAccount.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Label(); !ok {
		return &ValidationError{Name: "label", err: errors.New(`ent: missing required field "CloudAccount.label"`)}
	}
	if v, ok := _c.mutation.Label(); ok {
		if err := cloudaccount.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "CloudAccount.label": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExternalID(); !ok {
		return &ValidationError{Name: "external_id", err: errors.New(`ent: missing required field "CloudAccount.external_id"`)}
	}
	if v, ok := _c.mutation.ExternalID(); ok {
		if err := cloudaccount.ExternalIDValidator(v); err != nil {
			return &ValidationError{Name: "external_id", err: fmt.Errorf(`ent: validator failed for field "CloudAccount.external_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "CloudAccount.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := cloudaccount.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CloudAccount.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CloudAccount.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CloudAccount.updated_at"`)}
	}
	return nil
}

func (_c *CloudAccountCreate) sqlSave(ctx context.Context) (*CloudAccount, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CloudAccountCreate) createSpec() (*CloudAccount, *sqlgraph.CreateSpec) {
	var (
		_node = &CloudAccount{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(cloudaccount.Table, sqlgraph.NewFieldSpec(cloudaccount.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.OrgSlug(); ok {
		_spec.SetField(cloudaccount.FieldOrgSlug, field.TypeString, value)
		_node.OrgSlug = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(cloudaccount.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.Label(); ok {
		_spec.SetField(cloudaccount.FieldLabel, field.TypeString, value)
		_node.Label = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(cloudaccount.FieldAccountID, field.TypeString, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.RoleArn(); ok {
		_spec.SetField(cloudaccount.FieldRoleArn, field.TypeString, value)
		_node.RoleArn = value
	}
	if value, ok := _c.mutation.ExternalID(); ok {
		_spec.SetField(cloudaccount.FieldExternalID, field.TypeString, value)
		_node.ExternalID = value
	}
	if value, ok := _c.mutation.Region(); ok {
		_spec.SetField(cloudaccount.FieldRegion, field.TypeString, value)
		_node.Region = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(cloudaccount.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.LastVerifiedAt(); ok {
		_spec.SetField(cloudaccount.FieldLastVerifiedAt, field.TypeTime, value)
		_node.LastVerifiedAt = &value
	}
	if value, ok := _c.mutation.LastVerificationError(); ok {
		_spec.SetField(cloudaccount.FieldLastVerificationError, field.TypeString, value)
		_node.LastVerificationError = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(cloudaccount.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(cloudaccount.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// CloudAccountCreateBulk is the builder for creating many CloudAccount entities in bulk.
type CloudAccountCreateBulk struct {
	config
	err      error
	builders []*CloudAccountCreate
}

// Save creates the CloudAccount entities in the database.
func (_c *CloudAccountCreateBulk) Save(ctx context.Context) ([]*CloudAccount, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CloudAccount, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CloudAccountMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CloudAccountCreateBulk) SaveX(ctx context.Context) []*CloudAccount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CloudAccountCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CloudAccountCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
