// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/spacefleet/app/ent/cloudaccount"
)

// CloudAccount is the model entity for the CloudAccount schema.
type CloudAccount struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// OrgSlug holds the value of the "org_slug" field.
	OrgSlug string `json:"org_slug,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// Label holds the value of the "label" field.
	Label string `json:"label,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID string `json:"account_id,omitempty"`
	// RoleArn holds the value of the "role_arn" field.
	RoleArn string `json:"role_arn,omitempty"`
	// ExternalID holds the value of the "external_id" field.
	ExternalID string `json:"-"`
	// Region holds the value of the "region" field.
	Region string `json:"region,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// LastVerifiedAt holds the value of the "last_verified_at" field.
	LastVerifiedAt *time.Time `json:"last_verified_at,omitempty"`
	// LastVerificationError holds the value of the "last_verification_error" field.
	LastVerificationError string `json:"last_verification_error,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CloudAccount) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case cloudaccount.FieldOrgSlug, cloudaccount.FieldProvider, cloudaccount.FieldLabel, cloudaccount.FieldAccountID, cloudaccount.FieldRoleArn, cloudaccount.FieldExternalID, cloudaccount.FieldRegion, cloudaccount.FieldStatus, cloudaccount.FieldLastVerificationError:
			values[i] = new(sql.NullString)
		case cloudaccount.FieldLastVerifiedAt, cloudaccount.FieldCreatedAt, cloudaccount.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case cloudaccount.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CloudAccount fields.
func (_m *CloudAccount) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case cloudaccount.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case cloudaccount.FieldOrgSlug:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field org_slug", values[i])
			} else if value.Valid {
				_m.OrgSlug = value.String
			}
		case cloudaccount.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case cloudaccount.FieldLabel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field label", values[i])
			} else if value.Valid {
				_m.Label = value.String
			}
		case cloudaccount.FieldAccountID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.String
			}
		case cloudaccount.FieldRoleArn:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role_arn", values[i])
			} else if value.Valid {
				_m.RoleArn = value.String
			}
		case cloudaccount.FieldExternalID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field external_id", values[i])
			} else if value.Valid {
				_m.ExternalID = value.String
			}
		case cloudaccount.FieldRegion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field region", values[i])
			} else if value.Valid {
				_m.Region = value.String
			}
		case cloudaccount.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case cloudaccount.FieldLastVerifiedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_verified_at", values[i])
			} else if value.Valid {
				_m.LastVerifiedAt = new(time.Time)
				*_m.LastVerifiedAt = value.Time
			}
		case cloudaccount.FieldLastVerificationError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_verification_error", values[i])
			} else if value.Valid {
				_m.LastVerificationError = value.String
			}
		case cloudaccount.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case cloudaccount.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CloudAccount.
// This includes values selected through modifiers, order, etc.
func (_m *CloudAccount) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CloudAccount.
// Note that you need to call CloudAccount.Unwrap() before calling this method if this CloudAccount
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CloudAccount) Update() *CloudAccountUpdateOne {
	return NewCloudAccountClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CloudAccount entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CloudAccount) Unwrap() *CloudAccount {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CloudAccount is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CloudAccount) String() string {
	var builder strings.Builder
	builder.WriteString("CloudAccount(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("org_slug=")
	builder.WriteString(_m.OrgSlug)
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("label=")
	builder.WriteString(_m.Label)
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(_m.AccountID)
	builder.WriteString(", ")
	builder.WriteString("role_arn=")
	builder.WriteString(_m.RoleArn)
	builder.WriteString(", ")
	builder.WriteString("external_id=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("region=")
	builder.WriteString(_m.Region)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.LastVerifiedAt; v != nil {
		builder.WriteString("last_verified_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("last_verification_error=")
	builder.WriteString(_m.LastVerificationError)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CloudAccounts is a parsable slice of CloudAccount.
type CloudAccounts []*CloudAccount
