// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/spacefleet/app/ent/githubinstallstate"
)

// GithubInstallState is the model entity for the GithubInstallState schema.
type GithubInstallState struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// StateHash holds the value of the "state_hash" field.
	StateHash []byte `json:"state_hash,omitempty"`
	// OrgSlug holds the value of the "org_slug" field.
	OrgSlug string `json:"org_slug,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID string `json:"user_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// ConsumedAt holds the value of the "consumed_at" field.
	ConsumedAt   *time.Time `json:"consumed_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GithubInstallState) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case githubinstallstate.FieldStateHash:
			values[i] = new([]byte)
		case githubinstallstate.FieldOrgSlug, githubinstallstate.FieldUserID:
			values[i] = new(sql.NullString)
		case githubinstallstate.FieldCreatedAt, githubinstallstate.FieldExpiresAt, githubinstallstate.FieldConsumedAt:
			values[i] = new(sql.NullTime)
		case githubinstallstate.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GithubInstallState fields.
func (_m *GithubInstallState) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case githubinstallstate.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case githubinstallstate.FieldStateHash:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field state_hash", values[i])
			} else if value != nil {
				_m.StateHash = *value
			}
		case githubinstallstate.FieldOrgSlug:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field org_slug", values[i])
			} else if value.Valid {
				_m.OrgSlug = value.String
			}
		case githubinstallstate.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.String
			}
		case githubinstallstate.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case githubinstallstate.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case githubinstallstate.FieldConsumedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field consumed_at", values[i])
			} else if value.Valid {
				_m.ConsumedAt = new(time.Time)
				*_m.ConsumedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GithubInstallState.
// This includes values selected through modifiers, order, etc.
func (_m *GithubInstallState) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this GithubInstallState.
// Note that you need to call GithubInstallState.Unwrap() before calling this method if this GithubInstallState
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GithubInstallState) Update() *GithubInstallStateUpdateOne {
	return NewGithubInstallStateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GithubInstallState entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GithubInstallState) Unwrap() *GithubInstallState {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GithubInstallState is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GithubInstallState) String() string {
	var builder strings.Builder
	builder.WriteString("GithubInstallState(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("state_hash=")
	builder.WriteString(fmt.Sprintf("%v", _m.StateHash))
	builder.WriteString(", ")
	builder.WriteString("org_slug=")
	builder.WriteString(_m.OrgSlug)
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(_m.UserID)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ConsumedAt; v != nil {
		builder.WriteString("consumed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// GithubInstallStates is a parsable slice of GithubInstallState.
type GithubInstallStates []*GithubInstallState
