// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/spacefleet/app/ent/githubinstallation"
)

// GithubInstallationCreate is the builder for creating a GithubInstallation entity.
type GithubInstallationCreate struct {
	config
	mutation *GithubInstallationMutation
	hooks    []Hook
}

// SetOrgSlug sets the "org_slug" field.
func (_c *GithubInstallationCreate) SetOrgSlug(v string) *GithubInstallationCreate {
	_c.mutation.SetOrgSlug(v)
	return _c
}

// SetInstallationID sets the "installation_id" field.
func (_c *GithubInstallationCreate) SetInstallationID(v int64) *GithubInstallationCreate {
	_c.mutation.SetInstallationID(v)
	return _c
}

// SetAccountLogin sets the "account_login" field.
func (_c *GithubInstallationCreate) SetAccountLogin(v string) *GithubInstallationCreate {
	_c.mutation.SetAccountLogin(v)
	return _c
}

// SetAccountType sets the "account_type" field.
func (_c *GithubInstallationCreate) SetAccountType(v string) *GithubInstallationCreate {
	_c.mutation.SetAccountType(v)
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *GithubInstallationCreate) SetAccountID(v int64) *GithubInstallationCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *GithubInstallationCreate) SetCreatedAt(v time.Time) *GithubInstallationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GithubInstallationCreate) SetNillableCreatedAt(v *time.Time) *GithubInstallationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *GithubInstallationCreate) SetUpdatedAt(v time.Time) *GithubInstallationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *GithubInstallationCreate) SetNillableUpdatedAt(v *time.Time) *GithubInstallationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetSuspendedAt sets the "suspended_at" field.
func (_c *GithubInstallationCreate) SetSuspendedAt(v time.Time) *GithubInstallationCreate {
	_c.mutation.SetSuspendedAt(v)
	return _c
}

// SetNillableSuspendedAt sets the "suspended_at" field if the given value is not nil.
func (_c *GithubInstallationCreate) SetNillableSuspendedAt(v *time.Time) *GithubInstallationCreate {
	if v != nil {
		_c.SetSuspendedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *GithubInstallationCreate) SetID(v uuid.UUID) *GithubInstallationCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *GithubInstallationCreate) SetNillableID(v *uuid.UUID) *GithubInstallationCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the GithubInstallationMutation object of the builder.
func (_c *GithubInstallationCreate) Mutation() *GithubInstallationMutation {
	return _c.mutation
}

// Save creates the GithubInstallation in the database.
func (_c *GithubInstallationCreate) Save(ctx context.Context) (*GithubInstallation, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GithubInstallationCreate) SaveX(ctx context.Context) *GithubInstallation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GithubInstallationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GithubInstallationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GithubInstallationCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := githubinstallation.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := githubinstallation.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := githubinstallation.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GithubInstallationCreate) check() error {
	if _, ok := _c.mutation.OrgSlug(); !ok {
		return &ValidationError{Name: "org_slug", err: errors.New(`ent: missing required field "GithubInstallation.org_slug"`)}
	}
	if v, ok := _c.mutation.OrgSlug(); ok {
		if err := githubinstallation.OrgSlugValidator(v); err != nil {
			return &ValidationError{Name: "org_slug", err: fmt.Errorf(`ent: validator failed for field "GithubInstallation.org_slug": %w`, err)}
		}
	}
	if _, ok := _c.mutation.InstallationID(); !ok {
		return &ValidationError{Name: "installation_id", err: errors.New(`ent: missing required field "GithubInstallation.installation_id"`)}
	}
	if _, ok := _c.mutation.AccountLogin(); !ok {
		return &ValidationError{Name: "account_login", err: errors.New(`ent: missing required field "GithubInstallation.account_login"`)}
	}
	if v, ok := _c.mutation.AccountLogin(); ok {
		if err := githubinstallation.AccountLoginValidator(v); err != nil {
			return &ValidationError{Name: "account_login", err: fmt.Errorf(`ent: validator failed for field "GithubInstallation.account_login": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AccountType(); !ok {
		return &ValidationError{Name: "account_type", err: errors.New(`ent: missing required field "GithubInstallation.account_type"`)}
	}
	if v, ok := _c.mutation.AccountType(); ok {
		if err := githubinstallation.AccountTypeValidator(v); err != nil {
			return &ValidationError{Name: "account_type", err: fmt.Errorf(`ent: validator failed for field "GithubInstallation.account_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "GithubInstallation.account_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "GithubInstallation.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "GithubInstallation.updated_at"`)}
	}
	return nil
}

func (_c *GithubInstallationCreate) sqlSave(ctx context.Context) (*GithubInstallation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GithubInstallationCreate) createSpec() (*GithubInstallation, *sqlgraph.CreateSpec) {
	var (
		_node = &GithubInstallation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(githubinstallation.Table, sqlgraph.NewFieldSpec(githubinstallation.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.OrgSlug(); ok {
		_spec.SetField(githubinstallation.FieldOrgSlug, field.TypeString, value)
		_node.OrgSlug = value
	}
	if value, ok := _c.mutation.InstallationID(); ok {
		_spec.SetField(githubinstallation.FieldInstallationID, field.TypeInt64, value)
		_node.InstallationID = value
	}
	if value, ok := _c.mutation.AccountLogin(); ok {
		_spec.SetField(githubinstallation.FieldAccountLogin, field.TypeString, value)
		_node.AccountLogin = value
	}
	if value, ok := _c.mutation.AccountType(); ok {
		_spec.SetField(githubinstallation.FieldAccountType, field.TypeString, value)
		_node.AccountType = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(githubinstallation.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(githubinstallation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(githubinstallation.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.SuspendedAt(); ok {
		_spec.SetField(githubinstallation.FieldSuspendedAt, field.TypeTime, value)
		_node.SuspendedAt = &value
	}
	return _node, _spec
}

// GithubInstallationCreateBulk is the builder for creating many GithubInstallation entities in bulk.
type GithubInstallationCreateBulk struct {
	config
	err      error
	builders []*GithubInstallationCreate
}

// Save creates the GithubInstallation entities in the database.
func (_c *GithubInstallationCreateBulk) Save(ctx context.Context) ([]*GithubInstallation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GithubInstallation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GithubInstallationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GithubInstallationCreateBulk) SaveX(ctx context.Context) []*GithubInstallation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GithubInstallationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GithubInstallationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
