// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/spacefleet/app/ent/app"
	"github.com/spacefleet/app/ent/build"
	"github.com/spacefleet/app/ent/cliauthcode"
	"github.com/spacefleet/app/ent/clitoken"
	"github.com/spacefleet/app/ent/cloudaccount"
	"github.com/spacefleet/app/ent/githubinstallation"
	"github.com/spacefleet/app/ent/githubinstallstate"
	"github.com/spacefleet/app/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	appFields := schema.App{}.Fields()
	_ = appFields
	// appDescOrgSlug is the schema descriptor for org_slug field.
	appDescOrgSlug := appFields[1].Descriptor()
	// app.OrgSlugValidator is a validator for the "org_slug" field. It is called by the builders before save.
	app.OrgSlugValidator = appDescOrgSlug.Validators[0].(func(string) error)
	// appDescName is the schema descriptor for name field.
	appDescName := appFields[2].Descriptor()
	// app.NameValidator is a validator for the "name" field. It is called by the builders before save.
	app.NameValidator = func() func(string) error {
		validators := appDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// appDescSlug is the schema descriptor for slug field.
	appDescSlug := appFields[3].Descriptor()
	// app.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	app.SlugValidator = func() func(string) error {
		validators := appDescSlug.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(slug string) error {
			for _, fn := range fns {
				if err := fn(slug); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// appDescGithubRepoFullName is the schema descriptor for github_repo_full_name field.
	appDescGithubRepoFullName := appFields[6].Descriptor()
	// app.GithubRepoFullNameValidator is a validator for the "github_repo_full_name" field. It is called by the builders before save.
	app.GithubRepoFullNameValidator = appDescGithubRepoFullName.Validators[0].(func(string) error)
	// appDescDefaultBranch is the schema descriptor for default_branch field.
	appDescDefaultBranch := appFields[7].Descriptor()
	// app.DefaultBranchValidator is a validator for the "default_branch" field. It is called by the builders before save.
	app.DefaultBranchValidator = appDescDefaultBranch.Validators[0].(func(string) error)
	// appDescCreatedBy is the schema descriptor for created_by field.
	appDescCreatedBy := appFields[8].Descriptor()
	// app.CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	app.CreatedByValidator = appDescCreatedBy.Validators[0].(func(string) error)
	// appDescCreatedAt is the schema descriptor for created_at field.
	appDescCreatedAt := appFields[10].Descriptor()
	// app.DefaultCreatedAt holds the default value on creation for the created_at field.
	app.DefaultCreatedAt = appDescCreatedAt.Default.(func() time.Time)
	// appDescUpdatedAt is the schema descriptor for updated_at field.
	appDescUpdatedAt := appFields[11].Descriptor()
	// app.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	app.DefaultUpdatedAt = appDescUpdatedAt.Default.(func() time.Time)
	// app.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	app.UpdateDefaultUpdatedAt = appDescUpdatedAt.UpdateDefault.(func() time.Time)
	// appDescID is the schema descriptor for id field.
	appDescID := appFields[0].Descriptor()
	// app.DefaultID holds the default value on creation for the id field.
	app.DefaultID = appDescID.Default.(func() uuid.UUID)
	buildFields := schema.Build{}.Fields()
	_ = buildFields
	// buildDescSourceRef is the schema descriptor for source_ref field.
	buildDescSourceRef := buildFields[2].Descriptor()
	// build.SourceRefValidator is a validator for the "source_ref" field. It is called by the builders before save.
	build.SourceRefValidator = buildDescSourceRef.Validators[0].(func(string) error)
	// buildDescStatus is the schema descriptor for status field.
	buildDescStatus := buildFields[4].Descriptor()
	// build.DefaultStatus holds the default value on creation for the status field.
	build.DefaultStatus = buildDescStatus.Default.(string)
	// build.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	build.StatusValidator = buildDescStatus.Validators[0].(func(string) error)
	// buildDescStages is the schema descriptor for stages field.
	buildDescStages := buildFields[5].Descriptor()
	// build.DefaultStages holds the default value on creation for the stages field.
	build.DefaultStages = buildDescStages.Default.([]schema.StageEvent)
	// buildDescWebhookSecret is the schema descriptor for webhook_secret field.
	buildDescWebhookSecret := buildFields[11].Descriptor()
	// build.WebhookSecretValidator is a validator for the "webhook_secret" field. It is called by the builders before save.
	build.WebhookSecretValidator = buildDescWebhookSecret.Validators[0].(func(string) error)
	// buildDescCreatedBy is the schema descriptor for created_by field.
	buildDescCreatedBy := buildFields[13].Descriptor()
	// build.CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	build.CreatedByValidator = buildDescCreatedBy.Validators[0].(func(string) error)
	// buildDescCreatedAt is the schema descriptor for created_at field.
	buildDescCreatedAt := buildFields[14].Descriptor()
	// build.DefaultCreatedAt holds the default value on creation for the created_at field.
	build.DefaultCreatedAt = buildDescCreatedAt.Default.(func() time.Time)
	// buildDescID is the schema descriptor for id field.
	buildDescID := buildFields[0].Descriptor()
	// build.DefaultID holds the default value on creation for the id field.
	build.DefaultID = buildDescID.Default.(func() uuid.UUID)
	cliauthcodeFields := schema.CLIAuthCode{}.Fields()
	_ = cliauthcodeFields
	// cliauthcodeDescUserID is the schema descriptor for user_id field.
	cliauthcodeDescUserID := cliauthcodeFields[1].Descriptor()
	// cliauthcode.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	cliauthcode.UserIDValidator = cliauthcodeDescUserID.Validators[0].(func(string) error)
	// cliauthcodeDescCodeHash is the schema descriptor for code_hash field.
	cliauthcodeDescCodeHash := cliauthcodeFields[2].Descriptor()
	// cliauthcode.CodeHashValidator is a validator for the "code_hash" field. It is called by the builders before save.
	cliauthcode.CodeHashValidator = func() func([]byte) error {
		validators := cliauthcodeDescCodeHash.Validators
		fns := [...]func([]byte) error{
			validators[0].(func([]byte) error),
			validators[1].(func([]byte) error),
		}
		return func(code_hash []byte) error {
			for _, fn := range fns {
				if err := fn(code_hash); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// cliauthcodeDescChallenge is the schema descriptor for challenge field.
	cliauthcodeDescChallenge := cliauthcodeFields[3].Descriptor()
	// cliauthcode.ChallengeValidator is a validator for the "challenge" field. It is called by the builders before save.
	cliauthcode.ChallengeValidator = cliauthcodeDescChallenge.Validators[0].(func(string) error)
	// cliauthcodeDescName is the schema descriptor for name field.
	cliauthcodeDescName := cliauthcodeFields[4].Descriptor()
	// cliauthcode.NameValidator is a validator for the "name" field. It is called by the builders before save.
	cliauthcode.NameValidator = cliauthcodeDescName.Validators[0].(func(string) error)
	// cliauthcodeDescCreatedAt is the schema descriptor for created_at field.
	cliauthcodeDescCreatedAt := cliauthcodeFields[5].Descriptor()
	// cliauthcode.DefaultCreatedAt holds the default value on creation for the created_at field.
	cliauthcode.DefaultCreatedAt = cliauthcodeDescCreatedAt.Default.(func() time.Time)
	// cliauthcodeDescID is the schema descriptor for id field.
	cliauthcodeDescID := cliauthcodeFields[0].Descriptor()
	// cliauthcode.DefaultID holds the default value on creation for the id field.
	cliauthcode.DefaultID = cliauthcodeDescID.Default.(func() uuid.UUID)
	clitokenFields := schema.CLIToken{}.Fields()
	_ = clitokenFields
	// clitokenDescUserID is the schema descriptor for user_id field.
	clitokenDescUserID := clitokenFields[1].Descriptor()
	// clitoken.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	clitoken.UserIDValidator = clitokenDescUserID.Validators[0].(func(string) error)
	// clitokenDescTokenHash is the schema descriptor for token_hash field.
	clitokenDescTokenHash := clitokenFields[2].Descriptor()
	// clitoken.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	clitoken.TokenHashValidator = func() func([]byte) error {
		validators := clitokenDescTokenHash.Validators
		fns := [...]func([]byte) error{
			validators[0].(func([]byte) error),
			validators[1].(func([]byte) error),
		}
		return func(token_hash []byte) error {
			for _, fn := range fns {
				if err := fn(token_hash); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// clitokenDescName is the schema descriptor for name field.
	clitokenDescName := clitokenFields[3].Descriptor()
	// clitoken.NameValidator is a validator for the "name" field. It is called by the builders before save.
	clitoken.NameValidator = clitokenDescName.Validators[0].(func(string) error)
	// clitokenDescCreatedAt is the schema descriptor for created_at field.
	clitokenDescCreatedAt := clitokenFields[4].Descriptor()
	// clitoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	clitoken.DefaultCreatedAt = clitokenDescCreatedAt.Default.(func() time.Time)
	// clitokenDescID is the schema descriptor for id field.
	clitokenDescID := clitokenFields[0].Descriptor()
	// clitoken.DefaultID holds the default value on creation for the id field.
	clitoken.DefaultID = clitokenDescID.Default.(func() uuid.UUID)
	cloudaccountFields := schema.CloudAccount{}.Fields()
	_ = cloudaccountFields
	// cloudaccountDescOrgSlug is the schema descriptor for org_slug field.
	cloudaccountDescOrgSlug := cloudaccountFields[1].Descriptor()
	// cloudaccount.OrgSlugValidator is a validator for the "org_slug" field. It is called by the builders before save.
	cloudaccount.OrgSlugValidator = cloudaccountDescOrgSlug.Validators[0].(func(string) error)
	// cloudaccountDescProvider is the schema descriptor for provider field.
	cloudaccountDescProvider := cloudaccountFields[2].Descriptor()
	// cloudaccount.DefaultProvider holds the default value on creation for the provider field.
	cloudaccount.DefaultProvider = cloudaccountDescProvider.Default.(string)
	// cloudaccount.ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	cloudaccount.ProviderValidator = cloudaccountDescProvider.Validators[0].(func(string) error)
	// cloudaccountDescLabel is the schema descriptor for label field.
	cloudaccountDescLabel := cloudaccountFields[3].Descriptor()
	// cloudaccount.LabelValidator is a validator for the "label" field. It is called by the builders before save.
	cloudaccount.LabelValidator = cloudaccountDescLabel.Validators[0].(func(string) error)
	// cloudaccountDescExternalID is the schema descriptor for external_id field.
	cloudaccountDescExternalID := cloudaccountFields[6].Descriptor()
	// cloudaccount.ExternalIDValidator is a validator for the "external_id" field. It is called by the builders before save.
	cloudaccount.ExternalIDValidator = cloudaccountDescExternalID.Validators[0].(func(string) error)
	// cloudaccountDescStatus is the schema descriptor for status field.
	cloudaccountDescStatus := cloudaccountFields[8].Descriptor()
	// cloudaccount.DefaultStatus holds the default value on creation for the status field.
	cloudaccount.DefaultStatus = cloudaccountDescStatus.Default.(string)
	// cloudaccount.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	cloudaccount.StatusValidator = cloudaccountDescStatus.Validators[0].(func(string) error)
	// cloudaccountDescCreatedAt is the schema descriptor for created_at field.
	cloudaccountDescCreatedAt := cloudaccountFields[11].Descriptor()
	// cloudaccount.DefaultCreatedAt holds the default value on creation for the created_at field.
	cloudaccount.DefaultCreatedAt = cloudaccountDescCreatedAt.Default.(func() time.Time)
	// cloudaccountDescUpdatedAt is the schema descriptor for updated_at field.
	cloudaccountDescUpdatedAt := cloudaccountFields[12].Descriptor()
	// cloudaccount.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	cloudaccount.DefaultUpdatedAt = cloudaccountDescUpdatedAt.Default.(func() time.Time)
	// cloudaccount.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	cloudaccount.UpdateDefaultUpdatedAt = cloudaccountDescUpdatedAt.UpdateDefault.(func() time.Time)
	// cloudaccountDescID is the schema descriptor for id field.
	cloudaccountDescID := cloudaccountFields[0].Descriptor()
	// cloudaccount.DefaultID holds the default value on creation for the id field.
	cloudaccount.DefaultID = cloudaccountDescID.Default.(func() uuid.UUID)
	githubinstallstateFields := schema.GithubInstallState{}.Fields()
	_ = githubinstallstateFields
	// githubinstallstateDescStateHash is the schema descriptor for state_hash field.
	githubinstallstateDescStateHash := githubinstallstateFields[1].Descriptor()
	// githubinstallstate.StateHashValidator is a validator for the "state_hash" field. It is called by the builders before save.
	githubinstallstate.StateHashValidator = func() func([]byte) error {
		validators := githubinstallstateDescStateHash.Validators
		fns := [...]func([]byte) error{
			validators[0].(func([]byte) error),
			validators[1].(func([]byte) error),
		}
		return func(state_hash []byte) error {
			for _, fn := range fns {
				if err := fn(state_hash); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// githubinstallstateDescOrgSlug is the schema descriptor for org_slug field.
	githubinstallstateDescOrgSlug := githubinstallstateFields[2].Descriptor()
	// githubinstallstate.OrgSlugValidator is a validator for the "org_slug" field. It is called by the builders before save.
	githubinstallstate.OrgSlugValidator = githubinstallstateDescOrgSlug.Validators[0].(func(string) error)
	// githubinstallstateDescUserID is the schema descriptor for user_id field.
	githubinstallstateDescUserID := githubinstallstateFields[3].Descriptor()
	// githubinstallstate.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	githubinstallstate.UserIDValidator = githubinstallstateDescUserID.Validators[0].(func(string) error)
	// githubinstallstateDescCreatedAt is the schema descriptor for created_at field.
	githubinstallstateDescCreatedAt := githubinstallstateFields[4].Descriptor()
	// githubinstallstate.DefaultCreatedAt holds the default value on creation for the created_at field.
	githubinstallstate.DefaultCreatedAt = githubinstallstateDescCreatedAt.Default.(func() time.Time)
	// githubinstallstateDescID is the schema descriptor for id field.
	githubinstallstateDescID := githubinstallstateFields[0].Descriptor()
	// githubinstallstate.DefaultID holds the default value on creation for the id field.
	githubinstallstate.DefaultID = githubinstallstateDescID.Default.(func() uuid.UUID)
	githubinstallationFields := schema.GithubInstallation{}.Fields()
	_ = githubinstallationFields
	// githubinstallationDescOrgSlug is the schema descriptor for org_slug field.
	githubinstallationDescOrgSlug := githubinstallationFields[1].Descriptor()
	// githubinstallation.OrgSlugValidator is a validator for the "org_slug" field. It is called by the builders before save.
	githubinstallation.OrgSlugValidator = githubinstallationDescOrgSlug.Validators[0].(func(string) error)
	// githubinstallationDescAccountLogin is the schema descriptor for account_login field.
	githubinstallationDescAccountLogin := githubinstallationFields[3].Descriptor()
	// githubinstallation.AccountLoginValidator is a validator for the "account_login" field. It is called by the builders before save.
	githubinstallation.AccountLoginValidator = githubinstallationDescAccountLogin.Validators[0].(func(string) error)
	// githubinstallationDescAccountType is the schema descriptor for account_type field.
	githubinstallationDescAccountType := githubinstallationFields[4].Descriptor()
	// githubinstallation.AccountTypeValidator is a validator for the "account_type" field. It is called by the builders before save.
	githubinstallation.AccountTypeValidator = githubinstallationDescAccountType.Validators[0].(func(string) error)
	// githubinstallationDescCreatedAt is the schema descriptor for created_at field.
	githubinstallationDescCreatedAt := githubinstallationFields[6].Descriptor()
	// githubinstallation.DefaultCreatedAt holds the default value on creation for the created_at field.
	githubinstallation.DefaultCreatedAt = githubinstallationDescCreatedAt.Default.(func() time.Time)
	// githubinstallationDescUpdatedAt is the schema descriptor for updated_at field.
	githubinstallationDescUpdatedAt := githubinstallationFields[7].Descriptor()
	// githubinstallation.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	githubinstallation.DefaultUpdatedAt = githubinstallationDescUpdatedAt.Default.(func() time.Time)
	// githubinstallation.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	githubinstallation.UpdateDefaultUpdatedAt = githubinstallationDescUpdatedAt.UpdateDefault.(func() time.Time)
	// githubinstallationDescID is the schema descriptor for id field.
	githubinstallationDescID := githubinstallationFields[0].Descriptor()
	// githubinstallation.DefaultID holds the default value on creation for the id field.
	githubinstallation.DefaultID = githubinstallationDescID.Default.(func() uuid.UUID)
}
