// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/spacefleet/app/ent/cliauthcode"
	"github.com/spacefleet/app/ent/clitoken"
	"github.com/spacefleet/app/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	cliauthcodeFields := schema.CLIAuthCode{}.Fields()
	_ = cliauthcodeFields
	// cliauthcodeDescUserID is the schema descriptor for user_id field.
	cliauthcodeDescUserID := cliauthcodeFields[1].Descriptor()
	// cliauthcode.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	cliauthcode.UserIDValidator = cliauthcodeDescUserID.Validators[0].(func(string) error)
	// cliauthcodeDescCodeHash is the schema descriptor for code_hash field.
	cliauthcodeDescCodeHash := cliauthcodeFields[2].Descriptor()
	// cliauthcode.CodeHashValidator is a validator for the "code_hash" field. It is called by the builders before save.
	cliauthcode.CodeHashValidator = func() func([]byte) error {
		validators := cliauthcodeDescCodeHash.Validators
		fns := [...]func([]byte) error{
			validators[0].(func([]byte) error),
			validators[1].(func([]byte) error),
		}
		return func(code_hash []byte) error {
			for _, fn := range fns {
				if err := fn(code_hash); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// cliauthcodeDescChallenge is the schema descriptor for challenge field.
	cliauthcodeDescChallenge := cliauthcodeFields[3].Descriptor()
	// cliauthcode.ChallengeValidator is a validator for the "challenge" field. It is called by the builders before save.
	cliauthcode.ChallengeValidator = cliauthcodeDescChallenge.Validators[0].(func(string) error)
	// cliauthcodeDescName is the schema descriptor for name field.
	cliauthcodeDescName := cliauthcodeFields[4].Descriptor()
	// cliauthcode.NameValidator is a validator for the "name" field. It is called by the builders before save.
	cliauthcode.NameValidator = cliauthcodeDescName.Validators[0].(func(string) error)
	// cliauthcodeDescCreatedAt is the schema descriptor for created_at field.
	cliauthcodeDescCreatedAt := cliauthcodeFields[5].Descriptor()
	// cliauthcode.DefaultCreatedAt holds the default value on creation for the created_at field.
	cliauthcode.DefaultCreatedAt = cliauthcodeDescCreatedAt.Default.(func() time.Time)
	// cliauthcodeDescID is the schema descriptor for id field.
	cliauthcodeDescID := cliauthcodeFields[0].Descriptor()
	// cliauthcode.DefaultID holds the default value on creation for the id field.
	cliauthcode.DefaultID = cliauthcodeDescID.Default.(func() uuid.UUID)
	clitokenFields := schema.CLIToken{}.Fields()
	_ = clitokenFields
	// clitokenDescUserID is the schema descriptor for user_id field.
	clitokenDescUserID := clitokenFields[1].Descriptor()
	// clitoken.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	clitoken.UserIDValidator = clitokenDescUserID.Validators[0].(func(string) error)
	// clitokenDescTokenHash is the schema descriptor for token_hash field.
	clitokenDescTokenHash := clitokenFields[2].Descriptor()
	// clitoken.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	clitoken.TokenHashValidator = func() func([]byte) error {
		validators := clitokenDescTokenHash.Validators
		fns := [...]func([]byte) error{
			validators[0].(func([]byte) error),
			validators[1].(func([]byte) error),
		}
		return func(token_hash []byte) error {
			for _, fn := range fns {
				if err := fn(token_hash); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// clitokenDescName is the schema descriptor for name field.
	clitokenDescName := clitokenFields[3].Descriptor()
	// clitoken.NameValidator is a validator for the "name" field. It is called by the builders before save.
	clitoken.NameValidator = clitokenDescName.Validators[0].(func(string) error)
	// clitokenDescCreatedAt is the schema descriptor for created_at field.
	clitokenDescCreatedAt := clitokenFields[4].Descriptor()
	// clitoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	clitoken.DefaultCreatedAt = clitokenDescCreatedAt.Default.(func() time.Time)
	// clitokenDescID is the schema descriptor for id field.
	clitokenDescID := clitokenFields[0].Descriptor()
	// clitoken.DefaultID holds the default value on creation for the id field.
	clitoken.DefaultID = clitokenDescID.Default.(func() uuid.UUID)
}
