// Code generated by ent, DO NOT EDIT.

package app

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the app type in the database.
	Label = "app"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOrgSlug holds the string denoting the org_slug field in the database.
	FieldOrgSlug = "org_slug"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldSlug holds the string denoting the slug field in the database.
	FieldSlug = "slug"
	// FieldCloudAccountID holds the string denoting the cloud_account_id field in the database.
	FieldCloudAccountID = "cloud_account_id"
	// FieldGithubInstallationID holds the string denoting the github_installation_id field in the database.
	FieldGithubInstallationID = "github_installation_id"
	// FieldGithubRepoFullName holds the string denoting the github_repo_full_name field in the database.
	FieldGithubRepoFullName = "github_repo_full_name"
	// FieldDefaultBranch holds the string denoting the default_branch field in the database.
	FieldDefaultBranch = "default_branch"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldDeletingAt holds the string denoting the deleting_at field in the database.
	FieldDeletingAt = "deleting_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the app in the database.
	Table = "apps"
)

// Columns holds all SQL columns for app fields.
var Columns = []string{
	FieldID,
	FieldOrgSlug,
	FieldName,
	FieldSlug,
	FieldCloudAccountID,
	FieldGithubInstallationID,
	FieldGithubRepoFullName,
	FieldDefaultBranch,
	FieldCreatedBy,
	FieldDeletingAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// OrgSlugValidator is a validator for the "org_slug" field. It is called by the builders before save.
	OrgSlugValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	SlugValidator func(string) error
	// GithubRepoFullNameValidator is a validator for the "github_repo_full_name" field. It is called by the builders before save.
	GithubRepoFullNameValidator func(string) error
	// DefaultBranchValidator is a validator for the "default_branch" field. It is called by the builders before save.
	DefaultBranchValidator func(string) error
	// CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	CreatedByValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the App queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOrgSlug orders the results by the org_slug field.
func ByOrgSlug(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrgSlug, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// BySlug orders the results by the slug field.
func BySlug(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSlug, opts...).ToFunc()
}

// ByCloudAccountID orders the results by the cloud_account_id field.
func ByCloudAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCloudAccountID, opts...).ToFunc()
}

// ByGithubInstallationID orders the results by the github_installation_id field.
func ByGithubInstallationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGithubInstallationID, opts...).ToFunc()
}

// ByGithubRepoFullName orders the results by the github_repo_full_name field.
func ByGithubRepoFullName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGithubRepoFullName, opts...).ToFunc()
}

// ByDefaultBranch orders the results by the default_branch field.
func ByDefaultBranch(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDefaultBranch, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByDeletingAt orders the results by the deleting_at field.
func ByDeletingAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletingAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
