// Code generated by ent, DO NOT EDIT.

package app

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/spacefleet/app/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.App {
	return predicate.App(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.App {
	return predicate.App(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.App {
	return predicate.App(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.App {
	return predicate.App(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.App {
	return predicate.App(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.App {
	return predicate.App(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.App {
	return predicate.App(sql.FieldLTE(FieldID, id))
}

// OrgSlug applies equality check predicate on the "org_slug" field. It's identical to OrgSlugEQ.
func OrgSlug(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldOrgSlug, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldName, v))
}

// Slug applies equality check predicate on the "slug" field. It's identical to SlugEQ.
func Slug(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldSlug, v))
}

// CloudAccountID applies equality check predicate on the "cloud_account_id" field. It's identical to CloudAccountIDEQ.
func CloudAccountID(v uuid.UUID) predicate.App {
	return predicate.App(sql.FieldEQ(FieldCloudAccountID, v))
}

// GithubInstallationID applies equality check predicate on the "github_installation_id" field. It's identical to GithubInstallationIDEQ.
func GithubInstallationID(v uuid.UUID) predicate.App {
	return predicate.App(sql.FieldEQ(FieldGithubInstallationID, v))
}

// GithubRepoFullName applies equality check predicate on the "github_repo_full_name" field. It's identical to GithubRepoFullNameEQ.
func GithubRepoFullName(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldGithubRepoFullName, v))
}

// DefaultBranch applies equality check predicate on the "default_branch" field. It's identical to DefaultBranchEQ.
func DefaultBranch(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldDefaultBranch, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldCreatedBy, v))
}

// DeletingAt applies equality check predicate on the "deleting_at" field. It's identical to DeletingAtEQ.
func DeletingAt(v time.Time) predicate.App {
	return predicate.App(sql.FieldEQ(FieldDeletingAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.App {
	return predicate.App(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.App {
	return predicate.App(sql.FieldEQ(FieldUpdatedAt, v))
}

// OrgSlugEQ applies the EQ predicate on the "org_slug" field.
func OrgSlugEQ(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldOrgSlug, v))
}

// OrgSlugNEQ applies the NEQ predicate on the "org_slug" field.
func OrgSlugNEQ(v string) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldOrgSlug, v))
}

// OrgSlugIn applies the In predicate on the "org_slug" field.
func OrgSlugIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldIn(FieldOrgSlug, vs...))
}

// OrgSlugNotIn applies the NotIn predicate on the "org_slug" field.
func OrgSlugNotIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldOrgSlug, vs...))
}

// OrgSlugGT applies the GT predicate on the "org_slug" field.
func OrgSlugGT(v string) predicate.App {
	return predicate.App(sql.FieldGT(FieldOrgSlug, v))
}

// OrgSlugGTE applies the GTE predicate on the "org_slug" field.
func OrgSlugGTE(v string) predicate.App {
	return predicate.App(sql.FieldGTE(FieldOrgSlug, v))
}

// OrgSlugLT applies the LT predicate on the "org_slug" field.
func OrgSlugLT(v string) predicate.App {
	return predicate.App(sql.FieldLT(FieldOrgSlug, v))
}

// OrgSlugLTE applies the LTE predicate on the "org_slug" field.
func OrgSlugLTE(v string) predicate.App {
	return predicate.App(sql.FieldLTE(FieldOrgSlug, v))
}

// OrgSlugContains applies the Contains predicate on the "org_slug" field.
func OrgSlugContains(v string) predicate.App {
	return predicate.App(sql.FieldContains(FieldOrgSlug, v))
}

// OrgSlugHasPrefix applies the HasPrefix predicate on the "org_slug" field.
func OrgSlugHasPrefix(v string) predicate.App {
	return predicate.App(sql.FieldHasPrefix(FieldOrgSlug, v))
}

// OrgSlugHasSuffix applies the HasSuffix predicate on the "org_slug" field.
func OrgSlugHasSuffix(v string) predicate.App {
	return predicate.App(sql.FieldHasSuffix(FieldOrgSlug, v))
}

// OrgSlugEqualFold applies the EqualFold predicate on the "org_slug" field.
func OrgSlugEqualFold(v string) predicate.App {
	return predicate.App(sql.FieldEqualFold(FieldOrgSlug, v))
}

// OrgSlugContainsFold applies the ContainsFold predicate on the "org_slug" field.
func OrgSlugContainsFold(v string) predicate.App {
	return predicate.App(sql.FieldContainsFold(FieldOrgSlug, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.App {
	return predicate.App(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.App {
	return predicate.App(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.App {
	return predicate.App(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.App {
	return predicate.App(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.App {
	return predicate.App(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.App {
	return predicate.App(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.App {
	return predicate.App(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.App {
	return predicate.App(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.App {
	return predicate.App(sql.FieldContainsFold(FieldName, v))
}

// SlugEQ applies the EQ predicate on the "slug" field.
func SlugEQ(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldSlug, v))
}

// SlugNEQ applies the NEQ predicate on the "slug" field.
func SlugNEQ(v string) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldSlug, v))
}

// SlugIn applies the In predicate on the "slug" field.
func SlugIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldIn(FieldSlug, vs...))
}

// SlugNotIn applies the NotIn predicate on the "slug" field.
func SlugNotIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldSlug, vs...))
}

// SlugGT applies the GT predicate on the "slug" field.
func SlugGT(v string) predicate.App {
	return predicate.App(sql.FieldGT(FieldSlug, v))
}

// SlugGTE applies the GTE predicate on the "slug" field.
func SlugGTE(v string) predicate.App {
	return predicate.App(sql.FieldGTE(FieldSlug, v))
}

// SlugLT applies the LT predicate on the "slug" field.
func SlugLT(v string) predicate.App {
	return predicate.App(sql.FieldLT(FieldSlug, v))
}

// SlugLTE applies the LTE predicate on the "slug" field.
func SlugLTE(v string) predicate.App {
	return predicate.App(sql.FieldLTE(FieldSlug, v))
}

// SlugContains applies the Contains predicate on the "slug" field.
func SlugContains(v string) predicate.App {
	return predicate.App(sql.FieldContains(FieldSlug, v))
}

// SlugHasPrefix applies the HasPrefix predicate on the "slug" field.
func SlugHasPrefix(v string) predicate.App {
	return predicate.App(sql.FieldHasPrefix(FieldSlug, v))
}

// SlugHasSuffix applies the HasSuffix predicate on the "slug" field.
func SlugHasSuffix(v string) predicate.App {
	return predicate.App(sql.FieldHasSuffix(FieldSlug, v))
}

// SlugEqualFold applies the EqualFold predicate on the "slug" field.
func SlugEqualFold(v string) predicate.App {
	return predicate.App(sql.FieldEqualFold(FieldSlug, v))
}

// SlugContainsFold applies the ContainsFold predicate on the "slug" field.
func SlugContainsFold(v string) predicate.App {
	return predicate.App(sql.FieldContainsFold(FieldSlug, v))
}

// CloudAccountIDEQ applies the EQ predicate on the "cloud_account_id" field.
func CloudAccountIDEQ(v uuid.UUID) predicate.App {
	return predicate.App(sql.FieldEQ(FieldCloudAccountID, v))
}

// CloudAccountIDNEQ applies the NEQ predicate on the "cloud_account_id" field.
func CloudAccountIDNEQ(v uuid.UUID) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldCloudAccountID, v))
}

// CloudAccountIDIn applies the In predicate on the "cloud_account_id" field.
func CloudAccountIDIn(vs ...uuid.UUID) predicate.App {
	return predicate.App(sql.FieldIn(FieldCloudAccountID, vs...))
}

// CloudAccountIDNotIn applies the NotIn predicate on the "cloud_account_id" field.
func CloudAccountIDNotIn(vs ...uuid.UUID) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldCloudAccountID, vs...))
}

// CloudAccountIDGT applies the GT predicate on the "cloud_account_id" field.
func CloudAccountIDGT(v uuid.UUID) predicate.App {
	return predicate.App(sql.FieldGT(FieldCloudAccountID, v))
}

// CloudAccountIDGTE applies the GTE predicate on the "cloud_account_id" field.
func CloudAccountIDGTE(v uuid.UUID) predicate.App {
	return predicate.App(sql.FieldGTE(FieldCloudAccountID, v))
}

// CloudAccountIDLT applies the LT predicate on the "cloud_account_id" field.
func CloudAccountIDLT(v uuid.UUID) predicate.App {
	return predicate.App(sql.FieldLT(FieldCloudAccountID, v))
}

// CloudAccountIDLTE applies the LTE predicate on the "cloud_account_id" field.
func CloudAccountIDLTE(v uuid.UUID) predicate.App {
	return predicate.App(sql.FieldLTE(FieldCloudAccountID, v))
}

// GithubInstallationIDEQ applies the EQ predicate on the "github_installation_id" field.
func GithubInstallationIDEQ(v uuid.UUID) predicate.App {
	return predicate.App(sql.FieldEQ(FieldGithubInstallationID, v))
}

// GithubInstallationIDNEQ applies the NEQ predicate on the "github_installation_id" field.
func GithubInstallationIDNEQ(v uuid.UUID) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldGithubInstallationID, v))
}

// GithubInstallationIDIn applies the In predicate on the "github_installation_id" field.
func GithubInstallationIDIn(vs ...uuid.UUID) predicate.App {
	return predicate.App(sql.FieldIn(FieldGithubInstallationID, vs...))
}

// GithubInstallationIDNotIn applies the NotIn predicate on the "github_installation_id" field.
func GithubInstallationIDNotIn(vs ...uuid.UUID) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldGithubInstallationID, vs...))
}

// GithubInstallationIDGT applies the GT predicate on the "github_installation_id" field.
func GithubInstallationIDGT(v uuid.UUID) predicate.App {
	return predicate.App(sql.FieldGT(FieldGithubInstallationID, v))
}

// GithubInstallationIDGTE applies the GTE predicate on the "github_installation_id" field.
func GithubInstallationIDGTE(v uuid.UUID) predicate.App {
	return predicate.App(sql.FieldGTE(FieldGithubInstallationID, v))
}

// GithubInstallationIDLT applies the LT predicate on the "github_installation_id" field.
func GithubInstallationIDLT(v uuid.UUID) predicate.App {
	return predicate.App(sql.FieldLT(FieldGithubInstallationID, v))
}

// GithubInstallationIDLTE applies the LTE predicate on the "github_installation_id" field.
func GithubInstallationIDLTE(v uuid.UUID) predicate.App {
	return predicate.App(sql.FieldLTE(FieldGithubInstallationID, v))
}

// GithubRepoFullNameEQ applies the EQ predicate on the "github_repo_full_name" field.
func GithubRepoFullNameEQ(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldGithubRepoFullName, v))
}

// GithubRepoFullNameNEQ applies the NEQ predicate on the "github_repo_full_name" field.
func GithubRepoFullNameNEQ(v string) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldGithubRepoFullName, v))
}

// GithubRepoFullNameIn applies the In predicate on the "github_repo_full_name" field.
func GithubRepoFullNameIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldIn(FieldGithubRepoFullName, vs...))
}

// GithubRepoFullNameNotIn applies the NotIn predicate on the "github_repo_full_name" field.
func GithubRepoFullNameNotIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldGithubRepoFullName, vs...))
}

// GithubRepoFullNameGT applies the GT predicate on the "github_repo_full_name" field.
func GithubRepoFullNameGT(v string) predicate.App {
	return predicate.App(sql.FieldGT(FieldGithubRepoFullName, v))
}

// GithubRepoFullNameGTE applies the GTE predicate on the "github_repo_full_name" field.
func GithubRepoFullNameGTE(v string) predicate.App {
	return predicate.App(sql.FieldGTE(FieldGithubRepoFullName, v))
}

// GithubRepoFullNameLT applies the LT predicate on the "github_repo_full_name" field.
func GithubRepoFullNameLT(v string) predicate.App {
	return predicate.App(sql.FieldLT(FieldGithubRepoFullName, v))
}

// GithubRepoFullNameLTE applies the LTE predicate on the "github_repo_full_name" field.
func GithubRepoFullNameLTE(v string) predicate.App {
	return predicate.App(sql.FieldLTE(FieldGithubRepoFullName, v))
}

// GithubRepoFullNameContains applies the Contains predicate on the "github_repo_full_name" field.
func GithubRepoFullNameContains(v string) predicate.App {
	return predicate.App(sql.FieldContains(FieldGithubRepoFullName, v))
}

// GithubRepoFullNameHasPrefix applies the HasPrefix predicate on the "github_repo_full_name" field.
func GithubRepoFullNameHasPrefix(v string) predicate.App {
	return predicate.App(sql.FieldHasPrefix(FieldGithubRepoFullName, v))
}

// GithubRepoFullNameHasSuffix applies the HasSuffix predicate on the "github_repo_full_name" field.
func GithubRepoFullNameHasSuffix(v string) predicate.App {
	return predicate.App(sql.FieldHasSuffix(FieldGithubRepoFullName, v))
}

// GithubRepoFullNameEqualFold applies the EqualFold predicate on the "github_repo_full_name" field.
func GithubRepoFullNameEqualFold(v string) predicate.App {
	return predicate.App(sql.FieldEqualFold(FieldGithubRepoFullName, v))
}

// GithubRepoFullNameContainsFold applies the ContainsFold predicate on the "github_repo_full_name" field.
func GithubRepoFullNameContainsFold(v string) predicate.App {
	return predicate.App(sql.FieldContainsFold(FieldGithubRepoFullName, v))
}

// DefaultBranchEQ applies the EQ predicate on the "default_branch" field.
func DefaultBranchEQ(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldDefaultBranch, v))
}

// DefaultBranchNEQ applies the NEQ predicate on the "default_branch" field.
func DefaultBranchNEQ(v string) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldDefaultBranch, v))
}

// DefaultBranchIn applies the In predicate on the "default_branch" field.
func DefaultBranchIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldIn(FieldDefaultBranch, vs...))
}

// DefaultBranchNotIn applies the NotIn predicate on the "default_branch" field.
func DefaultBranchNotIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldDefaultBranch, vs...))
}

// DefaultBranchGT applies the GT predicate on the "default_branch" field.
func DefaultBranchGT(v string) predicate.App {
	return predicate.App(sql.FieldGT(FieldDefaultBranch, v))
}

// DefaultBranchGTE applies the GTE predicate on the "default_branch" field.
func DefaultBranchGTE(v string) predicate.App {
	return predicate.App(sql.FieldGTE(FieldDefaultBranch, v))
}

// DefaultBranchLT applies the LT predicate on the "default_branch" field.
func DefaultBranchLT(v string) predicate.App {
	return predicate.App(sql.FieldLT(FieldDefaultBranch, v))
}

// DefaultBranchLTE applies the LTE predicate on the "default_branch" field.
func DefaultBranchLTE(v string) predicate.App {
	return predicate.App(sql.FieldLTE(FieldDefaultBranch, v))
}

// DefaultBranchContains applies the Contains predicate on the "default_branch" field.
func DefaultBranchContains(v string) predicate.App {
	return predicate.App(sql.FieldContains(FieldDefaultBranch, v))
}

// DefaultBranchHasPrefix applies the HasPrefix predicate on the "default_branch" field.
func DefaultBranchHasPrefix(v string) predicate.App {
	return predicate.App(sql.FieldHasPrefix(FieldDefaultBranch, v))
}

// DefaultBranchHasSuffix applies the HasSuffix predicate on the "default_branch" field.
func DefaultBranchHasSuffix(v string) predicate.App {
	return predicate.App(sql.FieldHasSuffix(FieldDefaultBranch, v))
}

// DefaultBranchEqualFold applies the EqualFold predicate on the "default_branch" field.
func DefaultBranchEqualFold(v string) predicate.App {
	return predicate.App(sql.FieldEqualFold(FieldDefaultBranch, v))
}

// DefaultBranchContainsFold applies the ContainsFold predicate on the "default_branch" field.
func DefaultBranchContainsFold(v string) predicate.App {
	return predicate.App(sql.FieldContainsFold(FieldDefaultBranch, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.App {
	return predicate.App(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.App {
	return predicate.App(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.App {
	return predicate.App(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.App {
	return predicate.App(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.App {
	return predicate.App(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.App {
	return predicate.App(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.App {
	return predicate.App(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.App {
	return predicate.App(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.App {
	return predicate.App(sql.FieldContainsFold(FieldCreatedBy, v))
}

// DeletingAtEQ applies the EQ predicate on the "deleting_at" field.
func DeletingAtEQ(v time.Time) predicate.App {
	return predicate.App(sql.FieldEQ(FieldDeletingAt, v))
}

// DeletingAtNEQ applies the NEQ predicate on the "deleting_at" field.
func DeletingAtNEQ(v time.Time) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldDeletingAt, v))
}

// DeletingAtIn applies the In predicate on the "deleting_at" field.
func DeletingAtIn(vs ...time.Time) predicate.App {
	return predicate.App(sql.FieldIn(FieldDeletingAt, vs...))
}

// DeletingAtNotIn applies the NotIn predicate on the "deleting_at" field.
func DeletingAtNotIn(vs ...time.Time) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldDeletingAt, vs...))
}

// DeletingAtGT applies the GT predicate on the "deleting_at" field.
func DeletingAtGT(v time.Time) predicate.App {
	return predicate.App(sql.FieldGT(FieldDeletingAt, v))
}

// DeletingAtGTE applies the GTE predicate on the "deleting_at" field.
func DeletingAtGTE(v time.Time) predicate.App {
	return predicate.App(sql.FieldGTE(FieldDeletingAt, v))
}

// DeletingAtLT applies the LT predicate on the "deleting_at" field.
func DeletingAtLT(v time.Time) predicate.App {
	return predicate.App(sql.FieldLT(FieldDeletingAt, v))
}

// DeletingAtLTE applies the LTE predicate on the "deleting_at" field.
func DeletingAtLTE(v time.Time) predicate.App {
	return predicate.App(sql.FieldLTE(FieldDeletingAt, v))
}

// DeletingAtIsNil applies the IsNil predicate on the "deleting_at" field.
func DeletingAtIsNil() predicate.App {
	return predicate.App(sql.FieldIsNull(FieldDeletingAt))
}

// DeletingAtNotNil applies the NotNil predicate on the "deleting_at" field.
func DeletingAtNotNil() predicate.App {
	return predicate.App(sql.FieldNotNull(FieldDeletingAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.App {
	return predicate.App(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.App {
	return predicate.App(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.App {
	return predicate.App(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.App {
	return predicate.App(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.App {
	return predicate.App(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.App {
	return predicate.App(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.App {
	return predicate.App(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.App {
	return predicate.App(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.App {
	return predicate.App(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.App {
	return predicate.App(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.App {
	return predicate.App(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.App {
	return predicate.App(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.App) predicate.App {
	return predicate.App(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.App) predicate.App {
	return predicate.App(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.App) predicate.App {
	return predicate.App(sql.NotPredicates(p))
}
