// Code generated by ent, DO NOT EDIT.

package cloudaccount

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the cloudaccount type in the database.
	Label = "cloud_account"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOrgSlug holds the string denoting the org_slug field in the database.
	FieldOrgSlug = "org_slug"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldLabel holds the string denoting the label field in the database.
	FieldLabel = "label"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldRoleArn holds the string denoting the role_arn field in the database.
	FieldRoleArn = "role_arn"
	// FieldExternalID holds the string denoting the external_id field in the database.
	FieldExternalID = "external_id"
	// FieldRegion holds the string denoting the region field in the database.
	FieldRegion = "region"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldLastVerifiedAt holds the string denoting the last_verified_at field in the database.
	FieldLastVerifiedAt = "last_verified_at"
	// FieldLastVerificationError holds the string denoting the last_verification_error field in the database.
	FieldLastVerificationError = "last_verification_error"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the cloudaccount in the database.
	Table = "cloud_accounts"
)

// Columns holds all SQL columns for cloudaccount fields.
var Columns = []string{
	FieldID,
	FieldOrgSlug,
	FieldProvider,
	FieldLabel,
	FieldAccountID,
	FieldRoleArn,
	FieldExternalID,
	FieldRegion,
	FieldStatus,
	FieldLastVerifiedAt,
	FieldLastVerificationError,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// OrgSlugValidator is a validator for the "org_slug" field. It is called by the builders before save.
	OrgSlugValidator func(string) error
	// DefaultProvider holds the default value on creation for the "provider" field.
	DefaultProvider string
	// ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	ProviderValidator func(string) error
	// LabelValidator is a validator for the "label" field. It is called by the builders before save.
	LabelValidator func(string) error
	// ExternalIDValidator is a validator for the "external_id" field. It is called by the builders before save.
	ExternalIDValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the CloudAccount queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOrgSlug orders the results by the org_slug field.
func ByOrgSlug(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrgSlug, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByLabel orders the results by the label field.
func ByLabel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLabel, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByRoleArn orders the results by the role_arn field.
func ByRoleArn(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRoleArn, opts...).ToFunc()
}

// ByExternalID orders the results by the external_id field.
func ByExternalID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExternalID, opts...).ToFunc()
}

// ByRegion orders the results by the region field.
func ByRegion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRegion, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByLastVerifiedAt orders the results by the last_verified_at field.
func ByLastVerifiedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastVerifiedAt, opts...).ToFunc()
}

// ByLastVerificationError orders the results by the last_verification_error field.
func ByLastVerificationError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastVerificationError, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
