// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// App is the predicate function for app builders.
type App func(*sql.Selector)

// Build is the predicate function for build builders.
type Build func(*sql.Selector)

// CLIAuthCode is the predicate function for cliauthcode builders.
type CLIAuthCode func(*sql.Selector)

// CLIToken is the predicate function for clitoken builders.
type CLIToken func(*sql.Selector)

// CloudAccount is the predicate function for cloudaccount builders.
type CloudAccount func(*sql.Selector)

// GithubInstallState is the predicate function for githubinstallstate builders.
type GithubInstallState func(*sql.Selector)

// GithubInstallation is the predicate function for githubinstallation builders.
type GithubInstallation func(*sql.Selector)
