// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CLIAuthCode is the predicate function for cliauthcode builders.
type CLIAuthCode func(*sql.Selector)

// CLIToken is the predicate function for clitoken builders.
type CLIToken func(*sql.Selector)

// GithubInstallState is the predicate function for githubinstallstate builders.
type GithubInstallState func(*sql.Selector)

// GithubInstallation is the predicate function for githubinstallation builders.
type GithubInstallation func(*sql.Selector)
